using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace FreeGLBA.Controllers;

// ============================================================================
// GLBA EXTERNAL API CONTROLLER
// Receives events from external source systems via API key authentication.
// Generated by FreeManager for template: FreeAudit
// ============================================================================

[ApiController]
[Route("api/glba")]
[ApiRequestLogging]
public class GlbaController : ControllerBase
{
    private readonly IDataAccess _da;

    public GlbaController(IDataAccess da)
    {
        _da = da;
    }

    // ============================================================
    // EXTERNAL ENDPOINTS (API Key Auth via middleware)
    // ============================================================

    /// <summary>
    /// Receive a single event from an external source system.
    /// Requires API key in Authorization header: Bearer {api-key}
    /// </summary>
    [HttpPost("events")]
    public async Task<ActionResult<DataObjects.GlbaEventResponse>> PostEvent(
        [FromBody] DataObjects.GlbaEventRequest request)
    {
        // Get source system from middleware (set by ApiKeyMiddleware)
        var source = HttpContext.Items["SourceSystem"] as DataObjects.SourceSystem;
        if (source == null)
        {
            return Unauthorized(new { error = "invalid_api_key", message = "API key is invalid or inactive" });
        }

        var result = await _da.ProcessGlbaEventAsync(request, source.SourceSystemId);

        return result.Status switch
        {
            "accepted" => Created($"/api/glba/events/{result.EventId}", result),
            "duplicate" => Conflict(result),
            _ => BadRequest(result)
        };
    }

    /// <summary>
    /// Receive a batch of events from an external source system.
    /// Maximum 1000 events per request.
    /// </summary>
    [HttpPost("events/batch")]
    public async Task<ActionResult<DataObjects.GlbaBatchResponse>> PostBatch(
        [FromBody] List<DataObjects.GlbaEventRequest> events)
    {
        var source = HttpContext.Items["SourceSystem"] as DataObjects.SourceSystem;
        if (source == null)
        {
            return Unauthorized(new { error = "invalid_api_key", message = "API key is invalid or inactive" });
        }

        if (events.Count > 1000)
        {
            return BadRequest(new { error = "batch_too_large", message = "Maximum 1000 events per batch" });
        }

        var result = await _da.ProcessGlbaBatchAsync(events, source.SourceSystemId);
        return Ok(result);
    }

    // ============================================================
    // INTERNAL ENDPOINTS (User Auth)
    // ============================================================

    /// <summary>
    /// Get summary statistics for the dashboard.
    /// </summary>
    [HttpGet("stats/summary")]
    [Authorize]
    public async Task<ActionResult<DataObjects.GlbaStats>> GetStats()
    {
        var stats = await _da.GetGlbaStatsAsync();
        return Ok(stats);
    }

    /// <summary>
    /// Get recent events for the dashboard feed.
    /// </summary>
    [HttpGet("events/recent")]
    [Authorize]
    public async Task<ActionResult<List<DataObjects.AccessEvent>>> GetRecentEvents(
        [FromQuery] int limit = 50)
    {
        var events = await _da.GetRecentAccessEventsAsync(Math.Min(limit, 100));
        return Ok(events);
    }

    /// <summary>
    /// Get access events for a specific subject by external ID.
    /// </summary>
    [HttpGet("subjects/{subjectId}/events")]
    [Authorize]
    public async Task<ActionResult<List<DataObjects.AccessEvent>>> GetSubjectEvents(
        string subjectId, [FromQuery] int limit = 100)
    {
        var events = await _da.GetAccessEventsBySubjectAsync(subjectId, Math.Min(limit, 500));
        return Ok(events);
    }

    /// <summary>
    /// Get a single access event by ID.
    /// </summary>
    [HttpGet("events/{eventId:guid}")]
    [Authorize]
    public async Task<ActionResult<DataObjects.AccessEvent>> GetEvent(Guid eventId)
    {
        var evt = await _da.GetAccessEventAsync(eventId);
        if (evt == null) return NotFound();
        return Ok(evt);
    }

    /// <summary>
    /// Get source system status for the dashboard.
    /// </summary>
    [HttpGet("sources/status")]
    [Authorize]
    public async Task<ActionResult<List<DataObjects.SourceSystem>>> GetSourceStatus()
    {
        var sources = await _da.GetSourceSystemsAsync();
        return Ok(sources);
    }

    /// <summary>
    /// Get top accessors (users who have accessed data) for the dashboard.
    /// </summary>
    [HttpGet("accessors/top")]
    [Authorize]
    public async Task<ActionResult<List<DataObjects.AccessorSummary>>> GetTopAccessors(
        [FromQuery] int limit = 10)
    {
        var accessors = await _da.GetTopAccessorsAsync(Math.Min(limit, 50));
        return Ok(accessors);
    }
}
