namespace FreeManager.Client;

#region PagePatterns - DataImportWizard
// ============================================================================
// PAGE PATTERN: DATA IMPORT WIZARD
// Multi-step file upload with column mapping and validation.
//
// Generated Files:
// - ImportWizard.App.razor (main wizard container)
// - UploadStep.App.razor (drag-drop file upload)
// - MappingStep.App.razor (column mapping interface)
// - ValidateStep.App.razor (validation preview)
// - ProgressStep.App.razor (import progress tracking)
// ============================================================================

public static partial class PagePatterns
{
    /// <summary>
    /// Generate DataImportWizard files for the given entity/project.
    /// </summary>
    public static List<(string FileName, string FileType, string Content)> GetDataImportWizardFiles(
        string projectName,
        DataObjects.EntityDefinition? entity = null)
    {
        List<(string, string, string)> files = new();
        string entityName = entity?.Name ?? "Item";
        string pluralName = entity?.PluralName ?? "Items";

        files.Add(($"{projectName}.App.ImportWizard.razor", "RazorComponent", GetDataImportWizard_ImportWizard(projectName, entityName, pluralName)));
        files.Add(($"{projectName}.App.UploadStep.razor", "RazorComponent", GetDataImportWizard_UploadStep(projectName, entityName)));
        files.Add(($"{projectName}.App.MappingStep.razor", "RazorComponent", GetDataImportWizard_MappingStep(projectName, entityName)));
        files.Add(($"{projectName}.App.ValidateStep.razor", "RazorComponent", GetDataImportWizard_ValidateStep(projectName, entityName)));
        files.Add(($"{projectName}.App.ProgressStep.razor", "RazorComponent", GetDataImportWizard_ProgressStep(projectName, entityName)));

        return files;
    }

    // ============================================================
    // IMPORT WIZARD - Main Container
    // ============================================================

    private static string GetDataImportWizard_ImportWizard(string name, string entityName, string pluralName) => $@"@* {name} - ImportWizard.razor *@
@* Data Import Wizard for {entityName} - Generated by Page Pattern *@
@page ""/import/{pluralName.ToLower()}""
@page ""/{{TenantCode}}/import/{pluralName.ToLower()}""
@implements IDisposable
@inject BlazorDataModel Model
@inject HttpClient Http
@inject IJSRuntime JS

@if (Model.Loaded && Model.LoggedIn) {{
    <div class=""container-fluid py-4"">
        <div class=""row justify-content-center"">
            <div class=""col-lg-10"">
                <div class=""card shadow"">
                    <div class=""card-header bg-primary text-white"">
                        <h4 class=""mb-0"">
                            <i class=""fa-solid fa-file-import me-2""></i>Import {pluralName}
                        </h4>
                    </div>
                    <div class=""card-body"">
                        @* Step Progress Indicator *@
                        <div class=""mb-4"">
                            <div class=""d-flex justify-content-between align-items-center position-relative"">
                                <div class=""position-absolute top-50 start-0 end-0"" style=""height: 2px; background: #dee2e6; z-index: 0;""></div>
                                @for (int i = 1; i <= 4; i++) {{
                                    var stepNum = i;
                                    var isActive = stepNum == _currentStep;
                                    var isCompleted = stepNum < _currentStep;
                                    <div class=""position-relative bg-white px-2 z-1"">
                                        <div class=""rounded-circle d-flex align-items-center justify-content-center @(isCompleted ? ""bg-success text-white"" : isActive ? ""bg-primary text-white"" : ""bg-light text-muted"")""
                                             style=""width: 40px; height: 40px;"">
                                            @if (isCompleted) {{
                                                <i class=""fa-solid fa-check""></i>
                                            }} else {{
                                                @stepNum
                                            }}
                                        </div>
                                        <div class=""text-center mt-1 small @(isActive ? ""fw-bold"" : ""text-muted"")"">@GetStepName(stepNum)</div>
                                    </div>
                                }}
                            </div>
                        </div>

                        @* Step Content *@
                        @switch (_currentStep) {{
                            case 1:
                                <{name}_App_UploadStep
                                    OnFileUploaded=""HandleFileUploaded""
                                    OnError=""HandleError"" />
                                break;
                            case 2:
                                <{name}_App_MappingStep
                                    CsvColumns=""_csvColumns""
                                    EntityProperties=""_entityProperties""
                                    ColumnMappings=""_columnMappings""
                                    OnMappingsChanged=""HandleMappingsChanged""
                                    OnBack=""GoBack"" />
                                break;
                            case 3:
                                <{name}_App_ValidateStep
                                    PreviewData=""_previewData""
                                    ValidationErrors=""_validationErrors""
                                    OnBack=""GoBack""
                                    OnConfirm=""StartImport"" />
                                break;
                            case 4:
                                <{name}_App_ProgressStep
                                    Progress=""_importProgress""
                                    TotalRows=""_totalRows""
                                    ProcessedRows=""_processedRows""
                                    FailedRows=""_failedRows""
                                    IsComplete=""_importComplete""
                                    OnRollback=""HandleRollback""
                                    OnClose=""ResetWizard"" />
                                break;
                        }}

                        @* Error Display *@
                        @if (!string.IsNullOrEmpty(_errorMessage)) {{
                            <div class=""alert alert-danger mt-3"">
                                <i class=""fa-solid fa-exclamation-triangle me-2""></i>@_errorMessage
                                <button type=""button"" class=""btn-close float-end"" @onclick=""() => _errorMessage = string.Empty""></button>
                            </div>
                        }}
                    </div>
                </div>
            </div>
        </div>
    </div>
}}

@code {{
    private int _currentStep = 1;
    private string _errorMessage = string.Empty;

    // Upload state
    private byte[]? _fileContent;
    private string _fileName = string.Empty;

    // Mapping state
    private List<string> _csvColumns = new();
    private List<string> _entityProperties = new() {{ ""Name"", ""Description"", ""Email"", ""Phone"", ""Address"", ""Status"", ""CreatedAt"" }};
    private Dictionary<string, string> _columnMappings = new();

    // Validation state
    private List<Dictionary<string, object?>> _previewData = new();
    private List<ImportValidationError> _validationErrors = new();

    // Progress state
    private int _importProgress = 0;
    private int _totalRows = 0;
    private int _processedRows = 0;
    private List<ImportFailedRow> _failedRows = new();
    private bool _importComplete = false;
    private List<Guid> _importedIds = new();

    public void Dispose() {{ Model.OnChange -= StateHasChanged; }}

    protected override void OnInitialized()
    {{
        Model.OnChange += StateHasChanged;
    }}

    private string GetStepName(int step) => step switch
    {{
        1 => ""Upload"",
        2 => ""Mapping"",
        3 => ""Validate"",
        4 => ""Import"",
        _ => """"
    }};

    private void HandleFileUploaded((byte[] content, string fileName, List<string> columns, List<Dictionary<string, object?>> preview) data)
    {{
        _fileContent = data.content;
        _fileName = data.fileName;
        _csvColumns = data.columns;
        _previewData = data.preview;

        // Auto-map matching column names
        foreach (var col in _csvColumns)
        {{
            var match = _entityProperties.FirstOrDefault(p =>
                p.Equals(col, StringComparison.OrdinalIgnoreCase) ||
                p.Replace("" "", """").Equals(col.Replace("" "", """"), StringComparison.OrdinalIgnoreCase));
            if (match != null)
            {{
                _columnMappings[col] = match;
            }}
        }}

        _currentStep = 2;
        StateHasChanged();
    }}

    private void HandleMappingsChanged(Dictionary<string, string> mappings)
    {{
        _columnMappings = mappings;
        ValidateData();
        _currentStep = 3;
        StateHasChanged();
    }}

    private void ValidateData()
    {{
        _validationErrors.Clear();
        int rowNum = 0;

        foreach (var row in _previewData)
        {{
            rowNum++;
            foreach (var mapping in _columnMappings)
            {{
                if (row.TryGetValue(mapping.Key, out var value))
                {{
                    // Basic validation checks
                    if (mapping.Value.Contains(""Email"") && value != null)
                    {{
                        var email = value.ToString();
                        if (!string.IsNullOrEmpty(email) && !email!.Contains(""@""))
                        {{
                            _validationErrors.Add(new ImportValidationError
                            {{
                                RowNumber = rowNum,
                                ColumnName = mapping.Key,
                                Value = email,
                                Message = ""Invalid email format""
                            }});
                        }}
                    }}
                }}
            }}
        }}
    }}

    private async Task StartImport()
    {{
        _currentStep = 4;
        _totalRows = _previewData.Count;
        _processedRows = 0;
        _failedRows.Clear();
        _importedIds.Clear();
        _importComplete = false;
        StateHasChanged();

        // Simulate import process
        foreach (var row in _previewData)
        {{
            await Task.Delay(100); // Simulate API call

            try
            {{
                // TODO: Call actual import API
                _importedIds.Add(Guid.NewGuid());
                _processedRows++;
            }}
            catch (Exception ex)
            {{
                _failedRows.Add(new ImportFailedRow
                {{
                    RowNumber = _processedRows + 1,
                    Data = row,
                    ErrorMessage = ex.Message
                }});
            }}

            _importProgress = (int)((_processedRows / (double)_totalRows) * 100);
            StateHasChanged();
        }}

        _importComplete = true;
        StateHasChanged();
    }}

    private async Task HandleRollback()
    {{
        if (!await Helpers.Confirm(""Are you sure you want to rollback all imported records?""))
            return;

        // TODO: Call rollback API with _importedIds
        foreach (var id in _importedIds)
        {{
            // await Helpers.GetOrPost<bool>(DataObjects.Endpoints.{name}.Delete{entityName}, id);
        }}

        ResetWizard();
    }}

    private void GoBack()
    {{
        if (_currentStep > 1)
        {{
            _currentStep--;
            StateHasChanged();
        }}
    }}

    private void ResetWizard()
    {{
        _currentStep = 1;
        _fileContent = null;
        _fileName = string.Empty;
        _csvColumns.Clear();
        _columnMappings.Clear();
        _previewData.Clear();
        _validationErrors.Clear();
        _importProgress = 0;
        _totalRows = 0;
        _processedRows = 0;
        _failedRows.Clear();
        _importedIds.Clear();
        _importComplete = false;
        _errorMessage = string.Empty;
        StateHasChanged();
    }}

    private void HandleError(string message)
    {{
        _errorMessage = message;
        StateHasChanged();
    }}

    public class ImportValidationError
    {{
        public int RowNumber {{ get; set; }}
        public string ColumnName {{ get; set; }} = string.Empty;
        public string? Value {{ get; set; }}
        public string Message {{ get; set; }} = string.Empty;
    }}

    public class ImportFailedRow
    {{
        public int RowNumber {{ get; set; }}
        public Dictionary<string, object?> Data {{ get; set; }} = new();
        public string ErrorMessage {{ get; set; }} = string.Empty;
    }}
}}
";

    // ============================================================
    // UPLOAD STEP - Drag & Drop File Upload
    // ============================================================

    private static string GetDataImportWizard_UploadStep(string name, string entityName) => $@"@* {name} - UploadStep.razor *@
@* File Upload Step with Drag-Drop Support *@

<div class=""text-center py-4"">
    <div class=""upload-zone border border-2 border-dashed rounded-3 p-5 @(_isDragging ? ""border-primary bg-light"" : ""border-secondary"")""
         @ondragenter=""HandleDragEnter""
         @ondragover=""HandleDragOver""
         @ondragover:preventDefault
         @ondragleave=""HandleDragLeave""
         @ondrop=""HandleDrop""
         @ondrop:preventDefault>

        @if (_isProcessing) {{
            <div class=""mb-3"">
                <i class=""fa-solid fa-spinner fa-spin fa-3x text-primary""></i>
            </div>
            <h5>Processing file...</h5>
        }} else if (!string.IsNullOrEmpty(_uploadedFileName)) {{
            <div class=""mb-3"">
                <i class=""fa-solid fa-file-csv fa-3x text-success""></i>
            </div>
            <h5 class=""text-success"">@_uploadedFileName</h5>
            <p class=""text-muted mb-3"">@_rowCount rows detected</p>
            <button class=""btn btn-primary btn-lg"" @onclick=""ProceedToMapping"">
                <i class=""fa-solid fa-arrow-right me-2""></i>Continue to Mapping
            </button>
            <button class=""btn btn-outline-secondary ms-2"" @onclick=""ClearFile"">
                <i class=""fa-solid fa-times me-1""></i>Clear
            </button>
        }} else {{
            <div class=""mb-3"">
                <i class=""fa-solid fa-cloud-arrow-up fa-3x text-muted""></i>
            </div>
            <h5>Drag & drop your CSV file here</h5>
            <p class=""text-muted mb-3"">or</p>
            <label class=""btn btn-primary btn-lg"">
                <i class=""fa-solid fa-folder-open me-2""></i>Browse Files
                <InputFile OnChange=""HandleFileSelected"" accept="".csv,.txt"" class=""d-none"" />
            </label>
            <p class=""text-muted mt-3 small"">Supported formats: CSV, TXT (max 10MB)</p>
        }}
    </div>

    <div class=""mt-4"">
        <div class=""card bg-light"">
            <div class=""card-body"">
                <h6 class=""card-title""><i class=""fa-solid fa-lightbulb text-warning me-2""></i>Import Tips</h6>
                <ul class=""text-start mb-0 small"">
                    <li>Ensure your CSV file has headers in the first row</li>
                    <li>Use UTF-8 encoding for special characters</li>
                    <li>Maximum 10,000 rows per import</li>
                    <li>You can map columns in the next step</li>
                </ul>
            </div>
        </div>
    </div>
</div>

@code {{
    [Parameter] public EventCallback<(byte[] content, string fileName, List<string> columns, List<Dictionary<string, object?>> preview)> OnFileUploaded {{ get; set; }}
    [Parameter] public EventCallback<string> OnError {{ get; set; }}

    private bool _isDragging = false;
    private bool _isProcessing = false;
    private string _uploadedFileName = string.Empty;
    private int _rowCount = 0;
    private byte[]? _fileContent;
    private List<string> _columns = new();
    private List<Dictionary<string, object?>> _previewData = new();

    private void HandleDragEnter() => _isDragging = true;
    private void HandleDragOver() => _isDragging = true;
    private void HandleDragLeave() => _isDragging = false;

    private async Task HandleDrop(DragEventArgs e)
    {{
        _isDragging = false;
        // Note: Browser file drop requires JS interop for full implementation
        // This is a placeholder - actual implementation would use JS to get dropped files
    }}

    private async Task HandleFileSelected(InputFileChangeEventArgs e)
    {{
        var file = e.File;

        if (file.Size > 10 * 1024 * 1024)
        {{
            await OnError.InvokeAsync(""File size exceeds 10MB limit"");
            return;
        }}

        _isProcessing = true;
        StateHasChanged();

        try
        {{
            using var stream = file.OpenReadStream(maxAllowedSize: 10 * 1024 * 1024);
            using var memoryStream = new System.IO.MemoryStream();
            await stream.CopyToAsync(memoryStream);
            _fileContent = memoryStream.ToArray();

            // Parse CSV
            var content = System.Text.Encoding.UTF8.GetString(_fileContent);
            var lines = content.Split(new[] {{ ""\r\n"", ""\n"" }}, StringSplitOptions.RemoveEmptyEntries);

            if (lines.Length < 2)
            {{
                await OnError.InvokeAsync(""File must contain at least a header row and one data row"");
                _isProcessing = false;
                return;
            }}

            // Parse headers
            _columns = ParseCsvLine(lines[0]);

            // Parse preview data (first 100 rows)
            _previewData.Clear();
            for (int i = 1; i < Math.Min(lines.Length, 101); i++)
            {{
                var values = ParseCsvLine(lines[i]);
                var row = new Dictionary<string, object?>();
                for (int j = 0; j < Math.Min(_columns.Count, values.Count); j++)
                {{
                    row[_columns[j]] = values[j];
                }}
                _previewData.Add(row);
            }}

            _uploadedFileName = file.Name;
            _rowCount = lines.Length - 1;
        }}
        catch (Exception ex)
        {{
            await OnError.InvokeAsync($""Error processing file: {{ex.Message}}"");
        }}

        _isProcessing = false;
        StateHasChanged();
    }}

    private List<string> ParseCsvLine(string line)
    {{
        var result = new List<string>();
        var inQuotes = false;
        var field = new System.Text.StringBuilder();

        for (int i = 0; i < line.Length; i++)
        {{
            var c = line[i];

            if (c == '""')
            {{
                inQuotes = !inQuotes;
            }}
            else if (c == ',' && !inQuotes)
            {{
                result.Add(field.ToString().Trim());
                field.Clear();
            }}
            else
            {{
                field.Append(c);
            }}
        }}

        result.Add(field.ToString().Trim());
        return result;
    }}

    private async Task ProceedToMapping()
    {{
        if (_fileContent != null && _columns.Count > 0)
        {{
            await OnFileUploaded.InvokeAsync((_fileContent, _uploadedFileName, _columns, _previewData));
        }}
    }}

    private void ClearFile()
    {{
        _fileContent = null;
        _uploadedFileName = string.Empty;
        _rowCount = 0;
        _columns.Clear();
        _previewData.Clear();
    }}
}}
";

    // ============================================================
    // MAPPING STEP - Column Mapping Interface
    // ============================================================

    private static string GetDataImportWizard_MappingStep(string name, string entityName) => $@"@* {name} - MappingStep.razor *@
@* Column Mapping Interface *@

<div class=""py-3"">
    <div class=""d-flex justify-content-between align-items-center mb-4"">
        <h5 class=""mb-0"">
            <i class=""fa-solid fa-arrows-left-right me-2""></i>Map CSV Columns to {entityName} Fields
        </h5>
        <div>
            <button class=""btn btn-outline-secondary me-2"" @onclick=""AutoMap"">
                <i class=""fa-solid fa-magic me-1""></i>Auto-Map
            </button>
            <button class=""btn btn-outline-secondary"" @onclick=""ClearMappings"">
                <i class=""fa-solid fa-eraser me-1""></i>Clear All
            </button>
        </div>
    </div>

    <div class=""card"">
        <div class=""table-responsive"">
            <table class=""table table-hover mb-0"">
                <thead class=""table-light"">
                    <tr>
                        <th style=""width: 40%;"">CSV Column</th>
                        <th style=""width: 20%;"" class=""text-center"">
                            <i class=""fa-solid fa-arrow-right""></i>
                        </th>
                        <th style=""width: 40%;"">{entityName} Field</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var column in CsvColumns) {{
                        <tr>
                            <td>
                                <div class=""d-flex align-items-center"">
                                    <i class=""fa-solid fa-table-columns text-muted me-2""></i>
                                    <span class=""fw-medium"">@column</span>
                                </div>
                            </td>
                            <td class=""text-center"">
                                @if (_localMappings.ContainsKey(column) && !string.IsNullOrEmpty(_localMappings[column])) {{
                                    <i class=""fa-solid fa-link text-success""></i>
                                }} else {{
                                    <i class=""fa-solid fa-minus text-muted""></i>
                                }}
                            </td>
                            <td>
                                <select class=""form-select form-select-sm""
                                        value=""@(_localMappings.GetValueOrDefault(column) ?? """")""
                                        @onchange=""e => UpdateMapping(column, e.Value?.ToString())"">
                                    <option value="""">(Skip this column)</option>
                                    @foreach (var prop in EntityProperties) {{
                                        <option value=""@prop"" disabled=""@IsPropertyMapped(prop, column)"">
                                            @prop @(IsPropertyMapped(prop, column) ? ""(already mapped)"" : """")
                                        </option>
                                    }}
                                </select>
                            </td>
                        </tr>
                    }}
                </tbody>
            </table>
        </div>
    </div>

    <div class=""mt-3"">
        <div class=""row"">
            <div class=""col-md-6"">
                <div class=""card bg-light"">
                    <div class=""card-body py-2"">
                        <div class=""d-flex justify-content-between"">
                            <span class=""text-muted"">Mapped columns:</span>
                            <strong class=""text-success"">@MappedCount / @CsvColumns.Count</strong>
                        </div>
                    </div>
                </div>
            </div>
            <div class=""col-md-6"">
                <div class=""card bg-light"">
                    <div class=""card-body py-2"">
                        <div class=""d-flex justify-content-between"">
                            <span class=""text-muted"">Skipped columns:</span>
                            <strong class=""text-warning"">@(CsvColumns.Count - MappedCount)</strong>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class=""d-flex justify-content-between mt-4"">
        <button class=""btn btn-outline-secondary"" @onclick=""OnBack"">
            <i class=""fa-solid fa-arrow-left me-1""></i>Back
        </button>
        <button class=""btn btn-primary"" @onclick=""ProceedToValidation"" disabled=""@(MappedCount == 0)"">
            Continue to Validation<i class=""fa-solid fa-arrow-right ms-1""></i>
        </button>
    </div>
</div>

@code {{
    [Parameter] public List<string> CsvColumns {{ get; set; }} = new();
    [Parameter] public List<string> EntityProperties {{ get; set; }} = new();
    [Parameter] public Dictionary<string, string> ColumnMappings {{ get; set; }} = new();
    [Parameter] public EventCallback<Dictionary<string, string>> OnMappingsChanged {{ get; set; }}
    [Parameter] public EventCallback OnBack {{ get; set; }}

    private Dictionary<string, string> _localMappings = new();

    private int MappedCount => _localMappings.Count(m => !string.IsNullOrEmpty(m.Value));

    protected override void OnParametersSet()
    {{
        _localMappings = new Dictionary<string, string>(ColumnMappings);
        foreach (var col in CsvColumns)
        {{
            if (!_localMappings.ContainsKey(col))
            {{
                _localMappings[col] = string.Empty;
            }}
        }}
    }}

    private void UpdateMapping(string column, string? property)
    {{
        _localMappings[column] = property ?? string.Empty;
    }}

    private bool IsPropertyMapped(string property, string currentColumn)
    {{
        return _localMappings.Any(m => m.Value == property && m.Key != currentColumn);
    }}

    private void AutoMap()
    {{
        foreach (var col in CsvColumns)
        {{
            var match = EntityProperties.FirstOrDefault(p =>
                p.Equals(col, StringComparison.OrdinalIgnoreCase) ||
                p.Replace("" "", """").Equals(col.Replace("" "", """"), StringComparison.OrdinalIgnoreCase) ||
                p.Replace(""_"", """").Equals(col.Replace(""_"", """"), StringComparison.OrdinalIgnoreCase));

            if (match != null && !IsPropertyMapped(match, col))
            {{
                _localMappings[col] = match;
            }}
        }}
    }}

    private void ClearMappings()
    {{
        foreach (var col in CsvColumns)
        {{
            _localMappings[col] = string.Empty;
        }}
    }}

    private async Task ProceedToValidation()
    {{
        var mappings = _localMappings.Where(m => !string.IsNullOrEmpty(m.Value))
                                      .ToDictionary(m => m.Key, m => m.Value);
        await OnMappingsChanged.InvokeAsync(mappings);
    }}
}}
";

    // ============================================================
    // VALIDATE STEP - Validation Preview
    // ============================================================

    private static string GetDataImportWizard_ValidateStep(string name, string entityName) => $@"@* {name} - ValidateStep.razor *@
@* Validation Preview Step *@

<div class=""py-3"">
    <div class=""d-flex justify-content-between align-items-center mb-4"">
        <h5 class=""mb-0"">
            <i class=""fa-solid fa-clipboard-check me-2""></i>Review & Validate Data
        </h5>
        <div>
            @if (ValidationErrors.Count == 0) {{
                <span class=""badge bg-success fs-6"">
                    <i class=""fa-solid fa-check me-1""></i>No validation errors
                </span>
            }} else {{
                <span class=""badge bg-warning text-dark fs-6"">
                    <i class=""fa-solid fa-exclamation-triangle me-1""></i>@ValidationErrors.Count validation issue(s)
                </span>
            }}
        </div>
    </div>

    @if (ValidationErrors.Count > 0) {{
        <div class=""alert alert-warning mb-4"">
            <h6 class=""alert-heading"">
                <i class=""fa-solid fa-exclamation-triangle me-2""></i>Validation Issues Found
            </h6>
            <p class=""mb-2"">The following issues were found in your data. You can still proceed, but these rows may fail to import:</p>
            <div class=""table-responsive"" style=""max-height: 200px; overflow-y: auto;"">
                <table class=""table table-sm table-bordered mb-0 bg-white"">
                    <thead>
                        <tr>
                            <th>Row</th>
                            <th>Column</th>
                            <th>Value</th>
                            <th>Issue</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var error in ValidationErrors.Take(20)) {{
                            <tr>
                                <td>@error.RowNumber</td>
                                <td>@error.ColumnName</td>
                                <td><code>@(error.Value ?? ""(empty)"")</code></td>
                                <td class=""text-danger"">@error.Message</td>
                            </tr>
                        }}
                        @if (ValidationErrors.Count > 20) {{
                            <tr>
                                <td colspan=""4"" class=""text-center text-muted"">
                                    ... and @(ValidationErrors.Count - 20) more issues
                                </td>
                            </tr>
                        }}
                    </tbody>
                </table>
            </div>
        </div>
    }}

    <div class=""card mb-4"">
        <div class=""card-header d-flex justify-content-between align-items-center"">
            <span><i class=""fa-solid fa-table me-2""></i>Data Preview (first 10 rows)</span>
            <span class=""badge bg-secondary"">@PreviewData.Count total rows</span>
        </div>
        <div class=""table-responsive"" style=""max-height: 400px; overflow: auto;"">
            <table class=""table table-sm table-striped mb-0"">
                <thead class=""table-light sticky-top"">
                    <tr>
                        <th>#</th>
                        @if (PreviewData.Count > 0) {{
                            @foreach (var col in PreviewData[0].Keys) {{
                                <th>@col</th>
                            }}
                        }}
                    </tr>
                </thead>
                <tbody>
                    @{{ int rowNum = 0; }}
                    @foreach (var row in PreviewData.Take(10)) {{
                        rowNum++;
                        var hasError = ValidationErrors.Any(e => e.RowNumber == rowNum);
                        <tr class=""@(hasError ? ""table-warning"" : """")"">
                            <td>
                                @rowNum
                                @if (hasError) {{
                                    <i class=""fa-solid fa-exclamation-circle text-warning ms-1""></i>
                                }}
                            </td>
                            @foreach (var val in row.Values) {{
                                <td>@(val?.ToString() ?? """")</td>
                            }}
                        </tr>
                    }}
                </tbody>
            </table>
        </div>
    </div>

    <div class=""card bg-light mb-4"">
        <div class=""card-body"">
            <h6 class=""card-title""><i class=""fa-solid fa-info-circle me-2""></i>Import Summary</h6>
            <div class=""row"">
                <div class=""col-md-4"">
                    <div class=""d-flex justify-content-between"">
                        <span>Total rows to import:</span>
                        <strong>@PreviewData.Count</strong>
                    </div>
                </div>
                <div class=""col-md-4"">
                    <div class=""d-flex justify-content-between"">
                        <span>Rows with warnings:</span>
                        <strong class=""text-warning"">@ValidationErrors.Select(e => e.RowNumber).Distinct().Count()</strong>
                    </div>
                </div>
                <div class=""col-md-4"">
                    <div class=""d-flex justify-content-between"">
                        <span>Expected success:</span>
                        <strong class=""text-success"">@(PreviewData.Count - ValidationErrors.Select(e => e.RowNumber).Distinct().Count())</strong>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class=""d-flex justify-content-between"">
        <button class=""btn btn-outline-secondary"" @onclick=""OnBack"">
            <i class=""fa-solid fa-arrow-left me-1""></i>Back to Mapping
        </button>
        <button class=""btn btn-success btn-lg"" @onclick=""OnConfirm"">
            <i class=""fa-solid fa-play me-1""></i>Start Import
        </button>
    </div>
</div>

@code {{
    [Parameter] public List<Dictionary<string, object?>> PreviewData {{ get; set; }} = new();
    [Parameter] public List<ImportValidationError> ValidationErrors {{ get; set; }} = new();
    [Parameter] public EventCallback OnBack {{ get; set; }}
    [Parameter] public EventCallback OnConfirm {{ get; set; }}

    public class ImportValidationError
    {{
        public int RowNumber {{ get; set; }}
        public string ColumnName {{ get; set; }} = string.Empty;
        public string? Value {{ get; set; }}
        public string Message {{ get; set; }} = string.Empty;
    }}
}}
";

    // ============================================================
    // PROGRESS STEP - Import Progress Tracking
    // ============================================================

    private static string GetDataImportWizard_ProgressStep(string name, string entityName) => $@"@* {name} - ProgressStep.razor *@
@* Import Progress Tracking Step *@

<div class=""py-3"">
    <div class=""text-center mb-4"">
        @if (IsComplete) {{
            @if (FailedRows.Count == 0) {{
                <div class=""mb-3"">
                    <i class=""fa-solid fa-check-circle fa-4x text-success""></i>
                </div>
                <h4 class=""text-success"">Import Complete!</h4>
                <p class=""text-muted"">Successfully imported @ProcessedRows {entityName.ToLower()} records.</p>
            }} else {{
                <div class=""mb-3"">
                    <i class=""fa-solid fa-exclamation-circle fa-4x text-warning""></i>
                </div>
                <h4 class=""text-warning"">Import Completed with Errors</h4>
                <p class=""text-muted"">Imported @(ProcessedRows - FailedRows.Count) of @TotalRows records. @FailedRows.Count row(s) failed.</p>
            }}
        }} else {{
            <div class=""mb-3"">
                <i class=""fa-solid fa-cog fa-spin fa-4x text-primary""></i>
            </div>
            <h4>Importing Data...</h4>
            <p class=""text-muted"">Please wait while your data is being imported.</p>
        }}
    </div>

    <div class=""card mb-4"">
        <div class=""card-body"">
            <div class=""d-flex justify-content-between mb-2"">
                <span>Progress</span>
                <span class=""fw-bold"">@ProcessedRows / @TotalRows rows</span>
            </div>
            <div class=""progress"" style=""height: 25px;"">
                <div class=""progress-bar @(IsComplete && FailedRows.Count == 0 ? ""bg-success"" : IsComplete ? ""bg-warning"" : """")""
                     role=""progressbar""
                     style=""width: @Progress%;""
                     aria-valuenow=""@Progress""
                     aria-valuemin=""0""
                     aria-valuemax=""100"">
                    @Progress%
                </div>
            </div>
        </div>
    </div>

    @if (IsComplete) {{
        <div class=""row mb-4"">
            <div class=""col-md-4"">
                <div class=""card text-center border-success"">
                    <div class=""card-body"">
                        <i class=""fa-solid fa-check text-success fa-2x mb-2""></i>
                        <h3 class=""text-success mb-0"">@(ProcessedRows - FailedRows.Count)</h3>
                        <small class=""text-muted"">Successful</small>
                    </div>
                </div>
            </div>
            <div class=""col-md-4"">
                <div class=""card text-center border-danger"">
                    <div class=""card-body"">
                        <i class=""fa-solid fa-times text-danger fa-2x mb-2""></i>
                        <h3 class=""text-danger mb-0"">@FailedRows.Count</h3>
                        <small class=""text-muted"">Failed</small>
                    </div>
                </div>
            </div>
            <div class=""col-md-4"">
                <div class=""card text-center"">
                    <div class=""card-body"">
                        <i class=""fa-solid fa-clock text-muted fa-2x mb-2""></i>
                        <h3 class=""mb-0"">@TotalRows</h3>
                        <small class=""text-muted"">Total Processed</small>
                    </div>
                </div>
            </div>
        </div>
    }}

    @if (FailedRows.Count > 0) {{
        <div class=""card border-danger mb-4"">
            <div class=""card-header bg-danger text-white"">
                <i class=""fa-solid fa-exclamation-triangle me-2""></i>Failed Rows
            </div>
            <div class=""table-responsive"" style=""max-height: 300px; overflow-y: auto;"">
                <table class=""table table-sm mb-0"">
                    <thead class=""table-light sticky-top"">
                        <tr>
                            <th>Row</th>
                            <th>Error</th>
                            <th>Data Preview</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var failed in FailedRows) {{
                            <tr>
                                <td>@failed.RowNumber</td>
                                <td class=""text-danger"">@failed.ErrorMessage</td>
                                <td><code>@string.Join("", "", failed.Data.Take(3).Select(d => $""{{d.Key}}: {{d.Value}}""))</code></td>
                            </tr>
                        }}
                    </tbody>
                </table>
            </div>
        </div>
    }}

    @if (IsComplete) {{
        <div class=""d-flex justify-content-between"">
            <button class=""btn btn-outline-danger"" @onclick=""OnRollback"" disabled=""@(ProcessedRows == FailedRows.Count)"">
                <i class=""fa-solid fa-rotate-left me-1""></i>Rollback Import
            </button>
            <div>
                @if (FailedRows.Count > 0) {{
                    <button class=""btn btn-outline-secondary me-2"" @onclick=""DownloadFailedRows"">
                        <i class=""fa-solid fa-download me-1""></i>Download Failed Rows
                    </button>
                }}
                <button class=""btn btn-primary"" @onclick=""OnClose"">
                    <i class=""fa-solid fa-check me-1""></i>Done
                </button>
            </div>
        </div>
    }}
</div>

@code {{
    [Parameter] public int Progress {{ get; set; }}
    [Parameter] public int TotalRows {{ get; set; }}
    [Parameter] public int ProcessedRows {{ get; set; }}
    [Parameter] public List<ImportFailedRow> FailedRows {{ get; set; }} = new();
    [Parameter] public bool IsComplete {{ get; set; }}
    [Parameter] public EventCallback OnRollback {{ get; set; }}
    [Parameter] public EventCallback OnClose {{ get; set; }}

    private void DownloadFailedRows()
    {{
        // TODO: Implement CSV export of failed rows
        // This would create a CSV with the failed row data for user review
    }}

    public class ImportFailedRow
    {{
        public int RowNumber {{ get; set; }}
        public Dictionary<string, object?> Data {{ get; set; }} = new();
        public string ErrorMessage {{ get; set; }} = string.Empty;
    }}
}}
";
}

#endregion
