using System.Text;

namespace FreeManager;

#region WizardTemplates - Service/State Templates
// ============================================================================
// WIZARD TEMPLATES - STATE & SERVICE
// State DTO and Service class generators.
// Part of: WizardTemplates.App (partial)
// ============================================================================

public static partial class WizardTemplates
{
    /// <summary>
    /// Generate the State DTO containing all wizard data.
    /// </summary>
    public static string GenerateStateDto(DataObjects.SetupWizardDefinition wizard)
    {
        var sb = new StringBuilder();
        var name = wizard.Name;

        sb.AppendLine("// Auto-generated by FreeManager Setup Wizard Builder");
        sb.AppendLine("// Do not modify manually - regenerate instead");
        sb.AppendLine();
        sb.AppendLine("namespace DataObjects;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// State object for {name} wizard.");
        sb.AppendLine($"/// {wizard.Description}");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public class {name}State");
        sb.AppendLine("{");
        sb.AppendLine("    public Guid UserId { get; set; }");
        sb.AppendLine("    public int CurrentStep { get; set; }");
        sb.AppendLine("    public bool IsCompleted { get; set; }");
        sb.AppendLine("    public DateTime StartedAt { get; set; } = DateTime.UtcNow;");
        sb.AppendLine("    public DateTime? CompletedAt { get; set; }");
        sb.AppendLine("    public List<int> SkippedSteps { get; set; } = new();");
        sb.AppendLine();

        foreach (var step in wizard.Steps.OrderBy(s => s.Order))
        {
            var stepClassName = $"Step{step.Order + 1}Data";
            sb.AppendLine($"    public {stepClassName} {stepClassName.Replace("Data", "")} {{ get; set; }} = new();");
        }

        sb.AppendLine("}");
        sb.AppendLine();

        foreach (var step in wizard.Steps.OrderBy(s => s.Order))
        {
            var stepClassName = $"Step{step.Order + 1}Data";
            sb.AppendLine($"/// <summary>Data for step {step.Order + 1}: {step.Name}</summary>");
            sb.AppendLine($"public class {stepClassName}");
            sb.AppendLine("{");

            foreach (var field in step.Fields)
            {
                if (!string.IsNullOrWhiteSpace(field.Description))
                {
                    sb.AppendLine($"    /// <summary>{field.Description}</summary>");
                }
                var nullableMarker = !field.IsRequired && field.Type != "string" ? "?" : "";
                var defaultValue = GetDefaultValue(field);
                sb.AppendLine($"    public {field.Type}{nullableMarker} {field.Name} {{ get; set; }}{defaultValue}");
            }

            if (!step.Fields.Any())
            {
                sb.AppendLine("    // Add properties for this step");
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    /// <summary>
    /// Generate the Service for state persistence.
    /// </summary>
    public static string GenerateService(DataObjects.SetupWizardDefinition wizard)
    {
        var sb = new StringBuilder();
        var name = wizard.Name;

        sb.AppendLine("// Auto-generated by FreeManager Setup Wizard Builder");
        sb.AppendLine();
        sb.AppendLine("namespace Services;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Service for managing {name} wizard state.</summary>");
        sb.AppendLine($"public class {name}Service");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IHttpClientFactory _httpClientFactory;");
        sb.AppendLine();
        sb.AppendLine($"    public {name}Service(IHttpClientFactory httpClientFactory)");
        sb.AppendLine("    {");
        sb.AppendLine("        _httpClientFactory = httpClientFactory;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public async Task<DataObjects.{name}State> GetStateAsync(Guid userId)");
        sb.AppendLine("    {");
        sb.AppendLine("        // TODO: Load from database or cache");
        sb.AppendLine($"        return new DataObjects.{name}State {{ UserId = userId }};");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public async Task SaveStateAsync(DataObjects.{name}State state)");
        sb.AppendLine("    {");
        sb.AppendLine("        // TODO: Persist to database");
        sb.AppendLine("        await Task.CompletedTask;");
        sb.AppendLine("    }");
        sb.AppendLine();

        if (wizard.TrackCompletion)
        {
            sb.AppendLine($"    public async Task MarkCompletedAsync(Guid userId)");
            sb.AppendLine("    {");
            sb.AppendLine("        // TODO: Record completion in database");
            sb.AppendLine("        await Task.CompletedTask;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Generate the Validator using FluentValidation.
    /// </summary>
    public static string GenerateValidator(DataObjects.SetupWizardDefinition wizard)
    {
        var sb = new StringBuilder();
        var name = wizard.Name;

        sb.AppendLine("// Auto-generated by FreeManager Setup Wizard Builder");
        sb.AppendLine();
        sb.AppendLine("using FluentValidation;");
        sb.AppendLine();
        sb.AppendLine("namespace Validators;");
        sb.AppendLine();
        sb.AppendLine($"public class {name}StateValidator : AbstractValidator<DataObjects.{name}State>");
        sb.AppendLine("{");
        sb.AppendLine($"    public {name}StateValidator()");
        sb.AppendLine("    {");

        foreach (var step in wizard.Steps.OrderBy(s => s.Order))
        {
            var stepNum = step.Order + 1;
            foreach (var field in step.Fields.Where(f => f.IsRequired))
            {
                if (field.Type.ToLower() == "string")
                {
                    sb.AppendLine($"        RuleFor(x => x.Step{stepNum}.{field.Name})");
                    sb.AppendLine($"            .NotEmpty().WithMessage(\"{ToDisplayName(field.Name)} is required\");");
                }
                else
                {
                    sb.AppendLine($"        RuleFor(x => x.Step{stepNum}.{field.Name})");
                    sb.AppendLine($"            .NotNull().WithMessage(\"{ToDisplayName(field.Name)} is required\");");
                }
            }
        }

        if (!wizard.Steps.SelectMany(s => s.Fields).Any(f => f.IsRequired))
        {
            sb.AppendLine("        // Add validation rules for required fields");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    // ============================================================
    // HELPERS
    // ============================================================

    private static string GetDefaultValue(DataObjects.PropertyDefinition field)
    {
        if (!string.IsNullOrWhiteSpace(field.DefaultValue))
        {
            return $" = {field.DefaultValue};";
        }

        return field.Type switch
        {
            "string" => " = string.Empty;",
            "bool" => " = false;",
            "int" => " = 0;",
            _ => ""
        };
    }

    private static string ToDisplayName(string name)
    {
        var result = new StringBuilder();
        foreach (var c in name)
        {
            if (char.IsUpper(c) && result.Length > 0)
            {
                result.Append(' ');
            }
            result.Append(c);
        }
        return result.ToString();
    }
}

#endregion
