namespace FreeManager.Client;

#region PagePatterns - TimelineActivityFeed
// ============================================================================
// PAGE PATTERN: TIMELINE ACTIVITY FEED
// Chronological event history grouped by date
//
// Generated Files:
// Timeline.App.razor, TimelineDay.App.razor, TimelineEvent.App.razor, TimelineFilters.App.razor
// ============================================================================

public static partial class PagePatterns
{
    /// <summary>
    /// Generate TimelineActivityFeed files for the given entity/project.
    /// </summary>
    public static List<(string FileName, string FileType, string Content)> GetTimelineActivityFeedFiles(
        string projectName,
        DataObjects.EntityDefinition? entity = null)
    {
        List<(string, string, string)> files = new();

        files.Add(($"{projectName}.App.Timeline.razor", "RazorComponent", GetTimelineActivityFeed_Timeline(projectName, entity)));
        files.Add(($"{projectName}.App.TimelineDay.razor", "RazorComponent", GetTimelineActivityFeed_TimelineDay(projectName, entity)));
        files.Add(($"{projectName}.App.TimelineEvent.razor", "RazorComponent", GetTimelineActivityFeed_TimelineEvent(projectName, entity)));
        files.Add(($"{projectName}.App.TimelineFilters.razor", "RazorComponent", GetTimelineActivityFeed_TimelineFilters(projectName, entity)));

        return files;
    }

    // ============================================================
    // TIMELINE.RAZOR - Main timeline container with infinite scroll
    // ============================================================
    private static string GetTimelineActivityFeed_Timeline(string name, DataObjects.EntityDefinition? entity) => $@"@* {name} - Timeline Activity Feed *@
@* Generated by Page Pattern: TimelineActivityFeed *@
@page ""/{name}/Timeline""
@page ""/{{TenantCode}}/{name}/Timeline""
@implements IDisposable
@inject BlazorDataModel Model
@inject HttpClient Http
@inject IJSRuntime JS

@if (Model.Loaded && Model.LoggedIn && Model.View == _pageName) {{
    <div class=""container-fluid"">
        <div class=""@Model.StickyMenuClass"">
            <div class=""d-flex justify-content-between align-items-center"">
                <h1 class=""page-title mb-0"">
                    <i class=""fa-solid fa-clock-rotate-left me-2""></i>Activity Timeline
                </h1>
                <button class=""btn btn-outline-secondary"" @onclick=""ToggleFilters"">
                    <i class=""fa-solid fa-filter me-1""></i>Filters
                    @if (_filtersActive) {{
                        <span class=""badge bg-primary ms-1"">@_activeFilterCount</span>
                    }}
                </button>
            </div>
        </div>

        @if (_showFilters) {{
            <{name}_App_TimelineFilters
                Filter=""_filter""
                OnFilterChanged=""ApplyFilters""
                OnClose=""ToggleFilters"" />
        }}

        <div class=""timeline-container mt-3"">
            @if (_loading && _events.Count == 0) {{
                <div class=""text-center py-5"">
                    <i class=""fa-solid fa-spinner fa-spin fa-2x""></i>
                    <p class=""mt-2 text-muted"">Loading activity...</p>
                </div>
            }} else if (_events.Count == 0) {{
                <div class=""text-center py-5 text-muted"">
                    <i class=""fa-solid fa-inbox fa-4x mb-3 opacity-50""></i>
                    <h4>No activity found</h4>
                    <p>Events will appear here as they occur</p>
                </div>
            }} else {{
                @foreach (var dayGroup in _groupedEvents) {{
                    <{name}_App_TimelineDay
                        Date=""dayGroup.Key""
                        Events=""dayGroup.Value""
                        OnEntityClick=""NavigateToEntity"" />
                }}

                @if (_hasMore) {{
                    <div class=""text-center py-3"" @ref=""_loadMoreTrigger"">
                        @if (_loadingMore) {{
                            <i class=""fa-solid fa-spinner fa-spin""></i>
                            <span class=""ms-2"">Loading more...</span>
                        }} else {{
                            <button class=""btn btn-outline-primary"" @onclick=""LoadMore"">
                                <i class=""fa-solid fa-chevron-down me-1""></i>Load More
                            </button>
                        }}
                    </div>
                }}
            }}
        </div>
    </div>
}}

@code {{
    private string _pageName = ""{name.ToLower()}-timeline"";
    private bool _loading = true;
    private bool _loadingMore = false;
    private bool _showFilters = false;
    private bool _filtersActive = false;
    private int _activeFilterCount = 0;
    private bool _hasMore = true;
    private int _page = 0;
    private const int _pageSize = 20;

    private TimelineFilter _filter = new();
    private List<TimelineEvent> _events = new();
    private Dictionary<DateTime, List<TimelineEvent>> _groupedEvents = new();
    private ElementReference _loadMoreTrigger;

    public void Dispose() {{ Model.OnChange -= StateHasChanged; }}

    protected override void OnInitialized()
    {{
        Model.View = _pageName;
        Model.OnChange += StateHasChanged;
    }}

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {{
        if (firstRender) await LoadData();
    }}

    private async Task LoadData()
    {{
        _loading = true;
        _page = 0;
        _events.Clear();
        StateHasChanged();

        var result = await Helpers.GetOrPost<TimelineResult>(
            DataObjects.Endpoints.{name}.GetTimelineEvents,
            new {{ Filter = _filter, Page = _page, PageSize = _pageSize }}) ?? new();

        _events = result.Events;
        _hasMore = result.HasMore;
        GroupEventsByDate();
        _loading = false;
        StateHasChanged();
    }}

    private async Task LoadMore()
    {{
        if (_loadingMore || !_hasMore) return;

        _loadingMore = true;
        _page++;
        StateHasChanged();

        var result = await Helpers.GetOrPost<TimelineResult>(
            DataObjects.Endpoints.{name}.GetTimelineEvents,
            new {{ Filter = _filter, Page = _page, PageSize = _pageSize }}) ?? new();

        _events.AddRange(result.Events);
        _hasMore = result.HasMore;
        GroupEventsByDate();
        _loadingMore = false;
        StateHasChanged();
    }}

    private void GroupEventsByDate()
    {{
        _groupedEvents = _events
            .GroupBy(e => e.Timestamp.Date)
            .OrderByDescending(g => g.Key)
            .ToDictionary(g => g.Key, g => g.OrderByDescending(e => e.Timestamp).ToList());
    }}

    private void ToggleFilters()
    {{
        _showFilters = !_showFilters;
    }}

    private async Task ApplyFilters(TimelineFilter filter)
    {{
        _filter = filter;
        _filtersActive = !filter.IsEmpty();
        _activeFilterCount = filter.GetActiveCount();
        _showFilters = false;
        await LoadData();
    }}

    private void NavigateToEntity(TimelineEvent evt)
    {{
        if (!string.IsNullOrEmpty(evt.EntityUrl))
        {{
            Model.NavigateTo(evt.EntityUrl);
        }}
    }}

    // Data models
    public class TimelineFilter
    {{
        public DateTime? StartDate {{ get; set; }}
        public DateTime? EndDate {{ get; set; }}
        public List<string> EventTypes {{ get; set; }} = new();
        public List<Guid> UserIds {{ get; set; }} = new();
        public string SearchText {{ get; set; }} = string.Empty;

        public bool IsEmpty() =>
            !StartDate.HasValue && !EndDate.HasValue &&
            EventTypes.Count == 0 && UserIds.Count == 0 &&
            string.IsNullOrWhiteSpace(SearchText);

        public int GetActiveCount()
        {{
            int count = 0;
            if (StartDate.HasValue || EndDate.HasValue) count++;
            if (EventTypes.Count > 0) count++;
            if (UserIds.Count > 0) count++;
            if (!string.IsNullOrWhiteSpace(SearchText)) count++;
            return count;
        }}
    }}

    public class TimelineEvent
    {{
        public Guid Id {{ get; set; }}
        public DateTime Timestamp {{ get; set; }}
        public string EventType {{ get; set; }} = string.Empty;
        public string Icon {{ get; set; }} = ""fa-circle"";
        public string IconColor {{ get; set; }} = ""secondary"";
        public string Title {{ get; set; }} = string.Empty;
        public string Description {{ get; set; }} = string.Empty;
        public string UserName {{ get; set; }} = string.Empty;
        public string? UserAvatar {{ get; set; }}
        public Guid? EntityId {{ get; set; }}
        public string? EntityType {{ get; set; }}
        public string? EntityName {{ get; set; }}
        public string? EntityUrl {{ get; set; }}
        public Dictionary<string, object>? Metadata {{ get; set; }}
    }}

    public class TimelineResult
    {{
        public List<TimelineEvent> Events {{ get; set; }} = new();
        public bool HasMore {{ get; set; }}
        public int TotalCount {{ get; set; }}
    }}
}}
";

    // ============================================================
    // TIMELINEDAY.RAZOR - Group of events for a single day
    // ============================================================
    private static string GetTimelineActivityFeed_TimelineDay(string name, DataObjects.EntityDefinition? entity) => $@"@* {name} - Timeline Day Component *@
@* Generated by Page Pattern: TimelineActivityFeed *@

<div class=""timeline-day mb-4"">
    <div class=""timeline-day-header sticky-top bg-body py-2 mb-3"" style=""z-index: 10;"">
        <div class=""d-flex align-items-center"">
            <div class=""timeline-date-badge me-3"">
                <span class=""badge bg-primary fs-6 px-3 py-2"">
                    <i class=""fa-solid fa-calendar-day me-1""></i>
                    @GetDateLabel(Date)
                </span>
            </div>
            <div class=""flex-grow-1 border-bottom""></div>
            <span class=""ms-3 text-muted small"">@Events.Count @(Events.Count == 1 ? ""event"" : ""events"")</span>
        </div>
    </div>

    <div class=""timeline-events position-relative ps-4"">
        @* Vertical timeline line *@
        <div class=""timeline-line position-absolute""
             style=""left: 11px; top: 0; bottom: 0; width: 2px; background: linear-gradient(to bottom, var(--bs-primary), var(--bs-gray-300));"">
        </div>

        @foreach (var evt in Events) {{
            <{name}_App_TimelineEvent Event=""evt"" OnEntityClick=""HandleEntityClick"" />
        }}
    </div>
</div>

@code {{
    [Parameter] public DateTime Date {{ get; set; }}
    [Parameter] public List<TimelineEvent> Events {{ get; set; }} = new();
    [Parameter] public EventCallback<TimelineEvent> OnEntityClick {{ get; set; }}

    private string GetDateLabel(DateTime date)
    {{
        var today = DateTime.Today;
        if (date.Date == today) return ""Today"";
        if (date.Date == today.AddDays(-1)) return ""Yesterday"";
        if (date.Date > today.AddDays(-7)) return date.ToString(""dddd"");
        return date.ToString(""MMM dd, yyyy"");
    }}

    private async Task HandleEntityClick(TimelineEvent evt)
    {{
        await OnEntityClick.InvokeAsync(evt);
    }}

    // Reference to parent's TimelineEvent class
    public class TimelineEvent
    {{
        public Guid Id {{ get; set; }}
        public DateTime Timestamp {{ get; set; }}
        public string EventType {{ get; set; }} = string.Empty;
        public string Icon {{ get; set; }} = ""fa-circle"";
        public string IconColor {{ get; set; }} = ""secondary"";
        public string Title {{ get; set; }} = string.Empty;
        public string Description {{ get; set; }} = string.Empty;
        public string UserName {{ get; set; }} = string.Empty;
        public string? UserAvatar {{ get; set; }}
        public Guid? EntityId {{ get; set; }}
        public string? EntityType {{ get; set; }}
        public string? EntityName {{ get; set; }}
        public string? EntityUrl {{ get; set; }}
        public Dictionary<string, object>? Metadata {{ get; set; }}
    }}
}}

<style>
    .timeline-day-header {{
        backdrop-filter: blur(8px);
    }}

    .timeline-events {{
        padding-left: 2rem;
    }}
</style>
";

    // ============================================================
    // TIMELINEEVENT.RAZOR - Individual event item
    // ============================================================
    private static string GetTimelineActivityFeed_TimelineEvent(string name, DataObjects.EntityDefinition? entity) => $@"@* {name} - Timeline Event Component *@
@* Generated by Page Pattern: TimelineActivityFeed *@

<div class=""timeline-event mb-3 position-relative"">
    @* Event dot on timeline *@
    <div class=""timeline-dot position-absolute d-flex align-items-center justify-content-center rounded-circle bg-white border border-2""
         style=""left: -24px; top: 4px; width: 24px; height: 24px; border-color: var(--bs-@Event.IconColor) !important;"">
        <i class=""fa-solid @Event.Icon text-@Event.IconColor"" style=""font-size: 10px;""></i>
    </div>

    <div class=""card shadow-sm hover-shadow"" style=""transition: box-shadow 0.2s ease;"">
        <div class=""card-body py-2 px-3"">
            <div class=""d-flex justify-content-between align-items-start"">
                <div class=""flex-grow-1"">
                    <div class=""d-flex align-items-center mb-1"">
                        @* User avatar *@
                        @if (!string.IsNullOrEmpty(Event.UserAvatar)) {{
                            <img src=""@Event.UserAvatar"" alt=""@Event.UserName""
                                 class=""rounded-circle me-2"" style=""width: 24px; height: 24px; object-fit: cover;"" />
                        }} else {{
                            <div class=""rounded-circle bg-secondary text-white d-flex align-items-center justify-content-center me-2""
                                 style=""width: 24px; height: 24px; font-size: 11px;"">
                                @GetInitials(Event.UserName)
                            </div>
                        }}

                        <span class=""fw-semibold text-dark"">@Event.UserName</span>
                        <span class=""text-muted mx-1"">·</span>
                        <span class=""badge bg-@Event.IconColor bg-opacity-10 text-@Event.IconColor small"">
                            @Event.EventType
                        </span>
                    </div>

                    <div class=""event-content"">
                        <span class=""text-dark"">@Event.Title</span>

                        @if (Event.EntityId.HasValue && !string.IsNullOrEmpty(Event.EntityName)) {{
                            <button class=""btn btn-link btn-sm p-0 ms-1 text-decoration-none""
                                    @onclick=""() => HandleClick()""
                                    @onclick:stopPropagation=""true"">
                                <i class=""fa-solid fa-arrow-up-right-from-square me-1"" style=""font-size: 10px;""></i>
                                @Event.EntityName
                            </button>
                        }}
                    </div>

                    @if (!string.IsNullOrEmpty(Event.Description)) {{
                        <p class=""text-muted small mb-0 mt-1"">@Event.Description</p>
                    }}
                </div>

                <div class=""text-end ms-3"">
                    <small class=""text-muted"" title=""@Event.Timestamp.ToString(""f"")"">
                        @GetRelativeTime(Event.Timestamp)
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>

@code {{
    [Parameter] public TimelineEvent Event {{ get; set; }} = new();
    [Parameter] public EventCallback<TimelineEvent> OnEntityClick {{ get; set; }}

    private string GetInitials(string name)
    {{
        if (string.IsNullOrWhiteSpace(name)) return ""?"";
        var parts = name.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length >= 2)
            return $""{{parts[0][0]}}{{parts[1][0]}}"".ToUpper();
        return name.Length > 0 ? name[0].ToString().ToUpper() : ""?"";
    }}

    private string GetRelativeTime(DateTime timestamp)
    {{
        var diff = DateTime.UtcNow - timestamp;

        if (diff.TotalMinutes < 1) return ""Just now"";
        if (diff.TotalMinutes < 60) return $""{{(int)diff.TotalMinutes}}m ago"";
        if (diff.TotalHours < 24) return $""{{(int)diff.TotalHours}}h ago"";
        if (diff.TotalDays < 7) return $""{{(int)diff.TotalDays}}d ago"";
        return timestamp.ToString(""MMM dd"");
    }}

    private async Task HandleClick()
    {{
        await OnEntityClick.InvokeAsync(Event);
    }}

    // Reference to parent's TimelineEvent class
    public class TimelineEvent
    {{
        public Guid Id {{ get; set; }}
        public DateTime Timestamp {{ get; set; }}
        public string EventType {{ get; set; }} = string.Empty;
        public string Icon {{ get; set; }} = ""fa-circle"";
        public string IconColor {{ get; set; }} = ""secondary"";
        public string Title {{ get; set; }} = string.Empty;
        public string Description {{ get; set; }} = string.Empty;
        public string UserName {{ get; set; }} = string.Empty;
        public string? UserAvatar {{ get; set; }}
        public Guid? EntityId {{ get; set; }}
        public string? EntityType {{ get; set; }}
        public string? EntityName {{ get; set; }}
        public string? EntityUrl {{ get; set; }}
        public Dictionary<string, object>? Metadata {{ get; set; }}
    }}
}}

<style>
    .timeline-event .card:hover {{
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1) !important;
    }}

    .hover-shadow:hover {{
        transform: translateX(2px);
    }}
</style>
";

    // ============================================================
    // TIMELINEFILTERS.RAZOR - Filter panel for timeline
    // ============================================================
    private static string GetTimelineActivityFeed_TimelineFilters(string name, DataObjects.EntityDefinition? entity) => $@"@* {name} - Timeline Filters Component *@
@* Generated by Page Pattern: TimelineActivityFeed *@

<div class=""card shadow-sm mb-3"">
    <div class=""card-header d-flex justify-content-between align-items-center py-2"">
        <h6 class=""mb-0"">
            <i class=""fa-solid fa-filter me-2""></i>Filter Activity
        </h6>
        <button class=""btn btn-sm btn-close"" @onclick=""Close""></button>
    </div>
    <div class=""card-body"">
        <div class=""row g-3"">
            @* Date Range *@
            <div class=""col-md-3"">
                <label class=""form-label small text-muted"">From Date</label>
                <input type=""date"" class=""form-control form-control-sm""
                       @bind=""Filter.StartDate"" @bind:event=""onchange"" />
            </div>
            <div class=""col-md-3"">
                <label class=""form-label small text-muted"">To Date</label>
                <input type=""date"" class=""form-control form-control-sm""
                       @bind=""Filter.EndDate"" @bind:event=""onchange"" />
            </div>

            @* Event Type Filter *@
            <div class=""col-md-3"">
                <label class=""form-label small text-muted"">Event Type</label>
                <select class=""form-select form-select-sm"" @bind=""_selectedEventType"" @bind:after=""AddEventType"">
                    <option value="""">All Types</option>
                    <option value=""Created"">Created</option>
                    <option value=""Updated"">Updated</option>
                    <option value=""Deleted"">Deleted</option>
                    <option value=""Completed"">Completed</option>
                    <option value=""Assigned"">Assigned</option>
                    <option value=""Commented"">Commented</option>
                    <option value=""StatusChanged"">Status Changed</option>
                </select>
            </div>

            @* Search *@
            <div class=""col-md-3"">
                <label class=""form-label small text-muted"">Search</label>
                <div class=""input-group input-group-sm"">
                    <span class=""input-group-text""><i class=""fa-solid fa-search""></i></span>
                    <input type=""text"" class=""form-control"" placeholder=""Search events...""
                           @bind=""Filter.SearchText"" @bind:event=""oninput"" />
                </div>
            </div>
        </div>

        @* Active Filters Display *@
        @if (Filter.EventTypes.Count > 0) {{
            <div class=""mt-3"">
                <label class=""form-label small text-muted"">Active Event Types:</label>
                <div class=""d-flex flex-wrap gap-1"">
                    @foreach (var eventType in Filter.EventTypes) {{
                        <span class=""badge bg-primary d-flex align-items-center"">
                            @eventType
                            <button class=""btn btn-sm p-0 ms-1 text-white"" @onclick=""() => RemoveEventType(eventType)"">
                                <i class=""fa-solid fa-times"" style=""font-size: 10px;""></i>
                            </button>
                        </span>
                    }}
                </div>
            </div>
        }}

        @* Quick Filters *@
        <div class=""mt-3 pt-3 border-top"">
            <label class=""form-label small text-muted"">Quick Filters:</label>
            <div class=""btn-group btn-group-sm"" role=""group"">
                <button class=""btn btn-outline-secondary @(_quickFilter == ""today"" ? ""active"" : """")""
                        @onclick=""() => ApplyQuickFilter(""today"")"">
                    Today
                </button>
                <button class=""btn btn-outline-secondary @(_quickFilter == ""week"" ? ""active"" : """")""
                        @onclick=""() => ApplyQuickFilter(""week"")"">
                    This Week
                </button>
                <button class=""btn btn-outline-secondary @(_quickFilter == ""month"" ? ""active"" : """")""
                        @onclick=""() => ApplyQuickFilter(""month"")"">
                    This Month
                </button>
                <button class=""btn btn-outline-secondary @(_quickFilter == ""all"" ? ""active"" : """")""
                        @onclick=""() => ApplyQuickFilter(""all"")"">
                    All Time
                </button>
            </div>
        </div>

        @* Actions *@
        <div class=""mt-3 pt-3 border-top d-flex justify-content-between"">
            <button class=""btn btn-sm btn-outline-secondary"" @onclick=""ClearFilters"">
                <i class=""fa-solid fa-eraser me-1""></i>Clear All
            </button>
            <button class=""btn btn-sm btn-primary"" @onclick=""ApplyFilters"">
                <i class=""fa-solid fa-check me-1""></i>Apply Filters
            </button>
        </div>
    </div>
</div>

@code {{
    [Parameter] public TimelineFilter Filter {{ get; set; }} = new();
    [Parameter] public EventCallback<TimelineFilter> OnFilterChanged {{ get; set; }}
    [Parameter] public EventCallback OnClose {{ get; set; }}

    private string _selectedEventType = string.Empty;
    private string _quickFilter = ""all"";

    private void AddEventType()
    {{
        if (!string.IsNullOrEmpty(_selectedEventType) && !Filter.EventTypes.Contains(_selectedEventType))
        {{
            Filter.EventTypes.Add(_selectedEventType);
            _selectedEventType = string.Empty;
            StateHasChanged();
        }}
    }}

    private void RemoveEventType(string eventType)
    {{
        Filter.EventTypes.Remove(eventType);
        StateHasChanged();
    }}

    private void ApplyQuickFilter(string filter)
    {{
        _quickFilter = filter;
        var today = DateTime.Today;

        switch (filter)
        {{
            case ""today"":
                Filter.StartDate = today;
                Filter.EndDate = today;
                break;
            case ""week"":
                Filter.StartDate = today.AddDays(-(int)today.DayOfWeek);
                Filter.EndDate = today;
                break;
            case ""month"":
                Filter.StartDate = new DateTime(today.Year, today.Month, 1);
                Filter.EndDate = today;
                break;
            case ""all"":
                Filter.StartDate = null;
                Filter.EndDate = null;
                break;
        }}
        StateHasChanged();
    }}

    private void ClearFilters()
    {{
        Filter = new TimelineFilter();
        _quickFilter = ""all"";
        _selectedEventType = string.Empty;
        StateHasChanged();
    }}

    private async Task ApplyFilters()
    {{
        await OnFilterChanged.InvokeAsync(Filter);
    }}

    private async Task Close()
    {{
        await OnClose.InvokeAsync();
    }}

    // Reference to parent's TimelineFilter class
    public class TimelineFilter
    {{
        public DateTime? StartDate {{ get; set; }}
        public DateTime? EndDate {{ get; set; }}
        public List<string> EventTypes {{ get; set; }} = new();
        public List<Guid> UserIds {{ get; set; }} = new();
        public string SearchText {{ get; set; }} = string.Empty;

        public bool IsEmpty() =>
            !StartDate.HasValue && !EndDate.HasValue &&
            EventTypes.Count == 0 && UserIds.Count == 0 &&
            string.IsNullOrWhiteSpace(SearchText);

        public int GetActiveCount()
        {{
            int count = 0;
            if (StartDate.HasValue || EndDate.HasValue) count++;
            if (EventTypes.Count > 0) count++;
            if (UserIds.Count > 0) count++;
            if (!string.IsNullOrWhiteSpace(SearchText)) count++;
            return count;
        }}
    }}
}}
";
}

#endregion
