namespace FreeManager.Client;

#region PagePatterns - SplitPanelMasterDetail
// ============================================================================
// PAGE PATTERN: SPLIT PANEL MASTER-DETAIL
// Email-style interface: list on left, detail on right
//
// Generated Files:
// - {Entity}SplitView.App.razor: Main container with resizable split panels
// - {Entity}ListPanel.App.razor: Left panel with scrollable list and selection
// - {Entity}DetailPanel.App.razor: Right panel showing selected item details with tabs
// - {Entity}ListItem.App.razor: Individual list item component with selection highlighting
// ============================================================================

public static partial class PagePatterns
{
    /// <summary>
    /// Generate SplitPanelMasterDetail files for the given entity/project.
    /// </summary>
    public static List<(string FileName, string FileType, string Content)> GetSplitPanelMasterDetailFiles(
        string projectName,
        DataObjects.EntityDefinition? entity = null)
    {
        List<(string, string, string)> files = new();
        string entityName = entity?.Name ?? "Item";
        string entityPlural = entity?.PluralName ?? "Items";

        files.Add(($"{projectName}.App.{entityName}SplitView.razor", "RazorComponent", GetSplitPanelMasterDetail_SplitView(projectName, entityName, entityPlural)));
        files.Add(($"{projectName}.App.{entityName}ListPanel.razor", "RazorComponent", GetSplitPanelMasterDetail_ListPanel(projectName, entityName, entityPlural)));
        files.Add(($"{projectName}.App.{entityName}DetailPanel.razor", "RazorComponent", GetSplitPanelMasterDetail_DetailPanel(projectName, entityName, entityPlural)));
        files.Add(($"{projectName}.App.{entityName}ListItem.razor", "RazorComponent", GetSplitPanelMasterDetail_ListItem(projectName, entityName, entityPlural)));

        return files;
    }

    // ============================================================
    // SPLIT VIEW - Main Container with Resizable Panels
    // ============================================================

    private static string GetSplitPanelMasterDetail_SplitView(string projectName, string entityName, string entityPlural) => $@"@* {entityName}SplitView.App.razor - Split-Panel Master-Detail View *@
@* Generated by Page Pattern: SplitPanelMasterDetail *@
@page ""/{entityPlural}""
@page ""/{{TenantCode}}/{entityPlural}""
@implements IDisposable
@inject BlazorDataModel Model
@inject HttpClient Http
@inject IJSRuntime JS

@if (Model.Loaded && Model.LoggedIn && Model.View == _pageName) {{
    <div class=""split-view-container"" @onkeydown=""HandleKeyDown"" tabindex=""0"" @ref=""_containerRef"">
        <style>
            .split-view-container {{
                display: flex;
                height: calc(100vh - 60px);
                overflow: hidden;
                outline: none;
            }}
            .split-panel-left {{
                width: var(--left-panel-width, 350px);
                min-width: 250px;
                max-width: 600px;
                border-right: 1px solid var(--bs-border-color);
                display: flex;
                flex-direction: column;
                background: var(--bs-body-bg);
            }}
            .split-panel-right {{
                flex: 1;
                overflow: hidden;
                display: flex;
                flex-direction: column;
                background: var(--bs-body-bg);
            }}
            .split-resizer {{
                width: 4px;
                cursor: col-resize;
                background: transparent;
                transition: background 0.2s;
                position: relative;
            }}
            .split-resizer:hover,
            .split-resizer.dragging {{
                background: var(--bs-primary);
            }}
            .split-resizer::after {{
                content: '';
                position: absolute;
                left: -4px;
                right: -4px;
                top: 0;
                bottom: 0;
            }}
        </style>

        <div class=""split-panel-left"" style=""--left-panel-width: @(_leftPanelWidth)px;"">
            <{projectName}_App_{entityName}ListPanel
                Items=""_items""
                SelectedItem=""_selectedItem""
                Loading=""_loading""
                OnItemSelected=""SelectItem""
                OnRefresh=""LoadData""
                OnCreateNew=""CreateNew"" />
        </div>

        <div class=""split-resizer @(_isDragging ? ""dragging"" : """")""
             @onmousedown=""StartResize""
             @onmouseup=""StopResize"">
        </div>

        <div class=""split-panel-right"">
            <{projectName}_App_{entityName}DetailPanel
                Item=""_selectedItem""
                OnSave=""SaveItem""
                OnDelete=""DeleteItem""
                OnClose=""ClearSelection"" />
        </div>
    </div>
}}

@code {{
    private string _pageName = ""{entityPlural.ToLower()}"";
    private bool _loading = true;
    private List<{entityName}> _items = new();
    private {entityName}? _selectedItem;
    private int _selectedIndex = -1;
    private double _leftPanelWidth = 350;
    private bool _isDragging = false;
    private ElementReference _containerRef;

    public void Dispose() {{ Model.OnChange -= StateHasChanged; }}

    protected override void OnInitialized()
    {{
        Model.View = _pageName;
        Model.OnChange += StateHasChanged;
    }}

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {{
        if (firstRender)
        {{
            await LoadData();
            await _containerRef.FocusAsync();
        }}
    }}

    private async Task LoadData()
    {{
        _loading = true;
        StateHasChanged();

        var result = await Helpers.GetOrPost<{entityName}FilterResult>(
            DataObjects.Endpoints.{projectName}.Get{entityPlural}, new {entityName}Filter()) ?? new();
        _items = result.Records ?? new();

        // Maintain selection if possible
        if (_selectedItem != null)
        {{
            _selectedItem = _items.FirstOrDefault(x => x.{entityName}Id == _selectedItem.{entityName}Id);
            _selectedIndex = _selectedItem != null ? _items.IndexOf(_selectedItem) : -1;
        }}

        _loading = false;
        StateHasChanged();
    }}

    private void SelectItem({entityName} item)
    {{
        _selectedItem = item;
        _selectedIndex = _items.IndexOf(item);
        StateHasChanged();
    }}

    private void ClearSelection()
    {{
        _selectedItem = null;
        _selectedIndex = -1;
        StateHasChanged();
    }}

    private void CreateNew()
    {{
        _selectedItem = new {entityName}();
        _selectedIndex = -1;
        StateHasChanged();
    }}

    private async Task SaveItem({entityName} item)
    {{
        await Helpers.GetOrPost<{entityName}>(DataObjects.Endpoints.{projectName}.Save{entityName}, item);
        await LoadData();
    }}

    private async Task DeleteItem({entityName} item)
    {{
        if (await Helpers.Confirm(""Delete this {entityName.ToLower()}?""))
        {{
            await Helpers.GetOrPost<bool>(DataObjects.Endpoints.{projectName}.Delete{entityName}, item.{entityName}Id);
            _selectedItem = null;
            _selectedIndex = -1;
            await LoadData();
        }}
    }}

    // Keyboard navigation
    private void HandleKeyDown(KeyboardEventArgs e)
    {{
        if (_items.Count == 0) return;

        switch (e.Key)
        {{
            case ""ArrowUp"":
                if (_selectedIndex > 0)
                {{
                    _selectedIndex--;
                    _selectedItem = _items[_selectedIndex];
                }}
                break;
            case ""ArrowDown"":
                if (_selectedIndex < _items.Count - 1)
                {{
                    _selectedIndex++;
                    _selectedItem = _items[_selectedIndex];
                }}
                else if (_selectedIndex == -1 && _items.Count > 0)
                {{
                    _selectedIndex = 0;
                    _selectedItem = _items[0];
                }}
                break;
            case ""Escape"":
                ClearSelection();
                break;
            case ""Enter"":
                // Focus detail panel for editing
                break;
        }}
        StateHasChanged();
    }}

    // Panel resizing
    private void StartResize(MouseEventArgs e)
    {{
        _isDragging = true;
    }}

    private void StopResize(MouseEventArgs e)
    {{
        _isDragging = false;
    }}

    [JSInvokable]
    public void UpdatePanelWidth(double width)
    {{
        _leftPanelWidth = Math.Clamp(width, 250, 600);
        StateHasChanged();
    }}
}}
";

    // ============================================================
    // LIST PANEL - Left Panel with Scrollable List
    // ============================================================

    private static string GetSplitPanelMasterDetail_ListPanel(string projectName, string entityName, string entityPlural) => $@"@* {entityName}ListPanel.App.razor - List Panel Component *@
@* Generated by Page Pattern: SplitPanelMasterDetail *@

<div class=""list-panel"">
    <style>
        .list-panel {{
            display: flex;
            flex-direction: column;
            height: 100%;
        }}
        .list-panel-header {{
            padding: 1rem;
            border-bottom: 1px solid var(--bs-border-color);
            background: var(--bs-light);
        }}
        .list-panel-search {{
            position: relative;
        }}
        .list-panel-search i {{
            position: absolute;
            left: 12px;
            top: 50%;
            transform: translateY(-50%);
            color: var(--bs-secondary);
        }}
        .list-panel-search input {{
            padding-left: 36px;
        }}
        .list-panel-content {{
            flex: 1;
            overflow-y: auto;
        }}
        .list-panel-footer {{
            padding: 0.75rem 1rem;
            border-top: 1px solid var(--bs-border-color);
            background: var(--bs-light);
            font-size: 0.875rem;
            color: var(--bs-secondary);
        }}
        .list-empty-state {{
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100%;
            padding: 2rem;
            text-align: center;
            color: var(--bs-secondary);
        }}
        .list-empty-state i {{
            font-size: 3rem;
            margin-bottom: 1rem;
            opacity: 0.5;
        }}
    </style>

    <div class=""list-panel-header"">
        <div class=""d-flex justify-content-between align-items-center mb-2"">
            <h5 class=""mb-0"">{entityPlural}</h5>
            <div class=""btn-group btn-group-sm"">
                <button class=""btn btn-outline-secondary"" @onclick=""OnRefresh"" title=""Refresh"">
                    <i class=""fa-solid fa-refresh""></i>
                </button>
                <button class=""btn btn-primary"" @onclick=""OnCreateNew"" title=""New {entityName}"">
                    <i class=""fa-solid fa-plus""></i>
                </button>
            </div>
        </div>
        <div class=""list-panel-search"">
            <i class=""fa-solid fa-search""></i>
            <input type=""text"" class=""form-control form-control-sm""
                   placeholder=""Search {entityPlural.ToLower()}...""
                   @bind=""_searchText"" @bind:event=""oninput"" @bind:after=""FilterItems"" />
        </div>
    </div>

    <div class=""list-panel-content"">
        @if (Loading) {{
            <div class=""d-flex justify-content-center align-items-center h-100"">
                <div class=""spinner-border text-primary"" role=""status"">
                    <span class=""visually-hidden"">Loading...</span>
                </div>
            </div>
        }} else if (!FilteredItems.Any()) {{
            <div class=""list-empty-state"">
                <i class=""fa-solid fa-inbox""></i>
                <h6>No {entityPlural.ToLower()} found</h6>
                <p class=""mb-0"">@(string.IsNullOrEmpty(_searchText) ? ""Create your first {entityName.ToLower()} to get started"" : ""Try adjusting your search"")</p>
            </div>
        }} else {{
            @foreach (var item in FilteredItems) {{
                <{projectName}_App_{entityName}ListItem
                    Item=""item""
                    IsSelected=""item == SelectedItem""
                    OnClick=""() => OnItemSelected.InvokeAsync(item)"" />
            }}
        }}
    </div>

    <div class=""list-panel-footer"">
        <i class=""fa-solid fa-list me-1""></i>
        @FilteredItems.Count() of @Items.Count {entityPlural.ToLower()}
    </div>
</div>

@code {{
    [Parameter] public List<{entityName}> Items {{ get; set; }} = new();
    [Parameter] public {entityName}? SelectedItem {{ get; set; }}
    [Parameter] public bool Loading {{ get; set; }}
    [Parameter] public EventCallback<{entityName}> OnItemSelected {{ get; set; }}
    [Parameter] public EventCallback OnRefresh {{ get; set; }}
    [Parameter] public EventCallback OnCreateNew {{ get; set; }}

    private string _searchText = string.Empty;

    private IEnumerable<{entityName}> FilteredItems => string.IsNullOrWhiteSpace(_searchText)
        ? Items
        : Items.Where(x => x.Name.Contains(_searchText, StringComparison.OrdinalIgnoreCase));

    private void FilterItems()
    {{
        StateHasChanged();
    }}
}}
";

    // ============================================================
    // DETAIL PANEL - Right Panel with Tabs
    // ============================================================

    private static string GetSplitPanelMasterDetail_DetailPanel(string projectName, string entityName, string entityPlural) => $@"@* {entityName}DetailPanel.App.razor - Detail Panel with Tabs *@
@* Generated by Page Pattern: SplitPanelMasterDetail *@

<div class=""detail-panel"">
    <style>
        .detail-panel {{
            display: flex;
            flex-direction: column;
            height: 100%;
        }}
        .detail-panel-header {{
            padding: 1rem 1.5rem;
            border-bottom: 1px solid var(--bs-border-color);
            background: var(--bs-light);
        }}
        .detail-panel-tabs {{
            border-bottom: 1px solid var(--bs-border-color);
            background: var(--bs-body-bg);
        }}
        .detail-panel-tabs .nav-link {{
            border-radius: 0;
            border: none;
            border-bottom: 2px solid transparent;
            color: var(--bs-secondary);
            padding: 0.75rem 1.25rem;
        }}
        .detail-panel-tabs .nav-link:hover {{
            border-bottom-color: var(--bs-border-color);
            color: var(--bs-body-color);
        }}
        .detail-panel-tabs .nav-link.active {{
            border-bottom-color: var(--bs-primary);
            color: var(--bs-primary);
            background: transparent;
        }}
        .detail-panel-content {{
            flex: 1;
            overflow-y: auto;
            padding: 1.5rem;
        }}
        .detail-empty-state {{
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100%;
            text-align: center;
            color: var(--bs-secondary);
        }}
        .detail-empty-state i {{
            font-size: 4rem;
            margin-bottom: 1.5rem;
            opacity: 0.3;
        }}
        .detail-field {{
            margin-bottom: 1.25rem;
        }}
        .detail-field-label {{
            font-size: 0.75rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            color: var(--bs-secondary);
            margin-bottom: 0.25rem;
        }}
        .detail-field-value {{
            font-size: 1rem;
        }}
    </style>

    @if (Item == null) {{
        <div class=""detail-empty-state"">
            <i class=""fa-solid fa-arrow-left""></i>
            <h5>Select a {entityName.ToLower()}</h5>
            <p class=""text-muted mb-0"">Choose an item from the list to view details</p>
        </div>
    }} else {{
        <div class=""detail-panel-header"">
            <div class=""d-flex justify-content-between align-items-start"">
                <div>
                    <h4 class=""mb-1"">@(string.IsNullOrEmpty(Item.Name) ? ""New {entityName}"" : Item.Name)</h4>
                    <small class=""text-muted"">
                        @if (Item.{entityName}Id == default) {{
                            <span>Unsaved</span>
                        }} else {{
                            <span>ID: @Item.{entityName}Id.ToString()[..8]...</span>
                        }}
                    </small>
                </div>
                <div class=""btn-group"">
                    <button class=""btn btn-outline-secondary btn-sm"" @onclick=""() => OnClose.InvokeAsync()"" title=""Close"">
                        <i class=""fa-solid fa-times""></i>
                    </button>
                    <button class=""btn btn-outline-danger btn-sm"" @onclick=""() => OnDelete.InvokeAsync(Item)""
                            disabled=""@(Item.{entityName}Id == default)"" title=""Delete"">
                        <i class=""fa-solid fa-trash""></i>
                    </button>
                    <button class=""btn btn-primary btn-sm"" @onclick=""Save"" title=""Save"">
                        <i class=""fa-solid fa-save me-1""></i>Save
                    </button>
                </div>
            </div>
        </div>

        <div class=""detail-panel-tabs"">
            <ul class=""nav nav-tabs border-0"">
                <li class=""nav-item"">
                    <button class=""nav-link @(_activeTab == ""details"" ? ""active"" : """")""
                            @onclick=""@(() => _activeTab = ""details"")"">
                        <i class=""fa-solid fa-info-circle me-1""></i>Details
                    </button>
                </li>
                <li class=""nav-item"">
                    <button class=""nav-link @(_activeTab == ""activity"" ? ""active"" : """")""
                            @onclick=""@(() => _activeTab = ""activity"")"">
                        <i class=""fa-solid fa-clock me-1""></i>Activity
                    </button>
                </li>
                <li class=""nav-item"">
                    <button class=""nav-link @(_activeTab == ""related"" ? ""active"" : """")""
                            @onclick=""@(() => _activeTab = ""related"")"">
                        <i class=""fa-solid fa-link me-1""></i>Related
                    </button>
                </li>
            </ul>
        </div>

        <div class=""detail-panel-content"">
            @switch (_activeTab) {{
                case ""details"":
                    <EditForm Model=""_editModel"" OnValidSubmit=""Save"">
                        <DataAnnotationsValidator />

                        <div class=""mb-3"">
                            <label class=""form-label"">Name <span class=""text-danger"">*</span></label>
                            <input type=""text"" class=""form-control"" @bind=""_editModel.Name"" />
                            <ValidationMessage For=""@(() => _editModel.Name)"" />
                        </div>

                        <div class=""mb-3"">
                            <label class=""form-label"">Description</label>
                            <textarea class=""form-control"" rows=""4"" @bind=""_editModel.Description""></textarea>
                        </div>

                        <div class=""mb-3"">
                            <div class=""form-check"">
                                <input type=""checkbox"" class=""form-check-input"" id=""isComplete"" @bind=""_editModel.IsComplete"" />
                                <label class=""form-check-label"" for=""isComplete"">Mark as Complete</label>
                            </div>
                        </div>
                    </EditForm>
                    break;

                case ""activity"":
                    <div class=""timeline"">
                        @if (Item.{entityName}Id != default) {{
                            <div class=""timeline-item"">
                                <div class=""timeline-marker bg-success""></div>
                                <div class=""timeline-content"">
                                    <small class=""text-muted"">@Item.CreatedAt.ToString(""MMM dd, yyyy HH:mm"")</small>
                                    <p class=""mb-0"">Created</p>
                                </div>
                            </div>
                            @if (Item.UpdatedAt != Item.CreatedAt) {{
                                <div class=""timeline-item"">
                                    <div class=""timeline-marker bg-info""></div>
                                    <div class=""timeline-content"">
                                        <small class=""text-muted"">@Item.UpdatedAt.ToString(""MMM dd, yyyy HH:mm"")</small>
                                        <p class=""mb-0"">Last updated</p>
                                    </div>
                                </div>
                            }}
                            @if (Item.IsComplete && Item.CompletedAt.HasValue) {{
                                <div class=""timeline-item"">
                                    <div class=""timeline-marker bg-primary""></div>
                                    <div class=""timeline-content"">
                                        <small class=""text-muted"">@Item.CompletedAt.Value.ToString(""MMM dd, yyyy HH:mm"")</small>
                                        <p class=""mb-0"">Completed</p>
                                    </div>
                                </div>
                            }}
                        }} else {{
                            <p class=""text-muted"">No activity yet - save the item first</p>
                        }}
                    </div>
                    <style>
                        .timeline {{ position: relative; padding-left: 2rem; }}
                        .timeline-item {{ position: relative; padding-bottom: 1.5rem; }}
                        .timeline-item:last-child {{ padding-bottom: 0; }}
                        .timeline-item::before {{
                            content: '';
                            position: absolute;
                            left: -1.5rem;
                            top: 0.5rem;
                            bottom: -0.5rem;
                            width: 2px;
                            background: var(--bs-border-color);
                        }}
                        .timeline-item:last-child::before {{ display: none; }}
                        .timeline-marker {{
                            position: absolute;
                            left: -1.75rem;
                            top: 0.25rem;
                            width: 12px;
                            height: 12px;
                            border-radius: 50%;
                        }}
                    </style>
                    break;

                case ""related"":
                    <div class=""text-center text-muted py-4"">
                        <i class=""fa-solid fa-link fa-2x mb-2 opacity-50""></i>
                        <p>No related items</p>
                    </div>
                    break;
            }}
        </div>
    }}
</div>

@code {{
    [Parameter] public {entityName}? Item {{ get; set; }}
    [Parameter] public EventCallback<{entityName}> OnSave {{ get; set; }}
    [Parameter] public EventCallback<{entityName}> OnDelete {{ get; set; }}
    [Parameter] public EventCallback OnClose {{ get; set; }}

    private string _activeTab = ""details"";
    private {entityName} _editModel = new();

    protected override void OnParametersSet()
    {{
        if (Item != null)
        {{
            // Clone the item for editing
            _editModel = new {entityName}
            {{
                {entityName}Id = Item.{entityName}Id,
                Name = Item.Name,
                Description = Item.Description,
                IsComplete = Item.IsComplete,
                CreatedAt = Item.CreatedAt,
                UpdatedAt = Item.UpdatedAt,
                CompletedAt = Item.CompletedAt
            }};
        }}
        else
        {{
            _editModel = new();
        }}
        _activeTab = ""details"";
    }}

    private async Task Save()
    {{
        await OnSave.InvokeAsync(_editModel);
    }}
}}
";

    // ============================================================
    // LIST ITEM - Individual Item with Selection Highlighting
    // ============================================================

    private static string GetSplitPanelMasterDetail_ListItem(string projectName, string entityName, string entityPlural) => $@"@* {entityName}ListItem.App.razor - List Item Component *@
@* Generated by Page Pattern: SplitPanelMasterDetail *@

<div class=""list-item @(IsSelected ? ""selected"" : """")"" @onclick=""OnClick"">
    <style>
        .list-item {{
            padding: 0.875rem 1rem;
            border-bottom: 1px solid var(--bs-border-color);
            cursor: pointer;
            transition: background-color 0.15s ease;
        }}
        .list-item:hover {{
            background-color: var(--bs-light);
        }}
        .list-item.selected {{
            background-color: rgba(var(--bs-primary-rgb), 0.1);
            border-left: 3px solid var(--bs-primary);
            padding-left: calc(1rem - 3px);
        }}
        .list-item-title {{
            font-weight: 500;
            margin-bottom: 0.25rem;
            display: flex;
            align-items: center;
            gap: 0.5rem;
        }}
        .list-item-meta {{
            font-size: 0.8125rem;
            color: var(--bs-secondary);
            display: flex;
            align-items: center;
            gap: 0.75rem;
        }}
        .list-item-badge {{
            font-size: 0.6875rem;
            padding: 0.125rem 0.5rem;
        }}
    </style>

    <div class=""list-item-title"">
        @if (Item.IsComplete) {{
            <i class=""fa-solid fa-check-circle text-success"" title=""Complete""></i>
        }}
        <span class=""@(Item.IsComplete ? ""text-muted"" : """")"">@Item.Name</span>
    </div>

    <div class=""list-item-meta"">
        @if (!string.IsNullOrEmpty(Item.Description)) {{
            <span class=""text-truncate"" style=""max-width: 200px;"">@Item.Description</span>
        }}
        <span>
            <i class=""fa-regular fa-clock me-1""></i>
            @FormatDate(Item.UpdatedAt)
        </span>
    </div>
</div>

@code {{
    [Parameter] public {entityName} Item {{ get; set; }} = new();
    [Parameter] public bool IsSelected {{ get; set; }}
    [Parameter] public EventCallback OnClick {{ get; set; }}

    private string FormatDate(DateTime date)
    {{
        var diff = DateTime.UtcNow - date;
        if (diff.TotalMinutes < 1) return ""Just now"";
        if (diff.TotalMinutes < 60) return $""{{(int)diff.TotalMinutes}}m ago"";
        if (diff.TotalHours < 24) return $""{{(int)diff.TotalHours}}h ago"";
        if (diff.TotalDays < 7) return $""{{(int)diff.TotalDays}}d ago"";
        return date.ToString(""MMM dd"");
    }}
}}
";
}

#endregion
