namespace FreeManager.Client;

#region PagePatterns - QuickStartWizard
// ============================================================================
// PAGE PATTERN: QUICK START WIZARD
// Multi-step wizard for guided setup or onboarding.
//
// Generated Files:
// - {ProjectName}Wizard.App.razor (main wizard container with navigation)
// - {ProjectName}WizardStep1.App.razor (first step - welcome/intro)
// - {ProjectName}WizardStep2.App.razor (second step - configuration)
// - {ProjectName}WizardStep3.App.razor (third step - preferences)
// - {ProjectName}WizardComplete.App.razor (completion summary)
// ============================================================================

public static partial class PagePatterns
{
    /// <summary>
    /// Generate QuickStartWizard files for the given project.
    /// </summary>
    public static List<(string FileName, string FileType, string Content)> GetQuickStartWizardFiles(
        string projectName,
        DataObjects.EntityDefinition? entity = null)
    {
        List<(string, string, string)> files = new();

        files.Add(($"{projectName}.App.Wizard.razor", "RazorComponent", GetQuickStartWizard_Wizard(projectName, entity)));
        files.Add(($"{projectName}.App.WizardStep1.razor", "RazorComponent", GetQuickStartWizard_Step1(projectName, entity)));
        files.Add(($"{projectName}.App.WizardStep2.razor", "RazorComponent", GetQuickStartWizard_Step2(projectName, entity)));
        files.Add(($"{projectName}.App.WizardStep3.razor", "RazorComponent", GetQuickStartWizard_Step3(projectName, entity)));
        files.Add(($"{projectName}.App.WizardComplete.razor", "RazorComponent", GetQuickStartWizard_Complete(projectName, entity)));

        return files;
    }

    // ============================================================
    // WIZARD CONTAINER - Main wizard with step navigation
    // ============================================================

    private static string GetQuickStartWizard_Wizard(string name, DataObjects.EntityDefinition? entity) => $@"@* {name}Wizard.App.razor - QuickStart Wizard *@
@* Generated by Page Pattern: QuickStartWizard *@
@page ""/{name}Wizard""
@page ""/{{TenantCode}}/{name}Wizard""
@implements IDisposable
@inject BlazorDataModel Model
@inject NavigationManager Nav

@if (Model.Loaded && Model.LoggedIn) {{
    <div class=""container py-4"">
        <div class=""row justify-content-center"">
            <div class=""col-lg-8"">
                <!-- Header -->
                <div class=""text-center mb-4"">
                    <h1 class=""display-6"">
                        <i class=""fa-solid fa-wand-magic-sparkles me-2 text-primary""></i>{name} Setup Wizard
                    </h1>
                    <p class=""text-muted"">Complete these steps to get started</p>
                </div>

                <!-- Progress Stepper -->
                <div class=""card shadow-sm mb-4"">
                    <div class=""card-body py-4"">
                        <div class=""d-flex justify-content-between position-relative"">
                            <!-- Progress Line -->
                            <div class=""position-absolute top-50 start-0 end-0"" style=""height: 2px; z-index: 0;"">
                                <div class=""bg-light w-100 h-100""></div>
                                <div class=""bg-primary h-100 position-absolute top-0 start-0""
                                     style=""width: @((_currentStep - 1) * 33.33)%; transition: width 0.3s ease;""></div>
                            </div>

                            @for (int i = 1; i <= 4; i++) {{
                                var step = i;
                                var isCompleted = step < _currentStep;
                                var isCurrent = step == _currentStep;
                                var stepClass = isCompleted ? ""bg-primary text-white"" :
                                               isCurrent ? ""bg-primary text-white"" :
                                               ""bg-light text-muted"";
                                <div class=""text-center position-relative"" style=""z-index: 1;"">
                                    <div class=""rounded-circle d-inline-flex align-items-center justify-content-center @stepClass""
                                         style=""width: 40px; height: 40px; transition: all 0.3s ease;"">
                                        @if (isCompleted) {{
                                            <i class=""fa-solid fa-check""></i>
                                        }} else {{
                                            <span>@step</span>
                                        }}
                                    </div>
                                    <div class=""small mt-1 @(isCurrent || isCompleted ? ""text-primary fw-semibold"" : ""text-muted"")"">
                                        @GetStepLabel(step)
                                    </div>
                                </div>
                            }}
                        </div>
                    </div>
                </div>

                <!-- Step Content -->
                <div class=""card shadow-sm"">
                    <div class=""card-body p-4"">
                        @switch (_currentStep) {{
                            case 1:
                                <{name}_App_WizardStep1 State=""_wizardState"" OnValidated=""OnStepValidated"" />
                                break;
                            case 2:
                                <{name}_App_WizardStep2 State=""_wizardState"" OnValidated=""OnStepValidated"" />
                                break;
                            case 3:
                                <{name}_App_WizardStep3 State=""_wizardState"" OnValidated=""OnStepValidated"" />
                                break;
                            case 4:
                                <{name}_App_WizardComplete State=""_wizardState"" />
                                break;
                        }}
                    </div>

                    <!-- Navigation Footer -->
                    <div class=""card-footer bg-light"">
                        <div class=""d-flex justify-content-between align-items-center"">
                            <div>
                                @if (_currentStep > 1 && _currentStep < 4) {{
                                    <button class=""btn btn-outline-secondary"" @onclick=""PreviousStep"">
                                        <i class=""fa-solid fa-arrow-left me-1""></i>Back
                                    </button>
                                }}
                            </div>
                            <div class=""d-flex gap-2"">
                                @if (_currentStep < 3) {{
                                    <button class=""btn btn-link text-muted"" @onclick=""SkipStep"">
                                        Skip this step
                                    </button>
                                }}
                                @if (_currentStep < 4) {{
                                    <button class=""btn btn-primary"" @onclick=""NextStep"" disabled=""@(!_stepValid)"">
                                        @if (_currentStep == 3) {{
                                            <span>Complete Setup<i class=""fa-solid fa-check ms-1""></i></span>
                                        }} else {{
                                            <span>Next<i class=""fa-solid fa-arrow-right ms-1""></i></span>
                                        }}
                                    </button>
                                }} else {{
                                    <button class=""btn btn-success"" @onclick=""FinishWizard"">
                                        <i class=""fa-solid fa-rocket me-1""></i>Get Started
                                    </button>
                                }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}}

@code {{
    private int _currentStep = 1;
    private bool _stepValid = false;
    private {name}WizardState _wizardState = new();

    public void Dispose() {{ Model.OnChange -= StateHasChanged; }}

    protected override void OnInitialized()
    {{
        Model.View = ""{name.ToLower()}wizard"";
        Model.OnChange += StateHasChanged;
        LoadState();
    }}

    private string GetStepLabel(int step) => step switch
    {{
        1 => ""Welcome"",
        2 => ""Configure"",
        3 => ""Preferences"",
        4 => ""Complete"",
        _ => """"
    }};

    private void OnStepValidated(bool isValid)
    {{
        _stepValid = isValid;
        StateHasChanged();
    }}

    private void NextStep()
    {{
        if (_stepValid && _currentStep < 4)
        {{
            _currentStep++;
            _stepValid = _currentStep == 4;
            SaveState();
            StateHasChanged();
        }}
    }}

    private void PreviousStep()
    {{
        if (_currentStep > 1)
        {{
            _currentStep--;
            _stepValid = true;
            StateHasChanged();
        }}
    }}

    private void SkipStep()
    {{
        if (_currentStep < 3)
        {{
            _currentStep++;
            _stepValid = false;
            SaveState();
            StateHasChanged();
        }}
    }}

    private void FinishWizard()
    {{
        ClearState();
        Nav.NavigateTo(""/"");
    }}

    private void LoadState()
    {{
        // Load persisted wizard state from local storage or session
        // This enables resuming the wizard if the user navigates away
        var savedState = Model.GetStoredValue(""{name}WizardState"");
        if (!string.IsNullOrEmpty(savedState))
        {{
            try
            {{
                var state = System.Text.Json.JsonSerializer.Deserialize<{name}WizardState>(savedState);
                if (state != null)
                {{
                    _wizardState = state;
                    _currentStep = state.LastCompletedStep + 1;
                    if (_currentStep > 4) _currentStep = 4;
                }}
            }}
            catch {{ /* Ignore deserialization errors */ }}
        }}
    }}

    private void SaveState()
    {{
        _wizardState.LastCompletedStep = _currentStep - 1;
        var json = System.Text.Json.JsonSerializer.Serialize(_wizardState);
        Model.SetStoredValue(""{name}WizardState"", json);
    }}

    private void ClearState()
    {{
        Model.RemoveStoredValue(""{name}WizardState"");
    }}
}}

@* Wizard State Class *@
@code {{
    public class {name}WizardState
    {{
        public int LastCompletedStep {{ get; set; }} = 0;

        // Step 1: Welcome
        public string UserName {{ get; set; }} = string.Empty;
        public string OrganizationName {{ get; set; }} = string.Empty;

        // Step 2: Configuration
        public string TimeZone {{ get; set; }} = ""UTC"";
        public string DateFormat {{ get; set; }} = ""MM/dd/yyyy"";
        public string Language {{ get; set; }} = ""en"";

        // Step 3: Preferences
        public bool EnableNotifications {{ get; set; }} = true;
        public bool EnableEmailAlerts {{ get; set; }} = true;
        public string Theme {{ get; set; }} = ""light"";
    }}
}}
";

    // ============================================================
    // STEP 1 - Welcome / Introduction
    // ============================================================

    private static string GetQuickStartWizard_Step1(string name, DataObjects.EntityDefinition? entity) => $@"@* {name}WizardStep1.App.razor - Wizard Step 1: Welcome *@
@* Generated by Page Pattern: QuickStartWizard *@

<div class=""text-center mb-4"">
    <div class=""display-1 text-primary mb-3"">
        <i class=""fa-solid fa-hand-wave""></i>
    </div>
    <h2>Welcome to {name}!</h2>
    <p class=""text-muted lead"">Let's get you set up. This will only take a few minutes.</p>
</div>

<EditForm Model=""State"" OnValidSubmit=""Validate"">
    <DataAnnotationsValidator />

    <div class=""row g-3"">
        <div class=""col-md-6"">
            <label class=""form-label"">Your Name <span class=""text-danger"">*</span></label>
            <div class=""input-group"">
                <span class=""input-group-text""><i class=""fa-solid fa-user""></i></span>
                <input type=""text"" class=""form-control"" placeholder=""Enter your name""
                       @bind=""State.UserName"" @bind:event=""oninput"" @bind:after=""Validate"" />
            </div>
            <ValidationMessage For=""@(() => State.UserName)"" />
        </div>

        <div class=""col-md-6"">
            <label class=""form-label"">Organization Name</label>
            <div class=""input-group"">
                <span class=""input-group-text""><i class=""fa-solid fa-building""></i></span>
                <input type=""text"" class=""form-control"" placeholder=""Your company or team""
                       @bind=""State.OrganizationName"" @bind:event=""oninput"" />
            </div>
        </div>
    </div>

    <div class=""alert alert-info mt-4 mb-0"">
        <i class=""fa-solid fa-lightbulb me-2""></i>
        <strong>Tip:</strong> You can always update these settings later from your profile page.
    </div>
</EditForm>

@code {{
    [Parameter] public {name}WizardState State {{ get; set; }} = new();
    [Parameter] public EventCallback<bool> OnValidated {{ get; set; }}

    protected override void OnInitialized()
    {{
        Validate();
    }}

    private async Task Validate()
    {{
        bool isValid = !string.IsNullOrWhiteSpace(State.UserName);
        await OnValidated.InvokeAsync(isValid);
    }}
}}
";

    // ============================================================
    // STEP 2 - Configuration Settings
    // ============================================================

    private static string GetQuickStartWizard_Step2(string name, DataObjects.EntityDefinition? entity) => $@"@* {name}WizardStep2.App.razor - Wizard Step 2: Configuration *@
@* Generated by Page Pattern: QuickStartWizard *@

<div class=""mb-4"">
    <h3><i class=""fa-solid fa-gear me-2 text-primary""></i>Configuration</h3>
    <p class=""text-muted"">Set up your regional and localization preferences.</p>
</div>

<div class=""row g-4"">
    <div class=""col-md-6"">
        <div class=""card h-100"">
            <div class=""card-body"">
                <h5 class=""card-title"">
                    <i class=""fa-solid fa-globe me-2 text-muted""></i>Time Zone
                </h5>
                <select class=""form-select"" @bind=""State.TimeZone"" @bind:after=""Validate"">
                    <option value=""UTC"">UTC (Coordinated Universal Time)</option>
                    <option value=""America/New_York"">Eastern Time (ET)</option>
                    <option value=""America/Chicago"">Central Time (CT)</option>
                    <option value=""America/Denver"">Mountain Time (MT)</option>
                    <option value=""America/Los_Angeles"">Pacific Time (PT)</option>
                    <option value=""Europe/London"">London (GMT/BST)</option>
                    <option value=""Europe/Paris"">Paris (CET/CEST)</option>
                    <option value=""Asia/Tokyo"">Tokyo (JST)</option>
                    <option value=""Australia/Sydney"">Sydney (AEST/AEDT)</option>
                </select>
            </div>
        </div>
    </div>

    <div class=""col-md-6"">
        <div class=""card h-100"">
            <div class=""card-body"">
                <h5 class=""card-title"">
                    <i class=""fa-solid fa-calendar me-2 text-muted""></i>Date Format
                </h5>
                <select class=""form-select"" @bind=""State.DateFormat"" @bind:after=""Validate"">
                    <option value=""MM/dd/yyyy"">MM/DD/YYYY (12/31/2024)</option>
                    <option value=""dd/MM/yyyy"">DD/MM/YYYY (31/12/2024)</option>
                    <option value=""yyyy-MM-dd"">YYYY-MM-DD (2024-12-31)</option>
                    <option value=""dd.MM.yyyy"">DD.MM.YYYY (31.12.2024)</option>
                </select>
            </div>
        </div>
    </div>

    <div class=""col-md-6"">
        <div class=""card h-100"">
            <div class=""card-body"">
                <h5 class=""card-title"">
                    <i class=""fa-solid fa-language me-2 text-muted""></i>Language
                </h5>
                <select class=""form-select"" @bind=""State.Language"" @bind:after=""Validate"">
                    <option value=""en"">English</option>
                    <option value=""es"">Español (Spanish)</option>
                    <option value=""fr"">Français (French)</option>
                    <option value=""de"">Deutsch (German)</option>
                    <option value=""pt"">Português (Portuguese)</option>
                    <option value=""ja"">日本語 (Japanese)</option>
                    <option value=""zh"">中文 (Chinese)</option>
                </select>
            </div>
        </div>
    </div>
</div>

@code {{
    [Parameter] public {name}WizardState State {{ get; set; }} = new();
    [Parameter] public EventCallback<bool> OnValidated {{ get; set; }}

    protected override void OnInitialized()
    {{
        Validate();
    }}

    private async Task Validate()
    {{
        // Step 2 is always valid as all fields have defaults
        bool isValid = !string.IsNullOrEmpty(State.TimeZone) &&
                       !string.IsNullOrEmpty(State.DateFormat) &&
                       !string.IsNullOrEmpty(State.Language);
        await OnValidated.InvokeAsync(isValid);
    }}
}}
";

    // ============================================================
    // STEP 3 - Preferences
    // ============================================================

    private static string GetQuickStartWizard_Step3(string name, DataObjects.EntityDefinition? entity) => $@"@* {name}WizardStep3.App.razor - Wizard Step 3: Preferences *@
@* Generated by Page Pattern: QuickStartWizard *@

<div class=""mb-4"">
    <h3><i class=""fa-solid fa-sliders me-2 text-primary""></i>Preferences</h3>
    <p class=""text-muted"">Customize your experience with these optional settings.</p>
</div>

<div class=""row g-4"">
    <!-- Notifications -->
    <div class=""col-12"">
        <div class=""card"">
            <div class=""card-body"">
                <h5 class=""card-title mb-3"">
                    <i class=""fa-solid fa-bell me-2 text-muted""></i>Notifications
                </h5>

                <div class=""d-flex justify-content-between align-items-center py-2 border-bottom"">
                    <div>
                        <strong>In-app Notifications</strong>
                        <p class=""text-muted mb-0 small"">Receive notifications within the application</p>
                    </div>
                    <div class=""form-check form-switch"">
                        <input class=""form-check-input"" type=""checkbox"" role=""switch""
                               @bind=""State.EnableNotifications"" style=""width: 3em; height: 1.5em;"" />
                    </div>
                </div>

                <div class=""d-flex justify-content-between align-items-center py-2"">
                    <div>
                        <strong>Email Alerts</strong>
                        <p class=""text-muted mb-0 small"">Get important updates sent to your email</p>
                    </div>
                    <div class=""form-check form-switch"">
                        <input class=""form-check-input"" type=""checkbox"" role=""switch""
                               @bind=""State.EnableEmailAlerts"" style=""width: 3em; height: 1.5em;"" />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Theme -->
    <div class=""col-12"">
        <div class=""card"">
            <div class=""card-body"">
                <h5 class=""card-title mb-3"">
                    <i class=""fa-solid fa-palette me-2 text-muted""></i>Appearance
                </h5>

                <div class=""row g-3"">
                    <div class=""col-md-4"">
                        <div class=""card @(State.Theme == ""light"" ? ""border-primary"" : """")""
                             style=""cursor: pointer;"" @onclick=""@(() => SetTheme(""light""))"">
                            <div class=""card-body text-center py-4"">
                                <i class=""fa-solid fa-sun fa-2x mb-2 @(State.Theme == ""light"" ? ""text-primary"" : ""text-muted"")""></i>
                                <div class=""@(State.Theme == ""light"" ? ""fw-semibold"" : """")"">Light</div>
                            </div>
                        </div>
                    </div>
                    <div class=""col-md-4"">
                        <div class=""card @(State.Theme == ""dark"" ? ""border-primary"" : """")""
                             style=""cursor: pointer;"" @onclick=""@(() => SetTheme(""dark""))"">
                            <div class=""card-body text-center py-4"">
                                <i class=""fa-solid fa-moon fa-2x mb-2 @(State.Theme == ""dark"" ? ""text-primary"" : ""text-muted"")""></i>
                                <div class=""@(State.Theme == ""dark"" ? ""fw-semibold"" : """")"">Dark</div>
                            </div>
                        </div>
                    </div>
                    <div class=""col-md-4"">
                        <div class=""card @(State.Theme == ""auto"" ? ""border-primary"" : """")""
                             style=""cursor: pointer;"" @onclick=""@(() => SetTheme(""auto""))"">
                            <div class=""card-body text-center py-4"">
                                <i class=""fa-solid fa-circle-half-stroke fa-2x mb-2 @(State.Theme == ""auto"" ? ""text-primary"" : ""text-muted"")""></i>
                                <div class=""@(State.Theme == ""auto"" ? ""fw-semibold"" : """")"">Auto</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@code {{
    [Parameter] public {name}WizardState State {{ get; set; }} = new();
    [Parameter] public EventCallback<bool> OnValidated {{ get; set; }}

    protected override void OnInitialized()
    {{
        Validate();
    }}

    private void SetTheme(string theme)
    {{
        State.Theme = theme;
        StateHasChanged();
    }}

    private async Task Validate()
    {{
        // Step 3 is always valid (all preferences have defaults)
        await OnValidated.InvokeAsync(true);
    }}
}}
";

    // ============================================================
    // COMPLETE - Completion Summary
    // ============================================================

    private static string GetQuickStartWizard_Complete(string name, DataObjects.EntityDefinition? entity) => $@"@* {name}WizardComplete.App.razor - Wizard Complete *@
@* Generated by Page Pattern: QuickStartWizard *@

<div class=""text-center py-4"">
    <div class=""mb-4"">
        <div class=""rounded-circle bg-success d-inline-flex align-items-center justify-content-center""
             style=""width: 80px; height: 80px;"">
            <i class=""fa-solid fa-check fa-3x text-white""></i>
        </div>
    </div>

    <h2 class=""text-success mb-3"">Setup Complete!</h2>
    <p class=""lead text-muted mb-4"">
        Great job, <strong>@State.UserName</strong>! You're all set up and ready to go.
    </p>

    <!-- Summary Card -->
    <div class=""card text-start mx-auto"" style=""max-width: 500px;"">
        <div class=""card-header bg-light"">
            <i class=""fa-solid fa-clipboard-list me-2""></i>Your Settings Summary
        </div>
        <div class=""card-body"">
            <div class=""row g-3"">
                <div class=""col-6"">
                    <small class=""text-muted"">Name</small>
                    <div class=""fw-semibold"">@State.UserName</div>
                </div>
                @if (!string.IsNullOrEmpty(State.OrganizationName)) {{
                    <div class=""col-6"">
                        <small class=""text-muted"">Organization</small>
                        <div class=""fw-semibold"">@State.OrganizationName</div>
                    </div>
                }}
                <div class=""col-6"">
                    <small class=""text-muted"">Time Zone</small>
                    <div class=""fw-semibold"">@State.TimeZone</div>
                </div>
                <div class=""col-6"">
                    <small class=""text-muted"">Date Format</small>
                    <div class=""fw-semibold"">@State.DateFormat</div>
                </div>
                <div class=""col-6"">
                    <small class=""text-muted"">Language</small>
                    <div class=""fw-semibold"">@GetLanguageDisplay(State.Language)</div>
                </div>
                <div class=""col-6"">
                    <small class=""text-muted"">Theme</small>
                    <div class=""fw-semibold text-capitalize"">@State.Theme</div>
                </div>
            </div>

            <hr />

            <div class=""d-flex gap-3"">
                <div class=""d-flex align-items-center"">
                    @if (State.EnableNotifications) {{
                        <i class=""fa-solid fa-check-circle text-success me-1""></i>
                    }} else {{
                        <i class=""fa-solid fa-times-circle text-muted me-1""></i>
                    }}
                    <small>Notifications</small>
                </div>
                <div class=""d-flex align-items-center"">
                    @if (State.EnableEmailAlerts) {{
                        <i class=""fa-solid fa-check-circle text-success me-1""></i>
                    }} else {{
                        <i class=""fa-solid fa-times-circle text-muted me-1""></i>
                    }}
                    <small>Email Alerts</small>
                </div>
            </div>
        </div>
    </div>

    <!-- Next Steps -->
    <div class=""mt-4"">
        <h5 class=""text-muted mb-3"">What's Next?</h5>
        <div class=""row g-3 justify-content-center"">
            <div class=""col-md-4"">
                <div class=""card h-100 border-0 bg-light"">
                    <div class=""card-body text-center"">
                        <i class=""fa-solid fa-book fa-2x text-primary mb-2""></i>
                        <h6>Documentation</h6>
                        <small class=""text-muted"">Learn more about features</small>
                    </div>
                </div>
            </div>
            <div class=""col-md-4"">
                <div class=""card h-100 border-0 bg-light"">
                    <div class=""card-body text-center"">
                        <i class=""fa-solid fa-play-circle fa-2x text-primary mb-2""></i>
                        <h6>Quick Tour</h6>
                        <small class=""text-muted"">Take an interactive tour</small>
                    </div>
                </div>
            </div>
            <div class=""col-md-4"">
                <div class=""card h-100 border-0 bg-light"">
                    <div class=""card-body text-center"">
                        <i class=""fa-solid fa-headset fa-2x text-primary mb-2""></i>
                        <h6>Support</h6>
                        <small class=""text-muted"">Get help when needed</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@code {{
    [Parameter] public {name}WizardState State {{ get; set; }} = new();

    private string GetLanguageDisplay(string code) => code switch
    {{
        ""en"" => ""English"",
        ""es"" => ""Spanish"",
        ""fr"" => ""French"",
        ""de"" => ""German"",
        ""pt"" => ""Portuguese"",
        ""ja"" => ""Japanese"",
        ""zh"" => ""Chinese"",
        _ => code
    }};
}}
";
}

#endregion
