using System.Text;

namespace FreeManager;

#region EntityTemplates - API Key Auth Generation
// ============================================================================
// ENTITY WIZARD - API KEY AUTHENTICATION TEMPLATES
// Generates middleware and DataAccess for API key authentication.
// Part of: EntityTemplates.App (partial)
// ============================================================================

public static partial class EntityTemplates
{
    // ============================================================
    // API KEY MIDDLEWARE GENERATION
    // ============================================================

    /// <summary>
    /// Generates API key authentication middleware.
    /// Validates Bearer token against hashed keys in database.
    /// </summary>
    public static string GenerateApiKeyMiddleware(
        DataObjects.ExternalApiConfig config,
        string projectName)
    {
        var sb = new StringBuilder();

        sb.AppendLine($"using System.Security.Cryptography;");
        sb.AppendLine($"using System.Text;");
        sb.AppendLine($"using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        sb.AppendLine($"namespace {projectName}.Middleware;");
        sb.AppendLine();
        sb.AppendLine($"// ============================================================================");
        sb.AppendLine($"// API KEY AUTHENTICATION MIDDLEWARE");
        sb.AppendLine($"// Validates Bearer token for external API endpoints.");
        sb.AppendLine($"// Generated by FreeManager for template: FreeAudit");
        sb.AppendLine($"// ============================================================================");
        sb.AppendLine();
        sb.AppendLine($"public class ApiKeyMiddleware");
        sb.AppendLine($"{{");
        sb.AppendLine($"    private readonly RequestDelegate _next;");
        sb.AppendLine();
        sb.AppendLine($"    public ApiKeyMiddleware(RequestDelegate next)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        _next = next;");
        sb.AppendLine($"    }}");
        sb.AppendLine();
        sb.AppendLine($"    public async Task InvokeAsync(HttpContext context, IDataAccess da)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        // Only apply to external API paths that need API key auth");
        sb.AppendLine($"        var path = context.Request.Path.Value ?? \"\";");
        sb.AppendLine($"        if (!path.StartsWith(\"/{config.RoutePrefix}/events\", StringComparison.OrdinalIgnoreCase))");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            await _next(context);");
        sb.AppendLine($"            return;");
        sb.AppendLine($"        }}");
        sb.AppendLine();
        sb.AppendLine($"        // Extract API key from Authorization header");
        sb.AppendLine($"        if (!context.Request.Headers.TryGetValue(\"Authorization\", out var authHeader))");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            await WriteUnauthorized(context, \"missing_api_key\", \"Authorization header required\");");
        sb.AppendLine($"            return;");
        sb.AppendLine($"        }}");
        sb.AppendLine();
        sb.AppendLine($"        var headerValue = authHeader.ToString();");
        sb.AppendLine($"        if (!headerValue.StartsWith(\"Bearer \", StringComparison.OrdinalIgnoreCase))");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            await WriteUnauthorized(context, \"invalid_format\", \"Authorization header must use Bearer scheme\");");
        sb.AppendLine($"            return;");
        sb.AppendLine($"        }}");
        sb.AppendLine();
        sb.AppendLine($"        var apiKey = headerValue.Substring(7).Trim();");
        sb.AppendLine($"        if (string.IsNullOrEmpty(apiKey))");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            await WriteUnauthorized(context, \"empty_api_key\", \"API key cannot be empty\");");
        sb.AppendLine($"            return;");
        sb.AppendLine($"        }}");
        sb.AppendLine();
        sb.AppendLine($"        // Validate API key");
        sb.AppendLine($"        var source = await da.ValidateApiKeyAsync(apiKey);");
        sb.AppendLine($"        if (source == null)");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            await WriteUnauthorized(context, \"invalid_api_key\", \"API key is invalid or inactive\");");
        sb.AppendLine($"            return;");
        sb.AppendLine($"        }}");
        sb.AppendLine();
        sb.AppendLine($"        // Store source system in context for controller");
        sb.AppendLine($"        context.Items[\"SourceSystem\"] = source;");
        sb.AppendLine();
        sb.AppendLine($"        await _next(context);");
        sb.AppendLine($"    }}");
        sb.AppendLine();
        sb.AppendLine($"    private static async Task WriteUnauthorized(HttpContext context, string error, string message)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        context.Response.StatusCode = 401;");
        sb.AppendLine($"        context.Response.ContentType = \"application/json\";");
        sb.AppendLine($"        await context.Response.WriteAsJsonAsync(new {{ error, message }});");
        sb.AppendLine($"    }}");
        sb.AppendLine($"}}");
        sb.AppendLine();

        // Extension method for middleware registration
        sb.AppendLine($"// ============================================================================");
        sb.AppendLine($"// MIDDLEWARE EXTENSION");
        sb.AppendLine($"// ============================================================================");
        sb.AppendLine();
        sb.AppendLine($"public static class ApiKeyMiddlewareExtensions");
        sb.AppendLine($"{{");
        sb.AppendLine($"    public static IApplicationBuilder UseApiKeyAuth(this IApplicationBuilder builder)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        return builder.UseMiddleware<ApiKeyMiddleware>();");
        sb.AppendLine($"    }}");
        sb.AppendLine($"}}");

        return sb.ToString();
    }

    // ============================================================
    // API KEY DATA ACCESS GENERATION
    // ============================================================

    /// <summary>
    /// Generates DataAccess methods for API key validation and generation.
    /// </summary>
    public static string GenerateApiKeyDataAccess(
        DataObjects.ExternalApiConfig config,
        DataObjects.EntityDefinition apiKeyEntity,
        string projectName)
    {
        var sb = new StringBuilder();
        var entityName = config.ApiKeyEntity;
        var keyProperty = config.ApiKeyProperty;

        // Add using statements and namespace
        sb.AppendLine($"using Microsoft.EntityFrameworkCore;");
        sb.AppendLine($"using System.Security.Cryptography;");
        sb.AppendLine($"using System.Text;");
        sb.AppendLine();
        sb.AppendLine($"namespace {projectName};");
        sb.AppendLine();
        sb.AppendLine($"// ============================================================================");
        sb.AppendLine($"// API KEY AUTHENTICATION DATA ACCESS");
        sb.AppendLine($"// ============================================================================");
        sb.AppendLine();

        // Generate the IDataAccess partial interface FIRST
        sb.AppendLine($"/// <summary>API Key authentication interface extensions.</summary>");
        sb.AppendLine($"public partial interface IDataAccess");
        sb.AppendLine($"{{");
        sb.AppendLine($"    /// <summary>Validates an API key and returns the associated source system.</summary>");
        sb.AppendLine($"    Task<DataObjects.{entityName}?> ValidateApiKeyAsync(string apiKey);");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Generates a new API key for a source system.</summary>");
        sb.AppendLine($"    Task<string> GenerateApiKeyAsync(Guid {entityName.ToLower()}Id);");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Gets all source systems for the dashboard.</summary>");
        sb.AppendLine($"    Task<List<DataObjects.{entityName}>> Get{entityName}sAsync();");
        sb.AppendLine($"}}");
        sb.AppendLine();

        // Now generate the DataAccess partial class implementation
        sb.AppendLine($"public partial class DataAccess");
        sb.AppendLine($"{{");
        sb.AppendLine($"    #region API Key Authentication");
        sb.AppendLine();

        // ValidateApiKey - use inline mapping instead of calling mapper method
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Validates an API key and returns the associated source system.");
        sb.AppendLine($"    /// Returns null if key is invalid or source is inactive.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public async Task<DataObjects.{entityName}?> ValidateApiKeyAsync(string apiKey)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        if (string.IsNullOrEmpty(apiKey))");
        sb.AppendLine($"            return null;");
        sb.AppendLine();
        sb.AppendLine($"        // Hash the provided key");
        sb.AppendLine($"        var hash = HashApiKey(apiKey);");
        sb.AppendLine();
        sb.AppendLine($"        // Look up by hash");
        sb.AppendLine($"        var record = await data.{entityName}s");
        sb.AppendLine($"            .FirstOrDefaultAsync(x => x.{keyProperty} == hash && x.IsActive);");
        sb.AppendLine();
        sb.AppendLine($"        if (record == null)");
        sb.AppendLine($"            return null;");
        sb.AppendLine();
        sb.AppendLine($"        // Return as DataObject with inline mapping");
        sb.AppendLine($"        return new DataObjects.{entityName}");
        sb.AppendLine($"        {{");
        // Map properties from entity
        foreach (var prop in apiKeyEntity.Properties.Where(p => !p.IsSystemField || p.IsPrimaryKey))
        {
            sb.AppendLine($"            {prop.Name} = record.{prop.Name},");
        }
        sb.AppendLine($"        }};");
        sb.AppendLine($"    }}");
        sb.AppendLine();

        // GenerateApiKey
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Generates a new API key for a source system.");
        sb.AppendLine($"    /// Returns the plaintext key (show to user ONCE, then store only the hash).");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public async Task<string> GenerateApiKeyAsync(Guid {entityName.ToLower()}Id)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        var record = await data.{entityName}s");
        sb.AppendLine($"            .FirstOrDefaultAsync(x => x.{entityName}Id == {entityName.ToLower()}Id);");
        sb.AppendLine();
        sb.AppendLine($"        if (record == null)");
        sb.AppendLine($"            throw new InvalidOperationException(\"{entityName} not found\");");
        sb.AppendLine();
        sb.AppendLine($"        // Generate random 32-byte key and encode as Base64");
        sb.AppendLine($"        var bytes = new byte[32];");
        sb.AppendLine($"        RandomNumberGenerator.Fill(bytes);");
        sb.AppendLine($"        var plaintextKey = Convert.ToBase64String(bytes);");
        sb.AppendLine();
        sb.AppendLine($"        // Store only the hash");
        sb.AppendLine($"        record.{keyProperty} = HashApiKey(plaintextKey);");
        sb.AppendLine($"        await data.SaveChangesAsync();");
        sb.AppendLine();
        sb.AppendLine($"        // Return plaintext key (caller shows to user ONCE)");
        sb.AppendLine($"        return plaintextKey;");
        sb.AppendLine($"    }}");
        sb.AppendLine();

        // GetSourceSystems for dashboard
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Gets all source systems for the dashboard.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public async Task<List<DataObjects.{entityName}>> Get{entityName}sAsync()");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        return await data.{entityName}s");
        sb.AppendLine($"            .Where(x => x.IsActive)");
        sb.AppendLine($"            .OrderBy(x => x.Name)");
        sb.AppendLine($"            .Select(x => new DataObjects.{entityName}");
        sb.AppendLine($"            {{");
        foreach (var prop in apiKeyEntity.Properties.Where(p => !p.IsSystemField || p.IsPrimaryKey))
        {
            sb.AppendLine($"                {prop.Name} = x.{prop.Name},");
        }
        sb.AppendLine($"            }})");
        sb.AppendLine($"            .ToListAsync();");
        sb.AppendLine($"    }}");
        sb.AppendLine();

        // HashApiKey helper
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Hashes an API key using SHA256.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    private static string HashApiKey(string key)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        using var sha256 = SHA256.Create();");
        sb.AppendLine($"        var bytes = Encoding.UTF8.GetBytes(key);");
        sb.AppendLine($"        var hash = sha256.ComputeHash(bytes);");
        sb.AppendLine($"        return Convert.ToBase64String(hash);");
        sb.AppendLine($"    }}");
        sb.AppendLine();
        sb.AppendLine($"    #endregion");
        sb.AppendLine($"}}");

        return sb.ToString();
    }

    // ============================================================
    // PROGRAM.CS SNIPPET GENERATION
    // ============================================================

    /// <summary>
    /// Generates the snippet to add to Program.cs for middleware registration.
    /// </summary>
    public static string GenerateProgramCsSnippet(
        DataObjects.ExternalApiConfig config,
        string projectName)
    {
        var sb = new StringBuilder();

        sb.AppendLine($"// ============================================================================");
        sb.AppendLine($"// ADD TO PROGRAM.CS - Middleware Registration");
        sb.AppendLine($"// ============================================================================");
        sb.AppendLine();
        sb.AppendLine($"// Add this using statement:");
        sb.AppendLine($"// using {projectName}.Middleware;");
        sb.AppendLine();
        sb.AppendLine($"// Add this line BEFORE app.UseAuthentication() and app.UseAuthorization():");
        sb.AppendLine($"// app.UseApiKeyAuth();");
        sb.AppendLine();
        sb.AppendLine($"// Full middleware order:");
        sb.AppendLine($"// app.UseRouting();");
        sb.AppendLine($"// app.UseApiKeyAuth();      // <-- Add this line");
        sb.AppendLine($"// app.UseAuthentication();");
        sb.AppendLine($"// app.UseAuthorization();");
        sb.AppendLine($"// app.MapControllers();");

        return sb.ToString();
    }

    // ============================================================
    // EDIT PAGE SNIPPET FOR API KEY GENERATION UI
    // ============================================================

    /// <summary>
    /// Generates the API key generation section to add to the SourceSystem edit page.
    /// </summary>
    public static string GenerateApiKeyEditSection(
        DataObjects.ExternalApiConfig config,
        string projectName)
    {
        var sb = new StringBuilder();
        var entityName = config.ApiKeyEntity;

        sb.AppendLine($"@* API Key Generation Section - Add to Edit{entityName}.razor *@");
        sb.AppendLine();
        sb.AppendLine($"@if (!_isNew) {{");
        sb.AppendLine($"    <div class=\"card mb-3\">");
        sb.AppendLine($"        <div class=\"card-header\">");
        sb.AppendLine($"            <h6 class=\"mb-0\"><i class=\"fa-solid fa-key me-2\"></i>API Key</h6>");
        sb.AppendLine($"        </div>");
        sb.AppendLine($"        <div class=\"card-body\">");
        sb.AppendLine($"            @if (string.IsNullOrEmpty(_newApiKey)) {{");
        sb.AppendLine($"                <p class=\"text-muted mb-2\">");
        sb.AppendLine($"                    <i class=\"fa-solid fa-circle-info me-1\"></i>");
        sb.AppendLine($"                    API key is stored securely (hashed). Generate a new key if needed.");
        sb.AppendLine($"                </p>");
        sb.AppendLine($"                <button type=\"button\" class=\"btn btn-warning\" @onclick=\"GenerateNewApiKey\">");
        sb.AppendLine($"                    <i class=\"fa-solid fa-rotate me-1\"></i>Generate New API Key");
        sb.AppendLine($"                </button>");
        sb.AppendLine($"                <small class=\"text-danger d-block mt-2\">");
        sb.AppendLine($"                    Warning: This will invalidate the existing key!");
        sb.AppendLine($"                </small>");
        sb.AppendLine($"            }} else {{");
        sb.AppendLine($"                <div class=\"alert alert-success\">");
        sb.AppendLine($"                    <h6 class=\"alert-heading\"><i class=\"fa-solid fa-check-circle me-1\"></i>New API Key Generated</h6>");
        sb.AppendLine($"                    <p class=\"mb-2\">Copy this key now. <strong>It will not be shown again!</strong></p>");
        sb.AppendLine($"                    <div class=\"input-group\">");
        sb.AppendLine($"                        <input type=\"text\" class=\"form-control font-monospace\" value=\"@_newApiKey\" readonly />");
        sb.AppendLine($"                        <button class=\"btn btn-outline-secondary\" type=\"button\" @onclick=\"CopyApiKey\">");
        sb.AppendLine($"                            <i class=\"fa-solid fa-copy\"></i>");
        sb.AppendLine($"                        </button>");
        sb.AppendLine($"                    </div>");
        sb.AppendLine($"                </div>");
        sb.AppendLine($"            }}");
        sb.AppendLine($"        </div>");
        sb.AppendLine($"    </div>");
        sb.AppendLine($"}}");
        sb.AppendLine();
        sb.AppendLine($"@code {{");
        sb.AppendLine($"    private string _newApiKey = \"\";");
        sb.AppendLine();
        sb.AppendLine($"    private async Task GenerateNewApiKey()");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        try");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            var result = await Http.PostAsJsonAsync($\"api/{config.RoutePrefix}/sources/{{_item.{entityName}Id}}/generate-key\", new {{}});");
        sb.AppendLine($"            if (result.IsSuccessStatusCode)");
        sb.AppendLine($"            {{");
        sb.AppendLine($"                var response = await result.Content.ReadFromJsonAsync<GenerateKeyResponse>();");
        sb.AppendLine($"                _newApiKey = response?.ApiKey ?? \"\";");
        sb.AppendLine($"                StateHasChanged();");
        sb.AppendLine($"            }}");
        sb.AppendLine($"            else");
        sb.AppendLine($"            {{");
        sb.AppendLine($"                Model.ErrorMessage(\"Failed to generate API key\");");
        sb.AppendLine($"            }}");
        sb.AppendLine($"        }}");
        sb.AppendLine($"        catch (Exception ex)");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            Model.ErrorMessage($\"Error: {{ex.Message}}\");");
        sb.AppendLine($"        }}");
        sb.AppendLine($"    }}");
        sb.AppendLine();
        sb.AppendLine($"    private async Task CopyApiKey()");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        await JSRuntime.InvokeVoidAsync(\"navigator.clipboard.writeText\", _newApiKey);");
        sb.AppendLine($"        Model.SuccessMessage(\"API key copied to clipboard\");");
        sb.AppendLine($"    }}");
        sb.AppendLine();
        sb.AppendLine($"    private class GenerateKeyResponse");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        public string ApiKey {{ get; set; }} = \"\";");
        sb.AppendLine($"    }}");
        sb.AppendLine($"}}");

        return sb.ToString();
    }
}

#endregion
