namespace FreeManager.Client;

#region PagePatterns - SettingsHub
// ============================================================================
// PAGE PATTERN: SETTINGS HUB
// Multi-section settings page with sidebar navigation
//
// Generated Files:
// - {projectName}SettingsHub.App.razor (main container with layout)
// - {projectName}SettingsSidebar.App.razor (collapsible sidebar with section links)
// - {projectName}ProfileSettings.App.razor (user profile settings section)
// - {projectName}NotificationSettings.App.razor (notification preferences section)
//
// Key Features:
// - Collapsible sidebar
// - Section highlighting
// - Role-based visibility
// - Unsaved warning
// ============================================================================

public static partial class PagePatterns
{
    /// <summary>
    /// Generate SettingsHub files for the given project.
    /// </summary>
    public static List<(string FileName, string FileType, string Content)> GetSettingsHubFiles(
        string projectName,
        DataObjects.EntityDefinition? entity = null)
    {
        List<(string, string, string)> files = new();

        files.Add(($"{projectName}.App.SettingsHub.razor", "RazorComponent", GetSettingsHub_Main(projectName, entity)));
        files.Add(($"{projectName}.App.SettingsSidebar.razor", "RazorComponent", GetSettingsHub_Sidebar(projectName, entity)));
        files.Add(($"{projectName}.App.ProfileSettings.razor", "RazorComponent", GetSettingsHub_ProfileSettings(projectName, entity)));
        files.Add(($"{projectName}.App.NotificationSettings.razor", "RazorComponent", GetSettingsHub_NotificationSettings(projectName, entity)));

        return files;
    }

    // ============================================================
    // SETTINGS HUB - MAIN CONTAINER
    // ============================================================

    private static string GetSettingsHub_Main(string name, DataObjects.EntityDefinition? entity) => $@"@* {name}SettingsHub.App.razor - Settings hub main container *@
@* Generated by SettingsHub Page Pattern *@
@page ""/Settings""
@page ""/{{TenantCode}}/Settings""
@implements IDisposable
@inject BlazorDataModel Model
@inject NavigationManager Navigation
@inject IJSRuntime JS

@if (Model.Loaded && Model.LoggedIn && Model.View == _pageName) {{
    <div class=""container-fluid py-3"">
        <div class=""@Model.StickyMenuClass mb-3"">
            <div class=""d-flex justify-content-between align-items-center"">
                <h1 class=""page-title mb-0"">
                    <i class=""fa-solid fa-sliders me-2""></i>Settings
                </h1>
                @if (_hasUnsavedChanges) {{
                    <span class=""badge bg-warning text-dark"">
                        <i class=""fa-solid fa-exclamation-triangle me-1""></i>Unsaved Changes
                    </span>
                }}
            </div>
        </div>

        <div class=""row"">
            @* Sidebar *@
            <div class=""col-md-3 col-lg-2"">
                <{name}_App_SettingsSidebar
                    ActiveSection=""@_activeSection""
                    OnSectionChange=""HandleSectionChange""
                    IsCollapsed=""@_sidebarCollapsed""
                    OnToggleCollapse=""ToggleSidebar""
                    UserRoles=""@Model.CurrentUser?.Roles"" />
            </div>

            @* Content Area *@
            <div class=""@(_sidebarCollapsed ? ""col-md-11 col-lg-11"" : ""col-md-9 col-lg-10"")"">
                <div class=""card shadow-sm"">
                    <div class=""card-body"">
                        @switch (_activeSection) {{
                            case ""profile"":
                                <{name}_App_ProfileSettings
                                    OnChange=""MarkUnsaved""
                                    OnSave=""HandleSave"" />
                                break;
                            case ""notifications"":
                                <{name}_App_NotificationSettings
                                    OnChange=""MarkUnsaved""
                                    OnSave=""HandleSave"" />
                                break;
                            case ""security"":
                                <div class=""text-center py-5 text-muted"">
                                    <i class=""fa-solid fa-shield-halved fa-4x mb-3 opacity-50""></i>
                                    <h4>Security Settings</h4>
                                    <p>Security configuration options will appear here.</p>
                                </div>
                                break;
                            case ""preferences"":
                                <div class=""text-center py-5 text-muted"">
                                    <i class=""fa-solid fa-palette fa-4x mb-3 opacity-50""></i>
                                    <h4>Preferences</h4>
                                    <p>User preference options will appear here.</p>
                                </div>
                                break;
                            case ""admin"":
                                <div class=""text-center py-5 text-muted"">
                                    <i class=""fa-solid fa-user-shield fa-4x mb-3 opacity-50""></i>
                                    <h4>Admin Settings</h4>
                                    <p>Administrative configuration will appear here.</p>
                                </div>
                                break;
                            default:
                                <div class=""text-center py-5 text-muted"">
                                    <i class=""fa-solid fa-sliders fa-4x mb-3 opacity-50""></i>
                                    <h4>Select a section</h4>
                                    <p>Choose a settings category from the sidebar.</p>
                                </div>
                                break;
                        }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    @* Unsaved Changes Warning Modal *@
    @if (_showUnsavedWarning) {{
        <div class=""modal fade show d-block"" tabindex=""-1"" style=""background: rgba(0,0,0,0.5);"">
            <div class=""modal-dialog"">
                <div class=""modal-content"">
                    <div class=""modal-header bg-warning"">
                        <h5 class=""modal-title"">
                            <i class=""fa-solid fa-exclamation-triangle me-2""></i>Unsaved Changes
                        </h5>
                    </div>
                    <div class=""modal-body"">
                        <p>You have unsaved changes. Do you want to save before leaving?</p>
                    </div>
                    <div class=""modal-footer"">
                        <button type=""button"" class=""btn btn-secondary"" @onclick=""DiscardChanges"">Discard</button>
                        <button type=""button"" class=""btn btn-primary"" @onclick=""SaveAndNavigate"">Save Changes</button>
                        <button type=""button"" class=""btn btn-outline-secondary"" @onclick=""CancelNavigation"">Cancel</button>
                    </div>
                </div>
            </div>
        </div>
    }}
}}

@code {{
    private string _pageName = ""settings"";
    private string _activeSection = ""profile"";
    private bool _sidebarCollapsed = false;
    private bool _hasUnsavedChanges = false;
    private bool _showUnsavedWarning = false;
    private string _pendingSection = """";

    public void Dispose() {{ Model.OnChange -= StateHasChanged; }}

    protected override void OnInitialized()
    {{
        Model.View = _pageName;
        Model.OnChange += StateHasChanged;
    }}

    private async Task HandleSectionChange(string section)
    {{
        if (_hasUnsavedChanges) {{
            _pendingSection = section;
            _showUnsavedWarning = true;
        }} else {{
            _activeSection = section;
        }}
        await Task.CompletedTask;
    }}

    private void ToggleSidebar()
    {{
        _sidebarCollapsed = !_sidebarCollapsed;
    }}

    private void MarkUnsaved()
    {{
        _hasUnsavedChanges = true;
    }}

    private async Task HandleSave()
    {{
        _hasUnsavedChanges = false;
        await Task.CompletedTask;
    }}

    private async Task DiscardChanges()
    {{
        _hasUnsavedChanges = false;
        _showUnsavedWarning = false;
        _activeSection = _pendingSection;
        _pendingSection = """";
        await Task.CompletedTask;
    }}

    private async Task SaveAndNavigate()
    {{
        await HandleSave();
        _showUnsavedWarning = false;
        _activeSection = _pendingSection;
        _pendingSection = """";
    }}

    private void CancelNavigation()
    {{
        _showUnsavedWarning = false;
        _pendingSection = """";
    }}
}}
";

    // ============================================================
    // SETTINGS HUB - SIDEBAR
    // ============================================================

    private static string GetSettingsHub_Sidebar(string name, DataObjects.EntityDefinition? entity) => $@"@* {name}SettingsSidebar.App.razor - Collapsible sidebar *@
@* Generated by SettingsHub Page Pattern *@

<div class=""card shadow-sm @(IsCollapsed ? ""settings-sidebar-collapsed"" : """")"">
    <div class=""card-header d-flex justify-content-between align-items-center py-2"">
        @if (!IsCollapsed) {{
            <span class=""fw-bold""><i class=""fa-solid fa-cog me-2""></i>Settings</span>
        }}
        <button class=""btn btn-sm btn-link text-secondary p-0"" @onclick=""ToggleCollapse"" title=""@(IsCollapsed ? ""Expand"" : ""Collapse"")"">
            <i class=""fa-solid @(IsCollapsed ? ""fa-chevron-right"" : ""fa-chevron-left"")""></i>
        </button>
    </div>
    <div class=""list-group list-group-flush"">
        @* User Settings Section *@
        @if (!IsCollapsed) {{
            <div class=""list-group-item bg-light text-muted small fw-bold py-2"">
                <i class=""fa-solid fa-user me-2""></i>User Settings
            </div>
        }}

        <button type=""button""
                class=""list-group-item list-group-item-action @(ActiveSection == ""profile"" ? ""active"" : """")""
                @onclick=""@(() => SelectSection(""profile""))"">
            <i class=""fa-solid fa-id-card @(IsCollapsed ? """" : ""me-2"")""></i>
            @if (!IsCollapsed) {{ <span>Profile</span> }}
        </button>

        <button type=""button""
                class=""list-group-item list-group-item-action @(ActiveSection == ""notifications"" ? ""active"" : """")""
                @onclick=""@(() => SelectSection(""notifications""))"">
            <i class=""fa-solid fa-bell @(IsCollapsed ? """" : ""me-2"")""></i>
            @if (!IsCollapsed) {{ <span>Notifications</span> }}
        </button>

        <button type=""button""
                class=""list-group-item list-group-item-action @(ActiveSection == ""security"" ? ""active"" : """")""
                @onclick=""@(() => SelectSection(""security""))"">
            <i class=""fa-solid fa-shield-halved @(IsCollapsed ? """" : ""me-2"")""></i>
            @if (!IsCollapsed) {{ <span>Security</span> }}
        </button>

        <button type=""button""
                class=""list-group-item list-group-item-action @(ActiveSection == ""preferences"" ? ""active"" : """")""
                @onclick=""@(() => SelectSection(""preferences""))"">
            <i class=""fa-solid fa-palette @(IsCollapsed ? """" : ""me-2"")""></i>
            @if (!IsCollapsed) {{ <span>Preferences</span> }}
        </button>

        @* Admin Settings Section - Role-based visibility *@
        @if (HasAdminRole) {{
            @if (!IsCollapsed) {{
                <div class=""list-group-item bg-light text-muted small fw-bold py-2 mt-2"">
                    <i class=""fa-solid fa-user-shield me-2""></i>Administration
                </div>
            }}

            <button type=""button""
                    class=""list-group-item list-group-item-action @(ActiveSection == ""admin"" ? ""active"" : """")""
                    @onclick=""@(() => SelectSection(""admin""))"">
                <i class=""fa-solid fa-cogs @(IsCollapsed ? """" : ""me-2"")""></i>
                @if (!IsCollapsed) {{ <span>Admin Settings</span> }}
            </button>
        }}
    </div>
</div>

<style>
    .settings-sidebar-collapsed {{
        max-width: 60px;
    }}
    .settings-sidebar-collapsed .list-group-item {{
        text-align: center;
        padding-left: 0.5rem;
        padding-right: 0.5rem;
    }}
</style>

@code {{
    [Parameter] public string ActiveSection {{ get; set; }} = ""profile"";
    [Parameter] public EventCallback<string> OnSectionChange {{ get; set; }}
    [Parameter] public bool IsCollapsed {{ get; set; }} = false;
    [Parameter] public EventCallback OnToggleCollapse {{ get; set; }}
    [Parameter] public List<string>? UserRoles {{ get; set; }}

    private bool HasAdminRole => UserRoles?.Any(r =>
        r.Equals(""Admin"", StringComparison.OrdinalIgnoreCase) ||
        r.Equals(""Administrator"", StringComparison.OrdinalIgnoreCase) ||
        r.Equals(""SuperAdmin"", StringComparison.OrdinalIgnoreCase)) ?? false;

    private async Task SelectSection(string section)
    {{
        await OnSectionChange.InvokeAsync(section);
    }}

    private async Task ToggleCollapse()
    {{
        await OnToggleCollapse.InvokeAsync();
    }}
}}
";

    // ============================================================
    // SETTINGS HUB - PROFILE SETTINGS
    // ============================================================

    private static string GetSettingsHub_ProfileSettings(string name, DataObjects.EntityDefinition? entity) => $@"@* {name}ProfileSettings.App.razor - User profile settings *@
@* Generated by SettingsHub Page Pattern *@
@inject BlazorDataModel Model

<div class=""settings-section"">
    <div class=""d-flex justify-content-between align-items-center mb-4"">
        <div>
            <h4 class=""mb-1""><i class=""fa-solid fa-id-card me-2""></i>Profile Settings</h4>
            <p class=""text-muted mb-0"">Manage your personal information and profile details.</p>
        </div>
    </div>

    <EditForm Model=""_profile"" OnValidSubmit=""SaveProfile"">
        <DataAnnotationsValidator />

        <div class=""row"">
            <div class=""col-md-6 mb-3"">
                <label class=""form-label"">First Name <span class=""text-danger"">*</span></label>
                <InputText class=""form-control"" @bind-Value=""_profile.FirstName"" @oninput=""NotifyChange"" />
                <ValidationMessage For=""@(() => _profile.FirstName)"" />
            </div>
            <div class=""col-md-6 mb-3"">
                <label class=""form-label"">Last Name <span class=""text-danger"">*</span></label>
                <InputText class=""form-control"" @bind-Value=""_profile.LastName"" @oninput=""NotifyChange"" />
                <ValidationMessage For=""@(() => _profile.LastName)"" />
            </div>
        </div>

        <div class=""mb-3"">
            <label class=""form-label"">Email Address <span class=""text-danger"">*</span></label>
            <InputText type=""email"" class=""form-control"" @bind-Value=""_profile.Email"" @oninput=""NotifyChange"" />
            <ValidationMessage For=""@(() => _profile.Email)"" />
        </div>

        <div class=""mb-3"">
            <label class=""form-label"">Phone Number</label>
            <InputText class=""form-control"" @bind-Value=""_profile.Phone"" @oninput=""NotifyChange"" placeholder=""(optional)"" />
        </div>

        <div class=""mb-3"">
            <label class=""form-label"">Job Title</label>
            <InputText class=""form-control"" @bind-Value=""_profile.JobTitle"" @oninput=""NotifyChange"" placeholder=""(optional)"" />
        </div>

        <div class=""mb-3"">
            <label class=""form-label"">Bio</label>
            <InputTextArea class=""form-control"" rows=""3"" @bind-Value=""_profile.Bio"" @oninput=""NotifyChange"" placeholder=""Tell us about yourself..."" />
        </div>

        <div class=""mb-3"">
            <label class=""form-label"">Timezone</label>
            <InputSelect class=""form-select"" @bind-Value=""_profile.Timezone"" @onchange=""NotifyChange"">
                <option value=""UTC"">UTC</option>
                <option value=""America/New_York"">Eastern Time (US & Canada)</option>
                <option value=""America/Chicago"">Central Time (US & Canada)</option>
                <option value=""America/Denver"">Mountain Time (US & Canada)</option>
                <option value=""America/Los_Angeles"">Pacific Time (US & Canada)</option>
                <option value=""Europe/London"">London</option>
                <option value=""Europe/Paris"">Paris</option>
                <option value=""Asia/Tokyo"">Tokyo</option>
                <option value=""Australia/Sydney"">Sydney</option>
            </InputSelect>
        </div>

        <hr class=""my-4"" />

        <div class=""d-flex justify-content-end gap-2"">
            <button type=""button"" class=""btn btn-secondary"" @onclick=""ResetProfile"">
                <i class=""fa-solid fa-undo me-1""></i>Reset
            </button>
            <button type=""submit"" class=""btn btn-primary"">
                <i class=""fa-solid fa-save me-1""></i>Save Profile
            </button>
        </div>
    </EditForm>
</div>

@if (_showSuccess) {{
    <div class=""toast-container position-fixed bottom-0 end-0 p-3"">
        <div class=""toast show"" role=""alert"">
            <div class=""toast-header bg-success text-white"">
                <i class=""fa-solid fa-check-circle me-2""></i>
                <strong class=""me-auto"">Success</strong>
                <button type=""button"" class=""btn-close btn-close-white"" @onclick=""@(() => _showSuccess = false)""></button>
            </div>
            <div class=""toast-body"">
                Profile settings saved successfully.
            </div>
        </div>
    </div>
}}

@code {{
    [Parameter] public EventCallback OnChange {{ get; set; }}
    [Parameter] public EventCallback OnSave {{ get; set; }}

    private ProfileModel _profile = new();
    private ProfileModel _originalProfile = new();
    private bool _showSuccess = false;

    protected override void OnInitialized()
    {{
        if (Model.CurrentUser != null) {{
            _profile = new ProfileModel
            {{
                FirstName = Model.CurrentUser.FirstName ?? """",
                LastName = Model.CurrentUser.LastName ?? """",
                Email = Model.CurrentUser.Email ?? """",
                Phone = """",
                JobTitle = """",
                Bio = """",
                Timezone = ""UTC""
            }};
            _originalProfile = CloneProfile(_profile);
        }}
    }}

    private async Task NotifyChange()
    {{
        await OnChange.InvokeAsync();
    }}

    private async Task SaveProfile()
    {{
        _originalProfile = CloneProfile(_profile);
        _showSuccess = true;
        await OnSave.InvokeAsync();
        await Task.Delay(3000);
        _showSuccess = false;
        StateHasChanged();
    }}

    private void ResetProfile()
    {{
        _profile = CloneProfile(_originalProfile);
    }}

    private ProfileModel CloneProfile(ProfileModel source) => new()
    {{
        FirstName = source.FirstName,
        LastName = source.LastName,
        Email = source.Email,
        Phone = source.Phone,
        JobTitle = source.JobTitle,
        Bio = source.Bio,
        Timezone = source.Timezone
    }};

    private class ProfileModel
    {{
        public string FirstName {{ get; set; }} = """";
        public string LastName {{ get; set; }} = """";
        public string Email {{ get; set; }} = """";
        public string Phone {{ get; set; }} = """";
        public string JobTitle {{ get; set; }} = """";
        public string Bio {{ get; set; }} = """";
        public string Timezone {{ get; set; }} = ""UTC"";
    }}
}}
";

    // ============================================================
    // SETTINGS HUB - NOTIFICATION SETTINGS
    // ============================================================

    private static string GetSettingsHub_NotificationSettings(string name, DataObjects.EntityDefinition? entity) => $@"@* {name}NotificationSettings.App.razor - Notification preferences *@
@* Generated by SettingsHub Page Pattern *@

<div class=""settings-section"">
    <div class=""d-flex justify-content-between align-items-center mb-4"">
        <div>
            <h4 class=""mb-1""><i class=""fa-solid fa-bell me-2""></i>Notification Settings</h4>
            <p class=""text-muted mb-0"">Configure how and when you receive notifications.</p>
        </div>
    </div>

    <div class=""card mb-4"">
        <div class=""card-header"">
            <h6 class=""mb-0""><i class=""fa-solid fa-envelope me-2""></i>Email Notifications</h6>
        </div>
        <div class=""card-body"">
            <div class=""form-check form-switch mb-3"">
                <input class=""form-check-input"" type=""checkbox"" id=""emailUpdates"" @bind=""_settings.EmailUpdates"" @bind:after=""NotifyChange"" />
                <label class=""form-check-label"" for=""emailUpdates"">
                    <strong>Product Updates</strong>
                    <br /><small class=""text-muted"">Receive emails about new features and improvements</small>
                </label>
            </div>

            <div class=""form-check form-switch mb-3"">
                <input class=""form-check-input"" type=""checkbox"" id=""emailActivity"" @bind=""_settings.EmailActivity"" @bind:after=""NotifyChange"" />
                <label class=""form-check-label"" for=""emailActivity"">
                    <strong>Activity Alerts</strong>
                    <br /><small class=""text-muted"">Get notified about important activity in your account</small>
                </label>
            </div>

            <div class=""form-check form-switch mb-3"">
                <input class=""form-check-input"" type=""checkbox"" id=""emailDigest"" @bind=""_settings.EmailDigest"" @bind:after=""NotifyChange"" />
                <label class=""form-check-label"" for=""emailDigest"">
                    <strong>Weekly Digest</strong>
                    <br /><small class=""text-muted"">Receive a weekly summary of activity</small>
                </label>
            </div>

            <div class=""form-check form-switch"">
                <input class=""form-check-input"" type=""checkbox"" id=""emailMarketing"" @bind=""_settings.EmailMarketing"" @bind:after=""NotifyChange"" />
                <label class=""form-check-label"" for=""emailMarketing"">
                    <strong>Marketing Emails</strong>
                    <br /><small class=""text-muted"">Receive promotional emails and offers</small>
                </label>
            </div>
        </div>
    </div>

    <div class=""card mb-4"">
        <div class=""card-header"">
            <h6 class=""mb-0""><i class=""fa-solid fa-mobile-screen me-2""></i>Push Notifications</h6>
        </div>
        <div class=""card-body"">
            <div class=""form-check form-switch mb-3"">
                <input class=""form-check-input"" type=""checkbox"" id=""pushEnabled"" @bind=""_settings.PushEnabled"" @bind:after=""NotifyChange"" />
                <label class=""form-check-label"" for=""pushEnabled"">
                    <strong>Enable Push Notifications</strong>
                    <br /><small class=""text-muted"">Receive notifications in your browser</small>
                </label>
            </div>

            @if (_settings.PushEnabled) {{
                <div class=""ms-4"">
                    <div class=""form-check form-switch mb-2"">
                        <input class=""form-check-input"" type=""checkbox"" id=""pushMentions"" @bind=""_settings.PushMentions"" @bind:after=""NotifyChange"" />
                        <label class=""form-check-label"" for=""pushMentions"">Mentions and replies</label>
                    </div>
                    <div class=""form-check form-switch mb-2"">
                        <input class=""form-check-input"" type=""checkbox"" id=""pushAssignments"" @bind=""_settings.PushAssignments"" @bind:after=""NotifyChange"" />
                        <label class=""form-check-label"" for=""pushAssignments"">Task assignments</label>
                    </div>
                    <div class=""form-check form-switch"">
                        <input class=""form-check-input"" type=""checkbox"" id=""pushDeadlines"" @bind=""_settings.PushDeadlines"" @bind:after=""NotifyChange"" />
                        <label class=""form-check-label"" for=""pushDeadlines"">Upcoming deadlines</label>
                    </div>
                </div>
            }}
        </div>
    </div>

    <div class=""card mb-4"">
        <div class=""card-header"">
            <h6 class=""mb-0""><i class=""fa-solid fa-clock me-2""></i>Quiet Hours</h6>
        </div>
        <div class=""card-body"">
            <div class=""form-check form-switch mb-3"">
                <input class=""form-check-input"" type=""checkbox"" id=""quietHours"" @bind=""_settings.QuietHoursEnabled"" @bind:after=""NotifyChange"" />
                <label class=""form-check-label"" for=""quietHours"">
                    <strong>Enable Quiet Hours</strong>
                    <br /><small class=""text-muted"">Pause notifications during specified hours</small>
                </label>
            </div>

            @if (_settings.QuietHoursEnabled) {{
                <div class=""row ms-4"">
                    <div class=""col-md-4"">
                        <label class=""form-label small"">Start Time</label>
                        <input type=""time"" class=""form-control form-control-sm"" @bind=""_settings.QuietStart"" @bind:after=""NotifyChange"" />
                    </div>
                    <div class=""col-md-4"">
                        <label class=""form-label small"">End Time</label>
                        <input type=""time"" class=""form-control form-control-sm"" @bind=""_settings.QuietEnd"" @bind:after=""NotifyChange"" />
                    </div>
                </div>
            }}
        </div>
    </div>

    <hr class=""my-4"" />

    <div class=""d-flex justify-content-end gap-2"">
        <button type=""button"" class=""btn btn-secondary"" @onclick=""ResetSettings"">
            <i class=""fa-solid fa-undo me-1""></i>Reset
        </button>
        <button type=""button"" class=""btn btn-primary"" @onclick=""SaveSettings"">
            <i class=""fa-solid fa-save me-1""></i>Save Settings
        </button>
    </div>
</div>

@if (_showSuccess) {{
    <div class=""toast-container position-fixed bottom-0 end-0 p-3"">
        <div class=""toast show"" role=""alert"">
            <div class=""toast-header bg-success text-white"">
                <i class=""fa-solid fa-check-circle me-2""></i>
                <strong class=""me-auto"">Success</strong>
                <button type=""button"" class=""btn-close btn-close-white"" @onclick=""@(() => _showSuccess = false)""></button>
            </div>
            <div class=""toast-body"">
                Notification settings saved successfully.
            </div>
        </div>
    </div>
}}

@code {{
    [Parameter] public EventCallback OnChange {{ get; set; }}
    [Parameter] public EventCallback OnSave {{ get; set; }}

    private NotificationModel _settings = new();
    private NotificationModel _originalSettings = new();
    private bool _showSuccess = false;

    protected override void OnInitialized()
    {{
        _settings = new NotificationModel();
        _originalSettings = CloneSettings(_settings);
    }}

    private async Task NotifyChange()
    {{
        await OnChange.InvokeAsync();
    }}

    private async Task SaveSettings()
    {{
        _originalSettings = CloneSettings(_settings);
        _showSuccess = true;
        await OnSave.InvokeAsync();
        await Task.Delay(3000);
        _showSuccess = false;
        StateHasChanged();
    }}

    private void ResetSettings()
    {{
        _settings = CloneSettings(_originalSettings);
    }}

    private NotificationModel CloneSettings(NotificationModel source) => new()
    {{
        EmailUpdates = source.EmailUpdates,
        EmailActivity = source.EmailActivity,
        EmailDigest = source.EmailDigest,
        EmailMarketing = source.EmailMarketing,
        PushEnabled = source.PushEnabled,
        PushMentions = source.PushMentions,
        PushAssignments = source.PushAssignments,
        PushDeadlines = source.PushDeadlines,
        QuietHoursEnabled = source.QuietHoursEnabled,
        QuietStart = source.QuietStart,
        QuietEnd = source.QuietEnd
    }};

    private class NotificationModel
    {{
        public bool EmailUpdates {{ get; set; }} = true;
        public bool EmailActivity {{ get; set; }} = true;
        public bool EmailDigest {{ get; set; }} = false;
        public bool EmailMarketing {{ get; set; }} = false;
        public bool PushEnabled {{ get; set; }} = true;
        public bool PushMentions {{ get; set; }} = true;
        public bool PushAssignments {{ get; set; }} = true;
        public bool PushDeadlines {{ get; set; }} = true;
        public bool QuietHoursEnabled {{ get; set; }} = false;
        public string QuietStart {{ get; set; }} = ""22:00"";
        public string QuietEnd {{ get; set; }} = ""08:00"";
    }}
}}
";
}

#endregion
