using System.Text;

namespace FreeManager;

#region EntityTemplates - External API Generation
// ============================================================================
// ENTITY WIZARD - EXTERNAL API TEMPLATES
// Generates external API controller, middleware, and DataAccess for FreeAudit-style apps.
// Part of: EntityTemplates.App (partial)
// ============================================================================

public static partial class EntityTemplates
{
    // ============================================================
    // EXTERNAL API CONTROLLER GENERATION
    // ============================================================

    /// <summary>
    /// Generates an external API controller for receiving events from source systems.
    /// Used by FreeAudit template for GLBA compliance.
    /// </summary>
    public static string GenerateExternalApiController(
        DataObjects.ExternalApiConfig config,
        DataObjects.EntityDefinition eventEntity,
        DataObjects.EntityDefinition? apiKeyEntity,
        string projectName)
    {
        var sb = new StringBuilder();
        var entityName = config.EntityName;
        var controllerName = config.ControllerName;
        var routePrefix = config.RoutePrefix;

        // File header
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using Microsoft.AspNetCore.Authorization;");
        sb.AppendLine();
        sb.AppendLine($"namespace {projectName}.Controllers;");
        sb.AppendLine();
        sb.AppendLine($"// ============================================================================");
        sb.AppendLine($"// {controllerName.ToUpper()} EXTERNAL API CONTROLLER");
        sb.AppendLine($"// Receives events from external source systems via API key authentication.");
        sb.AppendLine($"// Generated by FreeManager for template: FreeAudit");
        sb.AppendLine($"// ============================================================================");
        sb.AppendLine();

        sb.AppendLine($"[ApiController]");
        sb.AppendLine($"[Route(\"{routePrefix}\")]");
        sb.AppendLine($"public class {controllerName}Controller : ControllerBase");
        sb.AppendLine($"{{");
        sb.AppendLine($"    private readonly IDataAccess _da;");
        sb.AppendLine();
        sb.AppendLine($"    public {controllerName}Controller(IDataAccess da)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        _da = da;");
        sb.AppendLine($"    }}");
        sb.AppendLine();

        // POST /events - Single event (API key auth via middleware)
        sb.AppendLine($"    // ============================================================");
        sb.AppendLine($"    // EXTERNAL ENDPOINTS (API Key Auth via middleware)");
        sb.AppendLine($"    // ============================================================");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Receive a single event from an external source system.");
        sb.AppendLine($"    /// Requires API key in Authorization header: Bearer {{api-key}}");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    [HttpPost(\"events\")]");
        sb.AppendLine($"    public async Task<ActionResult<DataObjects.{controllerName}EventResponse>> PostEvent(");
        sb.AppendLine($"        [FromBody] DataObjects.{controllerName}EventRequest request)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        // Get source system from middleware (set by ApiKeyMiddleware)");
        sb.AppendLine($"        var source = HttpContext.Items[\"SourceSystem\"] as DataObjects.{config.ApiKeyEntity};");
        sb.AppendLine($"        if (source == null)");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            return Unauthorized(new {{ error = \"invalid_api_key\", message = \"API key is invalid or inactive\" }});");
        sb.AppendLine($"        }}");
        sb.AppendLine();
        sb.AppendLine($"        var result = await _da.Process{controllerName}EventAsync(request, source.{config.ApiKeyEntity}Id);");
        sb.AppendLine();
        sb.AppendLine($"        return result.Status switch");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            \"accepted\" => Created($\"/{routePrefix}/events/{{result.EventId}}\", result),");
        sb.AppendLine($"            \"duplicate\" => Conflict(result),");
        sb.AppendLine($"            _ => BadRequest(result)");
        sb.AppendLine($"        }};");
        sb.AppendLine($"    }}");
        sb.AppendLine();

        // POST /events/batch - Batch events
        if (config.AllowBatch)
        {
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Receive a batch of events from an external source system.");
            sb.AppendLine($"    /// Maximum {config.BatchLimit} events per request.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    [HttpPost(\"events/batch\")]");
            sb.AppendLine($"    public async Task<ActionResult<DataObjects.{controllerName}BatchResponse>> PostBatch(");
            sb.AppendLine($"        [FromBody] List<DataObjects.{controllerName}EventRequest> events)");
            sb.AppendLine($"    {{");
            sb.AppendLine($"        var source = HttpContext.Items[\"SourceSystem\"] as DataObjects.{config.ApiKeyEntity};");
            sb.AppendLine($"        if (source == null)");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            return Unauthorized(new {{ error = \"invalid_api_key\", message = \"API key is invalid or inactive\" }});");
            sb.AppendLine($"        }}");
            sb.AppendLine();
            sb.AppendLine($"        if (events.Count > {config.BatchLimit})");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            return BadRequest(new {{ error = \"batch_too_large\", message = \"Maximum {config.BatchLimit} events per batch\" }});");
            sb.AppendLine($"        }}");
            sb.AppendLine();
            sb.AppendLine($"        var result = await _da.Process{controllerName}BatchAsync(events, source.{config.ApiKeyEntity}Id);");
            sb.AppendLine($"        return Ok(result);");
            sb.AppendLine($"    }}");
            sb.AppendLine();
        }

        // Internal endpoints (user auth)
        sb.AppendLine($"    // ============================================================");
        sb.AppendLine($"    // INTERNAL ENDPOINTS (User Auth)");
        sb.AppendLine($"    // ============================================================");
        sb.AppendLine();

        // GET /stats/summary
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Get summary statistics for the dashboard.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    [HttpGet(\"stats/summary\")]");
        sb.AppendLine($"    [Authorize]");
        sb.AppendLine($"    public async Task<ActionResult<DataObjects.{controllerName}Stats>> GetStats()");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        var stats = await _da.Get{controllerName}StatsAsync();");
        sb.AppendLine($"        return Ok(stats);");
        sb.AppendLine($"    }}");
        sb.AppendLine();

        // GET /events/recent
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Get recent events for the dashboard feed.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    [HttpGet(\"events/recent\")]");
        sb.AppendLine($"    [Authorize]");
        sb.AppendLine($"    public async Task<ActionResult<List<DataObjects.{entityName}>>> GetRecentEvents(");
        sb.AppendLine($"        [FromQuery] int limit = 50)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        var events = await _da.GetRecent{entityName}sAsync(Math.Min(limit, 100));");
        sb.AppendLine($"        return Ok(events);");
        sb.AppendLine($"    }}");
        sb.AppendLine();

        // GET /sources/status
        if (apiKeyEntity != null)
        {
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Get source system status for the dashboard.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    [HttpGet(\"sources/status\")]");
            sb.AppendLine($"    [Authorize]");
            sb.AppendLine($"    public async Task<ActionResult<List<DataObjects.{config.ApiKeyEntity}>>> GetSourceStatus()");
            sb.AppendLine($"    {{");
            sb.AppendLine($"        var sources = await _da.Get{config.ApiKeyEntity}sAsync();");
            sb.AppendLine($"        return Ok(sources);");
            sb.AppendLine($"    }}");
        }

        sb.AppendLine($"}}");

        // DTOs are now generated in a separate file (GenerateExternalApiDataObjects)
        // NOT appended to the controller

        return sb.ToString();
    }

    // ============================================================
    // EXTERNAL API DATAOBJECTS (Separate File)
    // ============================================================

    /// <summary>
    /// Generates a separate DataObjects file for External API DTOs.
    /// This should be called from GenerateAllFiles to create a separate file.
    /// </summary>
    public static string GenerateExternalApiDataObjects(
        DataObjects.ExternalApiConfig config,
        DataObjects.EntityDefinition eventEntity,
        string projectName)
    {
        var sb = new StringBuilder();
        var controllerName = config.ControllerName;

        sb.AppendLine($"namespace {projectName};");
        sb.AppendLine();
        sb.AppendLine($"#region {controllerName} External API DataObjects");
        sb.AppendLine($"// ============================================================================");
        sb.AppendLine($"// {controllerName.ToUpper()} API DATA TRANSFER OBJECTS");
        sb.AppendLine($"// Generated by Entity Builder Wizard");
        sb.AppendLine($"// ============================================================================");
        sb.AppendLine();
        sb.AppendLine($"public partial class DataObjects");
        sb.AppendLine($"{{");

        // Event Request DTO
        sb.AppendLine($"    /// <summary>Incoming event from external source system.</summary>");
        sb.AppendLine($"    public class {controllerName}EventRequest");
        sb.AppendLine($"    {{");

        // Include relevant properties from event entity (excluding system fields)
        foreach (var prop in eventEntity.Properties.Where(p =>
            !p.Name.EndsWith("Id") || p.Name == "SourceEventId" || p.Name == "SubjectId" || p.Name == "UserId"))
        {
            if (prop.Name.StartsWith("Created") || prop.Name.StartsWith("Modified") ||
                prop.Name == "TenantId" || prop.Name == "Deleted" || prop.Name == "ReceivedAt")
                continue;

            var nullableMarker = prop.IsNullable || !prop.IsRequired ? "?" : "";
            var defaultValue = prop.Type == "string" ? " = string.Empty;" : "";
            if (prop.IsNullable || !prop.IsRequired) defaultValue = "";

            sb.AppendLine($"        public {prop.Type}{nullableMarker} {prop.Name} {{ get; set; }}{defaultValue}");
        }

        sb.AppendLine($"    }}");
        sb.AppendLine();

        // Event Response DTO
        sb.AppendLine($"    /// <summary>Response after processing an event.</summary>");
        sb.AppendLine($"    public class {controllerName}EventResponse");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        public Guid? EventId {{ get; set; }}");
        sb.AppendLine($"        public DateTime ReceivedAt {{ get; set; }} = DateTime.UtcNow;");
        sb.AppendLine($"        public string Status {{ get; set; }} = string.Empty; // accepted, duplicate, error");
        sb.AppendLine($"        public string? Message {{ get; set; }}");
        sb.AppendLine($"    }}");
        sb.AppendLine();

        // Batch Response DTO
        if (config.AllowBatch)
        {
            sb.AppendLine($"    /// <summary>Response after processing a batch of events.</summary>");
            sb.AppendLine($"    public class {controllerName}BatchResponse");
            sb.AppendLine($"    {{");
            sb.AppendLine($"        public int Accepted {{ get; set; }}");
            sb.AppendLine($"        public int Rejected {{ get; set; }}");
            sb.AppendLine($"        public int Duplicate {{ get; set; }}");
            sb.AppendLine($"        public List<{controllerName}BatchError> Errors {{ get; set; }} = new();");
            sb.AppendLine($"    }}");
            sb.AppendLine();

            sb.AppendLine($"    /// <summary>Error detail for a single event in a batch.</summary>");
            sb.AppendLine($"    public class {controllerName}BatchError");
            sb.AppendLine($"    {{");
            sb.AppendLine($"        public int Index {{ get; set; }}");
            sb.AppendLine($"        public string Error {{ get; set; }} = string.Empty;");
            sb.AppendLine($"    }}");
            sb.AppendLine();
        }

        // Stats DTO
        sb.AppendLine($"    /// <summary>Dashboard statistics.</summary>");
        sb.AppendLine($"    public class {controllerName}Stats");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        public long Today {{ get; set; }}");
        sb.AppendLine($"        public long ThisWeek {{ get; set; }}");
        sb.AppendLine($"        public long ThisMonth {{ get; set; }}");
        sb.AppendLine($"        public Dictionary<string, long> ByCategory {{ get; set; }} = new();");
        sb.AppendLine($"        public Dictionary<string, long> ByAccessType {{ get; set; }} = new();");
        sb.AppendLine($"    }}");

        sb.AppendLine($"}}");
        sb.AppendLine();
        sb.AppendLine($"#endregion");

        return sb.ToString();
    }

    // ============================================================
    // EXTERNAL API DATA ACCESS GENERATION
    // ============================================================

    /// <summary>
    /// Generates DataAccess methods for external API event processing.
    /// </summary>
    public static string GenerateExternalApiDataAccess(
        DataObjects.ExternalApiConfig config,
        DataObjects.EntityDefinition eventEntity,
        string projectName)
    {
        var sb = new StringBuilder();
        var controllerName = config.ControllerName;
        var entityName = config.EntityName;

        // Add using statements and namespace
        sb.AppendLine($"using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        sb.AppendLine($"namespace {projectName};");
        sb.AppendLine();
        sb.AppendLine($"// ============================================================================");
        sb.AppendLine($"// {controllerName.ToUpper()} EXTERNAL API DATA ACCESS");
        sb.AppendLine($"// ============================================================================");
        sb.AppendLine();

        // Generate the IDataAccess partial interface FIRST
        sb.AppendLine($"/// <summary>{controllerName} External API interface extensions.</summary>");
        sb.AppendLine($"public partial interface IDataAccess");
        sb.AppendLine($"{{");
        sb.AppendLine($"    /// <summary>Process a single event from external source.</summary>");
        sb.AppendLine($"    Task<DataObjects.{controllerName}EventResponse> Process{controllerName}EventAsync(DataObjects.{controllerName}EventRequest request, Guid sourceSystemId);");
        sb.AppendLine();

        if (config.AllowBatch)
        {
            sb.AppendLine($"    /// <summary>Process a batch of events from external source.</summary>");
            sb.AppendLine($"    Task<DataObjects.{controllerName}BatchResponse> Process{controllerName}BatchAsync(List<DataObjects.{controllerName}EventRequest> requests, Guid sourceSystemId);");
            sb.AppendLine();
        }

        sb.AppendLine($"    /// <summary>Get dashboard statistics.</summary>");
        sb.AppendLine($"    Task<DataObjects.{controllerName}Stats> Get{controllerName}StatsAsync();");
        sb.AppendLine();

        sb.AppendLine($"    /// <summary>Get recent events for dashboard feed.</summary>");
        sb.AppendLine($"    Task<List<DataObjects.{entityName}>> GetRecent{entityName}sAsync(int limit = 50);");
        sb.AppendLine($"}}");
        sb.AppendLine();

        // Now generate the DataAccess partial class implementation
        sb.AppendLine($"public partial class DataAccess");
        sb.AppendLine($"{{");
        sb.AppendLine($"    #region {controllerName} External API");
        sb.AppendLine();

        // ProcessEvent
        sb.AppendLine($"    /// <summary>Process a single event from external source.</summary>");
        sb.AppendLine($"    public async Task<DataObjects.{controllerName}EventResponse> Process{controllerName}EventAsync(");
        sb.AppendLine($"        DataObjects.{controllerName}EventRequest request, Guid sourceSystemId)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        var response = new DataObjects.{controllerName}EventResponse");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            ReceivedAt = DateTime.UtcNow");
        sb.AppendLine($"        }};");
        sb.AppendLine();

        // Validation
        sb.AppendLine($"        // Validation");
        sb.AppendLine($"        if (string.IsNullOrWhiteSpace(request.SubjectId))");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            response.Status = \"error\";");
        sb.AppendLine($"            response.Message = \"Missing required field: SubjectId\";");
        sb.AppendLine($"            return response;");
        sb.AppendLine($"        }}");
        sb.AppendLine();

        // Deduplication
        if (!string.IsNullOrEmpty(config.DedupeProperty))
        {
            sb.AppendLine($"        // Deduplication check");
            sb.AppendLine($"        if (!string.IsNullOrEmpty(request.{config.DedupeProperty}))");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            var exists = await data.{eventEntity.PluralName}.AnyAsync(x =>");
            sb.AppendLine($"                x.SourceSystemId == sourceSystemId &&");
            sb.AppendLine($"                x.{config.DedupeProperty} == request.{config.DedupeProperty});");
            sb.AppendLine();
            sb.AppendLine($"            if (exists)");
            sb.AppendLine($"            {{");
            sb.AppendLine($"                response.Status = \"duplicate\";");
            sb.AppendLine($"                response.Message = \"Event with this {config.DedupeProperty} already exists\";");
            sb.AppendLine($"                return response;");
            sb.AppendLine($"            }}");
            sb.AppendLine($"        }}");
            sb.AppendLine();
        }

        // Create event
        sb.AppendLine($"        // Create event record");
        sb.AppendLine($"        var evt = new EFModels.EFModels.{entityName}Item");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            {entityName}Id = Guid.NewGuid(),");
        sb.AppendLine($"            SourceSystemId = sourceSystemId,");
        sb.AppendLine($"            ReceivedAt = DateTime.UtcNow,");

        // Map request properties to entity
        foreach (var prop in eventEntity.Properties.Where(p =>
            !p.Name.EndsWith("Id") || p.Name == "SourceEventId" || p.Name == "SubjectId" || p.Name == "UserId"))
        {
            if (prop.Name.StartsWith("Created") || prop.Name.StartsWith("Modified") ||
                prop.Name == "TenantId" || prop.Name == "Deleted" || prop.Name == "ReceivedAt" ||
                prop.Name == "SourceSystemId")
                continue;

            sb.AppendLine($"            {prop.Name} = request.{prop.Name},");
        }

        sb.AppendLine($"        }};");
        sb.AppendLine();
        sb.AppendLine($"        data.{eventEntity.PluralName}.Add(evt);");
        sb.AppendLine();

        // Update source system stats
        sb.AppendLine($"        // Update source system stats");
        sb.AppendLine($"        await data.{config.ApiKeyEntity}s");
        sb.AppendLine($"            .Where(x => x.{config.ApiKeyEntity}Id == sourceSystemId)");
        sb.AppendLine($"            .ExecuteUpdateAsync(s => s");
        sb.AppendLine($"                .SetProperty(x => x.EventCount, x => x.EventCount + 1)");
        sb.AppendLine($"                .SetProperty(x => x.LastEventReceivedAt, DateTime.UtcNow));");
        sb.AppendLine();

        // Update stats entity if configured
        if (!string.IsNullOrEmpty(config.StatsEntity))
        {
            sb.AppendLine($"        // Update {config.StatsEntity} stats");
            sb.AppendLine($"        await Update{config.StatsEntity}StatsAsync(request.SubjectId);");
            sb.AppendLine();
        }

        sb.AppendLine($"        await data.SaveChangesAsync();");
        sb.AppendLine();
        sb.AppendLine($"        response.EventId = evt.{entityName}Id;");
        sb.AppendLine($"        response.Status = \"accepted\";");
        sb.AppendLine($"        return response;");
        sb.AppendLine($"    }}");
        sb.AppendLine();

        // ProcessBatch
        if (config.AllowBatch)
        {
            sb.AppendLine($"    /// <summary>Process a batch of events from external source.</summary>");
            sb.AppendLine($"    public async Task<DataObjects.{controllerName}BatchResponse> Process{controllerName}BatchAsync(");
            sb.AppendLine($"        List<DataObjects.{controllerName}EventRequest> requests, Guid sourceSystemId)");
            sb.AppendLine($"    {{");
            sb.AppendLine($"        var response = new DataObjects.{controllerName}BatchResponse();");
            sb.AppendLine();
            sb.AppendLine($"        for (int i = 0; i < requests.Count; i++)");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            try");
            sb.AppendLine($"            {{");
            sb.AppendLine($"                var result = await Process{controllerName}EventAsync(requests[i], sourceSystemId);");
            sb.AppendLine($"                switch (result.Status)");
            sb.AppendLine($"                {{");
            sb.AppendLine($"                    case \"accepted\": response.Accepted++; break;");
            sb.AppendLine($"                    case \"duplicate\": response.Duplicate++; break;");
            sb.AppendLine($"                    default:");
            sb.AppendLine($"                        response.Rejected++;");
            sb.AppendLine($"                        response.Errors.Add(new DataObjects.{controllerName}BatchError {{ Index = i, Error = result.Message ?? \"Unknown error\" }});");
            sb.AppendLine($"                        break;");
            sb.AppendLine($"                }}");
            sb.AppendLine($"            }}");
            sb.AppendLine($"            catch (Exception ex)");
            sb.AppendLine($"            {{");
            sb.AppendLine($"                response.Rejected++;");
            sb.AppendLine($"                response.Errors.Add(new DataObjects.{controllerName}BatchError {{ Index = i, Error = ex.Message }});");
            sb.AppendLine($"            }}");
            sb.AppendLine($"        }}");
            sb.AppendLine();
            sb.AppendLine($"        return response;");
            sb.AppendLine($"    }}");
            sb.AppendLine();
        }

        // GetStats
        var dateProperty = config.StatsEntity != null ? "AccessedAt" : "ReceivedAt";
        sb.AppendLine($"    /// <summary>Get dashboard statistics.</summary>");
        sb.AppendLine($"    public async Task<DataObjects.{controllerName}Stats> Get{controllerName}StatsAsync()");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        var now = DateTime.UtcNow;");
        sb.AppendLine($"        var todayStart = now.Date;");
        sb.AppendLine($"        var weekStart = now.Date.AddDays(-(int)now.DayOfWeek);");
        sb.AppendLine($"        var monthStart = new DateTime(now.Year, now.Month, 1);");
        sb.AppendLine();
        sb.AppendLine($"        return new DataObjects.{controllerName}Stats");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            Today = await data.{eventEntity.PluralName}.CountAsync(x => x.{dateProperty} >= todayStart),");
        sb.AppendLine($"            ThisWeek = await data.{eventEntity.PluralName}.CountAsync(x => x.{dateProperty} >= weekStart),");
        sb.AppendLine($"            ThisMonth = await data.{eventEntity.PluralName}.CountAsync(x => x.{dateProperty} >= monthStart),");
        sb.AppendLine($"        }};");
        sb.AppendLine($"    }}");
        sb.AppendLine();

        // GetRecentEvents - use inline mapping instead of calling a mapper method
        sb.AppendLine($"    /// <summary>Get recent events for dashboard feed.</summary>");
        sb.AppendLine($"    public async Task<List<DataObjects.{entityName}>> GetRecent{entityName}sAsync(int limit = 50)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        return await data.{eventEntity.PluralName}");
        sb.AppendLine($"            .OrderByDescending(x => x.{dateProperty})");
        sb.AppendLine($"            .Take(limit)");
        sb.AppendLine($"            .Select(x => new DataObjects.{entityName}");
        sb.AppendLine($"            {{");
        foreach (var prop in eventEntity.Properties.Where(p => !p.IsSystemField || p.IsPrimaryKey))
        {
            sb.AppendLine($"                {prop.Name} = x.{prop.Name},");
        }
        sb.AppendLine($"            }})");
        sb.AppendLine($"            .ToListAsync();");
        sb.AppendLine($"    }}");
        sb.AppendLine();

        // UpdateStatsEntity helper
        if (!string.IsNullOrEmpty(config.StatsEntity))
        {
            sb.AppendLine($"    /// <summary>Update or create {config.StatsEntity} stats on event.</summary>");
            sb.AppendLine($"    private async Task Update{config.StatsEntity}StatsAsync(string subjectId)");
            sb.AppendLine($"    {{");
            sb.AppendLine($"        var subject = await data.{config.StatsEntity}s");
            sb.AppendLine($"            .FirstOrDefaultAsync(x => x.{config.StatsMatchProperty} == subjectId);");
            sb.AppendLine();
            sb.AppendLine($"        if (subject == null)");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            subject = new EFModels.EFModels.{config.StatsEntity}Item");
            sb.AppendLine($"            {{");
            sb.AppendLine($"                {config.StatsEntity}Id = Guid.NewGuid(),");
            sb.AppendLine($"                {config.StatsMatchProperty} = subjectId,");
            sb.AppendLine($"                FirstAccessedAt = DateTime.UtcNow,");
            sb.AppendLine($"                TotalAccessCount = 0");
            sb.AppendLine($"            }};");
            sb.AppendLine($"            data.{config.StatsEntity}s.Add(subject);");
            sb.AppendLine($"        }}");
            sb.AppendLine();
            sb.AppendLine($"        subject.LastAccessedAt = DateTime.UtcNow;");
            sb.AppendLine($"        subject.TotalAccessCount++;");
            sb.AppendLine($"    }}");
        }

        sb.AppendLine();
        sb.AppendLine($"    #endregion");
        sb.AppendLine($"}}");

        return sb.ToString();
    }
}

#endregion
