using System.Text;

namespace FreeManager;

#region EntityTemplates - Razor Pages Generation
// ============================================================================
// ENTITY WIZARD - RAZOR PAGE TEMPLATES
// Generates List and Edit Blazor pages.
// Part of: EntityTemplates.App (partial)
// ============================================================================

public static partial class EntityTemplates
{
    // ============================================================
    // LIST PAGE TEMPLATE (Relationship-Aware)
    // ============================================================

    private static string GenerateListPage(
        DataObjects.EntityDefinition entity,
        List<DataObjects.RelationshipDefinition> relationships,
        List<DataObjects.EntityDefinition> allEntities,
        DataObjects.EntityWizardOptions options,
        string projectName)
    {
        var sb = new StringBuilder();
        var pkProp = entity.Properties.FirstOrDefault(p => p.IsPrimaryKey);
        var pkName = pkProp?.Name ?? $"{entity.Name}Id";

        var parentRels = GetParentRelationships(entity.Name, relationships);

        var displayProps = entity.Properties
            .Where(p => !p.IsPrimaryKey && !p.IsSystemField && p.Name != "Deleted")
            .Where(p => !parentRels.Any(r => r.ForeignKeyProperty == p.Name))
            .OrderBy(p => p.SortOrder)
            .Take(5)
            .ToList();

        sb.AppendLine($"@* {projectName}.App.{entity.PluralName}Page.razor - List page for {entity.Name} *@");
        sb.AppendLine($"@* Generated by Entity Builder Wizard *@");
        sb.AppendLine($"@page \"/{entity.PluralName}\"");
        sb.AppendLine($"@page \"/{{TenantCode}}/{entity.PluralName}\"");
        sb.AppendLine($"@implements IDisposable");
        sb.AppendLine($"@inject BlazorDataModel Model");
        sb.AppendLine($"@inject HttpClient Http");
        sb.AppendLine();
        sb.AppendLine($"@if (Model.Loaded && Model.LoggedIn && Model.View == _pageName) {{");
        sb.AppendLine($"    <div class=\"container-fluid\">");
        sb.AppendLine($"        <div class=\"@Model.StickyMenuClass\">");
        sb.AppendLine($"            <div class=\"d-flex justify-content-between align-items-center\">");
        sb.AppendLine($"                <h1 class=\"page-title mb-0\">");
        sb.AppendLine($"                    <i class=\"fa-solid fa-cubes me-2\"></i>{entity.PluralName}");
        sb.AppendLine($"                </h1>");
        if (!options.IsReadOnly)
        {
            sb.AppendLine($"                <button class=\"btn btn-primary\" @onclick=\"CreateNew\">");
            sb.AppendLine($"                    <i class=\"fa-solid fa-plus me-1\"></i>New {entity.Name}");
            sb.AppendLine($"                </button>");
        }
        sb.AppendLine($"            </div>");
        sb.AppendLine($"        </div>");
        sb.AppendLine();

        // Filter bar
        sb.AppendLine($"        <div class=\"card shadow-sm mb-3\">");
        sb.AppendLine($"            <div class=\"card-body py-2\">");
        sb.AppendLine($"                <div class=\"row g-2 align-items-center\">");
        sb.AppendLine($"                    <div class=\"col-md-3\">");
        sb.AppendLine($"                        <div class=\"input-group input-group-sm\">");
        sb.AppendLine($"                            <span class=\"input-group-text\"><i class=\"fa-solid fa-search\"></i></span>");
        sb.AppendLine($"                            <input type=\"text\" class=\"form-control\" placeholder=\"Search...\"");
        sb.AppendLine($"                                   @bind=\"_filter.Search\" @bind:event=\"oninput\" @bind:after=\"LoadData\" />");
        sb.AppendLine($"                        </div>");
        sb.AppendLine($"                    </div>");
        sb.AppendLine($"                    <div class=\"col-md-2\">");
        sb.AppendLine($"                        <select class=\"form-select form-select-sm\" @bind=\"_filter.PageSize\" @bind:after=\"LoadData\">");
        sb.AppendLine($"                            <option value=\"10\">10 per page</option>");
        sb.AppendLine($"                            <option value=\"25\">25 per page</option>");
        sb.AppendLine($"                            <option value=\"50\">50 per page</option>");
        sb.AppendLine($"                        </select>");
        sb.AppendLine($"                    </div>");
        sb.AppendLine($"                </div>");
        sb.AppendLine($"            </div>");
        sb.AppendLine($"        </div>");
        sb.AppendLine();

        // Data grid
        sb.AppendLine($"        @if (_loading) {{");
        sb.AppendLine($"            <div class=\"text-center py-5\"><i class=\"fa-solid fa-spinner fa-spin fa-2x\"></i></div>");
        sb.AppendLine($"        }} else if (_result.Records.Count == 0) {{");
        sb.AppendLine($"            <div class=\"text-center py-5 text-muted\">");
        sb.AppendLine($"                <i class=\"fa-solid fa-inbox fa-4x mb-3 opacity-50\"></i>");
        sb.AppendLine($"                <h4>No {entity.PluralName.ToLower()} found</h4>");
        sb.AppendLine($"            </div>");
        sb.AppendLine($"        }} else {{");
        sb.AppendLine($"            <div class=\"card shadow-sm\">");
        sb.AppendLine($"                <div class=\"table-responsive\">");
        sb.AppendLine($"                    <table class=\"table table-hover align-middle mb-0\">");
        sb.AppendLine($"                        <thead class=\"table-light\">");
        sb.AppendLine($"                            <tr>");
        foreach (var prop in displayProps)
        {
            sb.AppendLine($"                                <th>{prop.Name}</th>");
        }
        sb.AppendLine($"                                <th style=\"width: 100px;\">Actions</th>");
        sb.AppendLine($"                            </tr>");
        sb.AppendLine($"                        </thead>");
        sb.AppendLine($"                        <tbody>");
        sb.AppendLine($"                            @foreach (var item in _result.Records) {{");
        sb.AppendLine($"                                <tr>");
        foreach (var prop in displayProps)
        {
            var displayExpr = GetDisplayExpression(prop, entity.Enums);
            sb.AppendLine($"                                    <td>{displayExpr}</td>");
        }
        sb.AppendLine($"                                    <td>");
        sb.AppendLine($"                                        <div class=\"btn-group btn-group-sm\">");
        if (!options.IsReadOnly)
        {
            sb.AppendLine($"                                            <button class=\"btn btn-outline-primary\" @onclick=\"@(() => Edit(item))\"><i class=\"fa-solid fa-pen\"></i></button>");
            sb.AppendLine($"                                            <button class=\"btn btn-outline-danger\" @onclick=\"@(() => ConfirmDelete(item))\"><i class=\"fa-solid fa-trash\"></i></button>");
        }
        sb.AppendLine($"                                        </div>");
        sb.AppendLine($"                                    </td>");
        sb.AppendLine($"                                </tr>");
        sb.AppendLine($"                            }}");
        sb.AppendLine($"                        </tbody>");
        sb.AppendLine($"                    </table>");
        sb.AppendLine($"                </div>");
        sb.AppendLine($"            </div>");
        sb.AppendLine($"        }}");
        sb.AppendLine($"    </div>");

        if (!options.IsReadOnly)
        {
            sb.AppendLine();
            sb.AppendLine($"    @if (_showEdit) {{");
            sb.AppendLine($"        <{projectName}_App_Edit{entity.Name} Item=\"_editItem\" OnSave=\"SaveItem\" OnCancel=\"CloseEdit\" />");
            sb.AppendLine($"    }}");
            sb.AppendLine();
            sb.AppendLine($"    @* Delete Confirmation Modal *@");
            sb.AppendLine($"    @if (_showDeleteConfirm) {{");
            sb.AppendLine($"        <div class=\"modal fade show d-block\" tabindex=\"-1\" style=\"background: rgba(0,0,0,0.5);\">");
            sb.AppendLine($"            <div class=\"modal-dialog\">");
            sb.AppendLine($"                <div class=\"modal-content\">");
            sb.AppendLine($"                    <div class=\"modal-header bg-danger text-white\">");
            sb.AppendLine($"                        <h5 class=\"modal-title\"><i class=\"fa-solid fa-triangle-exclamation me-2\"></i>Confirm Delete</h5>");
            sb.AppendLine($"                        <button type=\"button\" class=\"btn-close btn-close-white\" @onclick=\"CancelDelete\"></button>");
            sb.AppendLine($"                    </div>");
            sb.AppendLine($"                    <div class=\"modal-body\">");
            sb.AppendLine($"                        <p>Are you sure you want to delete this {entity.Name.ToLower()}?</p>");
            sb.AppendLine($"                        <p class=\"text-muted small\">This action cannot be undone.</p>");
            sb.AppendLine($"                    </div>");
            sb.AppendLine($"                    <div class=\"modal-footer\">");
            sb.AppendLine($"                        <button type=\"button\" class=\"btn btn-secondary\" @onclick=\"CancelDelete\">@Helpers.ConfirmButtonTextCancel</button>");
            sb.AppendLine($"                        <button type=\"button\" class=\"btn btn-danger\" @onclick=\"DeleteConfirmed\">@Helpers.ConfirmButtonTextDelete</button>");
            sb.AppendLine($"                    </div>");
            sb.AppendLine($"                </div>");
            sb.AppendLine($"            </div>");
            sb.AppendLine($"        </div>");
            sb.AppendLine($"    }}");
        }

        sb.AppendLine($"}}");
        sb.AppendLine();

        // Code section
        sb.AppendLine($"@code {{");
        sb.AppendLine($"    private string _pageName = \"{entity.PluralName.ToLower()}\";");
        sb.AppendLine($"    private bool _loading = true;");
        sb.AppendLine($"    private DataObjects.{entity.Name}Filter _filter = new();");
        sb.AppendLine($"    private DataObjects.{entity.Name}FilterResult _result = new();");
        if (!options.IsReadOnly)
        {
            sb.AppendLine($"    private bool _showEdit = false;");
            sb.AppendLine($"    private DataObjects.{entity.Name} _editItem = new();");
            sb.AppendLine($"    private bool _showDeleteConfirm = false;");
            sb.AppendLine($"    private DataObjects.{entity.Name}? _deleteItem = null;");
        }
        sb.AppendLine();
        sb.AppendLine($"    public void Dispose() {{ Model.OnChange -= StateHasChanged; }}");
        sb.AppendLine();
        sb.AppendLine($"    protected override void OnInitialized() {{");
        sb.AppendLine($"        Model.View = _pageName;");
        sb.AppendLine($"        Model.OnChange += StateHasChanged;");
        sb.AppendLine($"    }}");
        sb.AppendLine();
        sb.AppendLine($"    protected override async Task OnAfterRenderAsync(bool firstRender) {{");
        sb.AppendLine($"        if (firstRender) await LoadData();");
        sb.AppendLine($"    }}");
        sb.AppendLine();
        sb.AppendLine($"    private async Task LoadData() {{");
        sb.AppendLine($"        _loading = true;");
        sb.AppendLine($"        StateHasChanged();");
        sb.AppendLine($"        _result = await Helpers.GetOrPost<DataObjects.{entity.Name}FilterResult>(");
        sb.AppendLine($"            DataObjects.Endpoints.{projectName}.Get{entity.PluralName}, _filter) ?? new();");
        sb.AppendLine($"        _loading = false;");
        sb.AppendLine($"        StateHasChanged();");
        sb.AppendLine($"    }}");

        if (!options.IsReadOnly)
        {
            sb.AppendLine();
            sb.AppendLine($"    private void CreateNew() {{ _editItem = new DataObjects.{entity.Name}(); _showEdit = true; }}");
            sb.AppendLine($"    private void Edit(DataObjects.{entity.Name} item) {{ _editItem = item; _showEdit = true; }}");
            sb.AppendLine($"    private void CloseEdit() {{ _showEdit = false; }}");
            sb.AppendLine();
            sb.AppendLine($"    private async Task SaveItem(DataObjects.{entity.Name} item) {{");
            sb.AppendLine($"        await Helpers.GetOrPost<DataObjects.{entity.Name}>(DataObjects.Endpoints.{projectName}.Save{entity.Name}, item);");
            sb.AppendLine($"        _showEdit = false;");
            sb.AppendLine($"        await LoadData();");
            sb.AppendLine($"    }}");
            sb.AppendLine();
            sb.AppendLine($"    private void ConfirmDelete(DataObjects.{entity.Name} item) {{");
            sb.AppendLine($"        _deleteItem = item;");
            sb.AppendLine($"        _showDeleteConfirm = true;");
            sb.AppendLine($"    }}");
            sb.AppendLine();
            sb.AppendLine($"    private void CancelDelete() {{");
            sb.AppendLine($"        _deleteItem = null;");
            sb.AppendLine($"        _showDeleteConfirm = false;");
            sb.AppendLine($"    }}");
            sb.AppendLine();
            sb.AppendLine($"    private async Task DeleteConfirmed() {{");
            sb.AppendLine($"        if (_deleteItem != null) {{");
            sb.AppendLine($"            await Helpers.GetOrPost<bool>(DataObjects.Endpoints.{projectName}.Delete{entity.Name}, _deleteItem.{pkName});");
            sb.AppendLine($"            _deleteItem = null;");
            sb.AppendLine($"            _showDeleteConfirm = false;");
            sb.AppendLine($"            await LoadData();");
            sb.AppendLine($"        }}");
            sb.AppendLine($"    }}");
        }

        sb.AppendLine($"}}");

        return sb.ToString();
    }

    // Backward compatibility overload
    private static string GenerateListPage(DataObjects.EntityDefinition entity, DataObjects.EntityWizardOptions options, string projectName)
    {
        return GenerateListPage(entity, new List<DataObjects.RelationshipDefinition>(), new List<DataObjects.EntityDefinition>(), options, projectName);
    }

    private static string GetDisplayExpression(DataObjects.PropertyDefinition prop, List<DataObjects.EnumDefinition> enums)
    {
        if (prop.Type == "bool")
        {
            return $"@if (item.{prop.Name}) {{ <i class=\"fa-solid fa-check text-success\"></i> }} else {{ <i class=\"fa-solid fa-minus text-muted\"></i> }}";
        }
        if (prop.Type == "DateTime")
        {
            return $"@item.{prop.Name}.ToString(\"MMM dd, yyyy\")";
        }
        if (prop.Type.StartsWith("enum:"))
        {
            return $"<span class=\"badge bg-secondary\">@item.{prop.Name}</span>";
        }
        return $"@item.{prop.Name}";
    }

    // ============================================================
    // EDIT PAGE TEMPLATE (Relationship-Aware)
    // ============================================================

    private static string GenerateEditPage(
        DataObjects.EntityDefinition entity,
        List<DataObjects.RelationshipDefinition> relationships,
        List<DataObjects.EntityDefinition> allEntities,
        DataObjects.EntityWizardOptions options,
        string projectName)
    {
        var sb = new StringBuilder();
        var pkProp = entity.Properties.FirstOrDefault(p => p.IsPrimaryKey);
        var pkName = pkProp?.Name ?? $"{entity.Name}Id";

        var parentRels = GetParentRelationships(entity.Name, relationships);

        // Get FK properties that have parent relationships (for dropdowns)
        var fkPropsWithParents = parentRels
            .Select(r => new { Rel = r, Prop = entity.Properties.FirstOrDefault(p => p.Name == r.ForeignKeyProperty) })
            .Where(x => x.Prop != null)
            .ToList();

        var editableProps = entity.Properties
            .Where(p => !p.IsPrimaryKey && !p.IsSystemField)
            .Where(p => !parentRels.Any(r => r.ForeignKeyProperty == p.Name)) // FK fields handled separately as dropdowns
            .OrderBy(p => p.SortOrder)
            .ToList();

        sb.AppendLine($"@* {projectName}.App.Edit{entity.Name}.razor - Edit/Create form for {entity.Name} *@");
        sb.AppendLine($"@* Generated by Entity Builder Wizard *@");
        if (fkPropsWithParents.Any())
        {
            sb.AppendLine($"@inject HttpClient Http");
        }
        sb.AppendLine();
        sb.AppendLine($"<div class=\"modal fade show d-block\" tabindex=\"-1\" style=\"background: rgba(0,0,0,0.5);\">");
        sb.AppendLine($"    <div class=\"modal-dialog modal-lg\">");
        sb.AppendLine($"        <div class=\"modal-content\">");
        sb.AppendLine($"            <div class=\"modal-header\">");
        sb.AppendLine($"                <h5 class=\"modal-title\">");
        sb.AppendLine($"                    <i class=\"fa-solid @(IsNew ? \"fa-plus\" : \"fa-pen\") me-2\"></i>");
        sb.AppendLine($"                    @(IsNew ? \"New\" : \"Edit\") {entity.Name}");
        sb.AppendLine($"                </h5>");
        sb.AppendLine($"                <button type=\"button\" class=\"btn-close\" @onclick=\"Cancel\"></button>");
        sb.AppendLine($"            </div>");
        sb.AppendLine($"            <div class=\"modal-body\">");
        sb.AppendLine($"                <EditForm Model=\"Item\" OnValidSubmit=\"Save\">");
        sb.AppendLine($"                    <DataAnnotationsValidator />");

        // Generate FK dropdown fields first (for parent relationships)
        foreach (var fkInfo in fkPropsWithParents)
        {
            var parentEntity = allEntities.FirstOrDefault(e => e.Name == fkInfo.Rel.SourceEntityName);
            var parentPkName = parentEntity?.Properties.FirstOrDefault(p => p.IsPrimaryKey)?.Name ?? $"{fkInfo.Rel.SourceEntityName}Id";
            var displayProp = parentEntity?.Properties.FirstOrDefault(p => p.Name == "Name" || p.Name == "Title" || p.Name == "DisplayName")?.Name ?? "Name";
            var isRequired = fkInfo.Prop!.IsRequired;
            var isNullable = !isRequired || fkInfo.Prop.IsNullable;

            sb.AppendLine($"                    <div class=\"mb-3\">");
            sb.AppendLine($"                        <label class=\"form-label\">{fkInfo.Rel.SourceEntityName}{(isRequired ? " <span class=\"text-danger\">*</span>" : "")}</label>");
            sb.AppendLine($"                        <select class=\"form-select\" @bind=\"Item.{fkInfo.Prop.Name}\">");
            if (isNullable)
            {
                sb.AppendLine($"                            <option value=\"\">-- None --</option>");
            }
            sb.AppendLine($"                            @foreach (var parent in _{fkInfo.Rel.SourceEntityName.ToLower()}List) {{");
            sb.AppendLine($"                                <option value=\"@parent.{parentPkName}\">@parent.{displayProp}</option>");
            sb.AppendLine($"                            }}");
            sb.AppendLine($"                        </select>");
            sb.AppendLine($"                    </div>");
        }

        // Generate regular form fields
        foreach (var prop in editableProps)
        {
            sb.AppendLine($"                    <div class=\"mb-3\">");
            sb.AppendLine($"                        <label class=\"form-label\">{prop.Name}{(prop.IsRequired ? " <span class=\"text-danger\">*</span>" : "")}</label>");
            sb.Append(GetFormField(prop, entity.Enums));
            sb.AppendLine($"                    </div>");
        }

        sb.AppendLine($"                </EditForm>");
        sb.AppendLine($"            </div>");
        sb.AppendLine($"            <div class=\"modal-footer\">");
        sb.AppendLine($"                <button type=\"button\" class=\"btn btn-secondary\" @onclick=\"Cancel\">Cancel</button>");
        sb.AppendLine($"                <button type=\"button\" class=\"btn btn-primary\" @onclick=\"Save\">Save</button>");
        sb.AppendLine($"            </div>");
        sb.AppendLine($"        </div>");
        sb.AppendLine($"    </div>");
        sb.AppendLine($"</div>");
        sb.AppendLine();
        sb.AppendLine($"@code {{");
        sb.AppendLine($"    [Parameter] public DataObjects.{entity.Name} Item {{ get; set; }} = new();");
        sb.AppendLine($"    [Parameter] public EventCallback<DataObjects.{entity.Name}> OnSave {{ get; set; }}");
        sb.AppendLine($"    [Parameter] public EventCallback OnCancel {{ get; set; }}");
        sb.AppendLine();

        // Add state for parent entity lists
        foreach (var fkInfo in fkPropsWithParents)
        {
            sb.AppendLine($"    private List<DataObjects.{fkInfo.Rel.SourceEntityName}> _{fkInfo.Rel.SourceEntityName.ToLower()}List = new();");
        }

        sb.AppendLine($"    private bool IsNew => Item.{pkName} == default;");
        sb.AppendLine();

        // Add OnInitializedAsync to load parent entity lists
        if (fkPropsWithParents.Any())
        {
            sb.AppendLine($"    protected override async Task OnInitializedAsync() {{");
            foreach (var fkInfo in fkPropsWithParents)
            {
                sb.AppendLine($"        var {fkInfo.Rel.SourceEntityName.ToLower()}Result = await Helpers.GetOrPost<DataObjects.{fkInfo.Rel.SourceEntityName}FilterResult>(");
                sb.AppendLine($"            DataObjects.Endpoints.{projectName}.Get{fkInfo.Rel.SourceEntityName}s, new DataObjects.{fkInfo.Rel.SourceEntityName}Filter {{ PageSize = 1000 }}) ?? new();");
                sb.AppendLine($"        _{fkInfo.Rel.SourceEntityName.ToLower()}List = {fkInfo.Rel.SourceEntityName.ToLower()}Result.Records;");
            }
            sb.AppendLine($"    }}");
            sb.AppendLine();
        }

        sb.AppendLine($"    private async Task Save() => await OnSave.InvokeAsync(Item);");
        sb.AppendLine($"    private async Task Cancel() => await OnCancel.InvokeAsync();");
        sb.AppendLine($"}}");

        return sb.ToString();
    }

    // Backward compatibility overload
    private static string GenerateEditPage(DataObjects.EntityDefinition entity, DataObjects.EntityWizardOptions options, string projectName)
    {
        return GenerateEditPage(entity, new List<DataObjects.RelationshipDefinition>(), new List<DataObjects.EntityDefinition>(), options, projectName);
    }

    private static string GetFormField(DataObjects.PropertyDefinition prop, List<DataObjects.EnumDefinition> enums)
    {
        var sb = new StringBuilder();
        var bindExpr = $"@bind=\"Item.{prop.Name}\"";

        if (prop.Type == "bool")
        {
            sb.AppendLine($"                        <div class=\"form-check\">");
            sb.AppendLine($"                            <input type=\"checkbox\" class=\"form-check-input\" {bindExpr} />");
            sb.AppendLine($"                        </div>");
        }
        else if (prop.Type == "DateTime")
        {
            sb.AppendLine($"                        <input type=\"datetime-local\" class=\"form-control\" {bindExpr} />");
        }
        else if (prop.Type.StartsWith("enum:"))
        {
            var enumDef = enums.FirstOrDefault(e => e.Name == prop.EnumName);
            sb.AppendLine($"                        <select class=\"form-select\" {bindExpr}>");
            if (enumDef != null)
            {
                foreach (var val in enumDef.Values)
                {
                    sb.AppendLine($"                            <option value=\"{val}\">{val}</option>");
                }
            }
            sb.AppendLine($"                        </select>");
        }
        else if (prop.Type is "int" or "decimal" or "double" or "long")
        {
            sb.AppendLine($"                        <input type=\"number\" class=\"form-control\" {bindExpr} />");
        }
        else if (prop.MaxLength.HasValue && prop.MaxLength > 200)
        {
            sb.AppendLine($"                        <textarea class=\"form-control\" rows=\"3\" {bindExpr}></textarea>");
        }
        else
        {
            sb.AppendLine($"                        <input type=\"text\" class=\"form-control\" {bindExpr} />");
        }

        return sb.ToString();
    }
}

#endregion
