using System.Text;

namespace FreeManager;

#region EntityTemplates - DataObjects Generation
// ============================================================================
// ENTITY WIZARD - DATAOBJECTS TEMPLATES
// Generates DTOs, filter classes, and enums.
// Part of: EntityTemplates.App (partial)
// ============================================================================

public static partial class EntityTemplates
{
    // ============================================================
    // MULTI-ENTITY DATAOBJECTS TEMPLATE
    // ============================================================

    private static string GenerateDataObjectsMulti(
        List<DataObjects.EntityDefinition> entities,
        List<DataObjects.RelationshipDefinition> relationships,
        DataObjects.EntityWizardOptions options,
        string projectName)
    {
        var sb = new StringBuilder();

        sb.AppendLine($"namespace {projectName};");
        sb.AppendLine();
        sb.AppendLine($"#region {projectName} DataObjects");
        sb.AppendLine($"// ============================================================================");
        sb.AppendLine($"// {projectName.ToUpper()} PROJECT - Generated by Entity Builder Wizard");
        sb.AppendLine($"// Entities: {string.Join(", ", entities.Select(e => e.Name))}");
        if (relationships.Any())
        {
            sb.AppendLine($"// Relationships: {relationships.Count}");
        }
        sb.AppendLine($"// ============================================================================");
        sb.AppendLine();

        // Open the partial class wrapper
        sb.AppendLine($"public partial class DataObjects");
        sb.AppendLine($"{{");

        // Generate for each entity (with relationship awareness)
        foreach (var entity in entities)
        {
            sb.AppendLine(GenerateDataObjects(entity, relationships, entities, options, projectName));
            sb.AppendLine();
        }

        // Generate lookup DTOs for FK dropdowns
        foreach (var entity in entities.Where(e => !e.IsJoinTable))
        {
            var displayProp = entity.Properties
                .FirstOrDefault(p => p.Name.Contains("Name") || p.Name.Contains("Title") || p.Name.Contains("Description"))
                ?? entity.Properties.FirstOrDefault(p => p.Type == "string" && !p.IsPrimaryKey);
            var pkProp = entity.Properties.FirstOrDefault(p => p.IsPrimaryKey);

            if (displayProp != null && pkProp != null)
            {
                sb.AppendLine($"    /// <summary>Lookup DTO for {entity.Name} dropdowns.</summary>");
                sb.AppendLine($"    public class {entity.Name}Lookup");
                sb.AppendLine($"    {{");
                sb.AppendLine($"        public {pkProp.Type} {pkProp.Name} {{ get; set; }}");
                sb.AppendLine($"        public string DisplayName {{ get; set; }} = string.Empty;");
                sb.AppendLine($"    }}");
                sb.AppendLine();
            }
        }

        // Close the partial class wrapper
        sb.AppendLine($"}}");
        sb.AppendLine();
        sb.AppendLine("#endregion");

        return sb.ToString();
    }

    // ============================================================
    // SINGLE-ENTITY DATAOBJECTS TEMPLATE (with relationship support)
    // ============================================================

    private static string GenerateDataObjects(
        DataObjects.EntityDefinition entity,
        List<DataObjects.RelationshipDefinition> relationships,
        List<DataObjects.EntityDefinition> allEntities,
        DataObjects.EntityWizardOptions options,
        string projectName)
    {
        var sb = new StringBuilder();
        var pkProp = entity.Properties.FirstOrDefault(p => p.IsPrimaryKey);
        var pkName = pkProp?.Name ?? $"{entity.Name}Id";
        var pkType = pkProp?.Type ?? "Guid";

        // Get parent relationships (where this entity has FK to parent)
        var parentRels = GetParentRelationships(entity.Name, relationships);

        // Main DTO class
        sb.AppendLine($"    /// <summary>{entity.Name} data transfer object.</summary>");
        sb.AppendLine($"    public class {entity.Name}");
        sb.AppendLine($"    {{");
        foreach (var prop in entity.Properties.OrderBy(p => p.SortOrder))
        {
            var type = GetDTOType(prop, entity.Enums);
            var defaultVal = GetDTODefault(prop, entity.Enums);
            if (!string.IsNullOrWhiteSpace(prop.Description))
            {
                sb.AppendLine($"        /// <summary>{prop.Description}</summary>");
            }
            sb.AppendLine($"        public {type} {prop.Name} {{ get; set; }}{(string.IsNullOrWhiteSpace(defaultVal) ? "" : $" = {defaultVal};")}");
        }

        // Add FK display name properties for relationships
        foreach (var rel in parentRels)
        {
            sb.AppendLine($"        /// <summary>Display name for related {rel.SourceEntityName}.</summary>");
            sb.AppendLine($"        public string {rel.SourceEntityName}Name {{ get; set; }} = string.Empty;");
        }

        sb.AppendLine($"    }}");
        sb.AppendLine();

        // Filter class with typed filters
        sb.AppendLine($"    /// <summary>Filter criteria for {entity.Name} queries.</summary>");
        sb.AppendLine($"    public class {entity.Name}Filter");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        public string? Search {{ get; set; }}");
        sb.AppendLine($"        public string SortColumn {{ get; set; }} = \"{pkName}\";");
        sb.AppendLine($"        public bool SortDescending {{ get; set; }} = true;");
        sb.AppendLine($"        public int Page {{ get; set; }} = 1;");
        sb.AppendLine($"        public int PageSize {{ get; set; }} = {options.DefaultPageSize};");
        sb.AppendLine($"        public int Skip => (Page - 1) * PageSize;");
        if (options.IncludeSoftDelete)
        {
            sb.AppendLine($"        public bool IncludeDeleted {{ get; set; }} = false;");
        }
        // Add FK filter for parent relationships
        foreach (var rel in parentRels)
        {
            var fkNullable = !rel.IsRequired;
            sb.AppendLine($"        public Guid{(fkNullable ? "?" : "")} {rel.ForeignKeyProperty}Filter {{ get; set; }}");
        }
        // Add typed filters for filterable properties
        foreach (var prop in entity.Properties.Where(p => p.IsFilterable && !p.IsPrimaryKey && !p.IsSystemField))
        {
            var filterType = GetFilterPropertyType(prop, entity.Enums);
            if (!string.IsNullOrEmpty(filterType))
            {
                sb.AppendLine($"        public {filterType} {prop.Name}Filter {{ get; set; }}");
            }
        }
        sb.AppendLine($"    }}");
        sb.AppendLine();

        // Filter result with pagination
        sb.AppendLine($"    /// <summary>Paginated result for {entity.Name} queries.</summary>");
        sb.AppendLine($"    public class {entity.Name}FilterResult");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        public List<{entity.Name}> Records {{ get; set; }} = new();");
        sb.AppendLine($"        public int TotalRecords {{ get; set; }}");
        sb.AppendLine($"        public int Page {{ get; set; }}");
        sb.AppendLine($"        public int PageSize {{ get; set; }}");
        sb.AppendLine($"        public int TotalPages => (int)Math.Ceiling((double)TotalRecords / PageSize);");
        sb.AppendLine($"    }}");

        // Enums
        foreach (var enumDef in entity.Enums)
        {
            sb.AppendLine();
            sb.AppendLine($"    /// <summary>{enumDef.Name} enumeration.</summary>");
            sb.AppendLine($"    public enum {enumDef.Name}");
            sb.AppendLine($"    {{");
            for (int i = 0; i < enumDef.Values.Count; i++)
            {
                var comma = i < enumDef.Values.Count - 1 ? "," : "";
                sb.AppendLine($"        {enumDef.Values[i]}{comma}");
            }
            sb.AppendLine($"    }}");
        }

        return sb.ToString();
    }

    // Backward compatibility overload
    private static string GenerateDataObjects(DataObjects.EntityDefinition entity, DataObjects.EntityWizardOptions options, string projectName)
    {
        return GenerateDataObjects(entity, new List<DataObjects.RelationshipDefinition>(), new List<DataObjects.EntityDefinition>(), options, projectName);
    }

    // ============================================================
    // DTO TYPE HELPERS
    // ============================================================

    private static string GetDTOType(DataObjects.PropertyDefinition prop, List<DataObjects.EnumDefinition> enums)
    {
        var type = prop.Type.StartsWith("enum:") ? prop.EnumName! : prop.Type;
        if (prop.IsNullable && !type.EndsWith("?")) type += "?";
        return type;
    }

    private static string GetDTODefault(DataObjects.PropertyDefinition prop, List<DataObjects.EnumDefinition> enums)
    {
        if (!string.IsNullOrWhiteSpace(prop.DefaultValue)) return prop.DefaultValue;
        return prop.Type switch
        {
            "string" => "string.Empty",
            _ => null!
        };
    }

    private static string? GetFilterPropertyType(DataObjects.PropertyDefinition prop, List<DataObjects.EnumDefinition> enums)
    {
        if (prop.Type.StartsWith("enum:"))
        {
            return $"List<{prop.EnumName}>?";
        }
        return prop.Type switch
        {
            "bool" => "bool?",
            "DateTime" => "(DateTime? Start, DateTime? End)?",
            "int" or "decimal" or "double" => "(decimal? Min, decimal? Max)?",
            "string" => null,
            _ => null
        };
    }

    // ============================================================
    // ENDPOINTS FILE GENERATION
    // ============================================================

    /// <summary>
    /// Generates API endpoint route constants for all entities.
    /// Routes follow FreeCRM convention: api/Data/{MethodName}
    /// </summary>
    private static string GenerateEndpoints(
        List<DataObjects.EntityDefinition> entities,
        DataObjects.EntityWizardOptions options,
        string projectName)
    {
        var sb = new StringBuilder();

        sb.AppendLine($"namespace {projectName};");
        sb.AppendLine();
        sb.AppendLine($"#region {projectName} API Endpoints");
        sb.AppendLine($"// ============================================================================");
        sb.AppendLine($"// {projectName.ToUpper()} PROJECT - API Endpoint Constants");
        sb.AppendLine($"// Generated by Entity Builder Wizard");
        sb.AppendLine($"// ============================================================================");
        sb.AppendLine();
        sb.AppendLine($"public partial class DataObjects");
        sb.AppendLine($"{{");
        sb.AppendLine($"    public static partial class Endpoints");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        public static class {projectName}");
        sb.AppendLine($"        {{");

        foreach (var entity in entities.Where(e => !e.IsJoinTable))
        {
            sb.AppendLine($"            // ============================================================");
            sb.AppendLine($"            // {entity.Name.ToUpper()} ENDPOINTS");
            sb.AppendLine($"            // ============================================================");
            sb.AppendLine();

            // Get filtered list
            sb.AppendLine($"            /// <summary>Get filtered list of {entity.PluralName}</summary>");
            sb.AppendLine($"            public const string Get{entity.PluralName} = \"api/Data/Get{entity.PluralName}\";");
            sb.AppendLine();

            // Get by ID
            sb.AppendLine($"            /// <summary>Get single {entity.Name} by ID</summary>");
            sb.AppendLine($"            public const string Get{entity.Name} = \"api/Data/Get{entity.Name}\";");
            sb.AppendLine();

            // Lookups
            sb.AppendLine($"            /// <summary>Get {entity.Name} lookup list for dropdowns</summary>");
            sb.AppendLine($"            public const string Get{entity.Name}Lookups = \"api/Data/Get{entity.Name}Lookups\";");
            sb.AppendLine();

            if (!options.IsReadOnly)
            {
                // Save
                sb.AppendLine($"            /// <summary>Create or update {entity.Name}</summary>");
                sb.AppendLine($"            public const string Save{entity.Name} = \"api/Data/Save{entity.Name}\";");
                sb.AppendLine();

                // Delete
                sb.AppendLine($"            /// <summary>Delete {entity.Name} by ID</summary>");
                sb.AppendLine($"            public const string Delete{entity.Name} = \"api/Data/Delete{entity.Name}\";");
                sb.AppendLine();
            }
        }

        sb.AppendLine($"        }}");
        sb.AppendLine($"    }}");
        sb.AppendLine($"}}");
        sb.AppendLine();
        sb.AppendLine($"#endregion");

        return sb.ToString();
    }
}

#endregion
