namespace FreeManager.Client;

#region PagePatterns - KanbanBoard
// ============================================================================
// PAGE PATTERN: KANBAN BOARD
// Drag-and-drop columns for visual workflow management
//
// Generated Files:
// - KanbanBoard.razor: Main board container with columns
// - KanbanColumn.razor: Individual column component with WIP limits
// - KanbanCard.razor: Draggable card component
// - CardEditor.razor: Quick edit modal for cards
// ============================================================================

public static partial class PagePatterns
{
    /// <summary>
    /// Generate KanbanBoard files for the given entity/project.
    /// </summary>
    public static List<(string FileName, string FileType, string Content)> GetKanbanBoardFiles(
        string projectName,
        DataObjects.EntityDefinition? entity = null)
    {
        List<(string, string, string)> files = new();

        files.Add(($"{projectName}.App.KanbanBoard.razor", "RazorComponent", GetKanbanBoard_KanbanBoard(projectName, entity)));
        files.Add(($"{projectName}.App.KanbanColumn.razor", "RazorComponent", GetKanbanBoard_KanbanColumn(projectName, entity)));
        files.Add(($"{projectName}.App.KanbanCard.razor", "RazorComponent", GetKanbanBoard_KanbanCard(projectName, entity)));
        files.Add(($"{projectName}.App.CardEditor.razor", "RazorComponent", GetKanbanBoard_CardEditor(projectName, entity)));

        return files;
    }

    // ============================================================
    // KANBAN BOARD - Main Container
    // ============================================================

    private static string GetKanbanBoard_KanbanBoard(string name, DataObjects.EntityDefinition? entity) => $@"@* {name} - KanbanBoard.razor *@
@* Generated by Page Pattern: KanbanBoard *@
@page ""/kanban""
@page ""/{{TenantCode}}/kanban""
@implements IDisposable
@inject BlazorDataModel Model
@inject HttpClient Http

@if (Model.Loaded && Model.LoggedIn && Model.View == _pageName) {{
    <div class=""container-fluid"">
        <div class=""@Model.StickyMenuClass"">
            <div class=""d-flex justify-content-between align-items-center"">
                <h1 class=""page-title mb-0"">
                    <i class=""fa-solid fa-grip-vertical me-2""></i>Kanban Board
                </h1>
                <div class=""d-flex gap-2"">
                    <button class=""btn btn-outline-secondary"" @onclick=""ToggleSwimlanes"">
                        <i class=""fa-solid @(_showSwimlanes ? ""fa-compress"" : ""fa-layer-group"") me-1""></i>
                        @(_showSwimlanes ? ""Hide"" : ""Show"") Swimlanes
                    </button>
                    <button class=""btn btn-primary"" @onclick=""AddCard"">
                        <i class=""fa-solid fa-plus me-1""></i>New Card
                    </button>
                </div>
            </div>
        </div>

        @* Swimlane header (optional grouping) *@
        @if (_showSwimlanes) {{
            <div class=""swimlane-container"">
                @foreach (var swimlane in _swimlanes) {{
                    <div class=""swimlane mb-4"">
                        <div class=""swimlane-header d-flex align-items-center mb-2"">
                            <i class=""fa-solid fa-stream me-2""></i>
                            <strong>@swimlane</strong>
                            <span class=""badge bg-secondary ms-2"">@GetSwimlaneCardCount(swimlane)</span>
                        </div>
                        <div class=""kanban-board d-flex gap-3 overflow-auto pb-3"">
                            @foreach (var column in _columns) {{
                                <{name}_App_KanbanColumn
                                    Column=""column""
                                    Cards=""GetCardsForColumn(column.Id, swimlane)""
                                    OnCardDrop=""@((args) => HandleCardDrop(args.cardId, column.Id, swimlane))""
                                    OnCardClick=""EditCard""
                                    OnAddCard=""@(() => AddCardToColumn(column.Id, swimlane))"" />
                            }}
                        </div>
                    </div>
                }}
            </div>
        }} else {{
            <div class=""kanban-board d-flex gap-3 overflow-auto pb-3"" style=""min-height: calc(100vh - 200px);"">
                @foreach (var column in _columns) {{
                    <{name}_App_KanbanColumn
                        Column=""column""
                        Cards=""GetCardsForColumn(column.Id, null)""
                        OnCardDrop=""@((args) => HandleCardDrop(args.cardId, column.Id, null))""
                        OnCardClick=""EditCard""
                        OnAddCard=""@(() => AddCardToColumn(column.Id, null))"" />
                }}
            </div>
        }}
    </div>

    @if (_showEditor) {{
        <{name}_App_CardEditor
            Card=""_editingCard""
            Columns=""_columns""
            Swimlanes=""_swimlanes""
            OnSave=""SaveCard""
            OnDelete=""DeleteCard""
            OnCancel=""CloseEditor"" />
    }}
}}

<style>
    .kanban-board {{
        min-height: 500px;
    }}
    .swimlane {{
        background: var(--bs-gray-100);
        border-radius: 8px;
        padding: 1rem;
    }}
    .swimlane-header {{
        color: var(--bs-gray-700);
        font-size: 0.9rem;
        text-transform: uppercase;
        letter-spacing: 0.05em;
    }}
</style>

@code {{
    private string _pageName = ""kanban"";
    private bool _loading = true;
    private bool _showSwimlanes = false;
    private bool _showEditor = false;

    private List<KanbanColumnModel> _columns = new();
    private List<KanbanCardModel> _cards = new();
    private List<string> _swimlanes = new() {{ ""Default"" }};
    private KanbanCardModel _editingCard = new();

    public void Dispose() {{ Model.OnChange -= StateHasChanged; }}

    protected override void OnInitialized() {{
        Model.View = _pageName;
        Model.OnChange += StateHasChanged;
        InitializeBoard();
    }}

    private void InitializeBoard() {{
        // Default columns matching typical workflow statuses
        _columns = new List<KanbanColumnModel> {{
            new() {{ Id = ""todo"", Title = ""To Do"", Color = ""#6c757d"", WipLimit = 0, Order = 0 }},
            new() {{ Id = ""in-progress"", Title = ""In Progress"", Color = ""#0d6efd"", WipLimit = 5, Order = 1 }},
            new() {{ Id = ""review"", Title = ""In Review"", Color = ""#ffc107"", WipLimit = 3, Order = 2 }},
            new() {{ Id = ""done"", Title = ""Done"", Color = ""#198754"", WipLimit = 0, Order = 3 }}
        }};

        // Sample cards for demonstration
        _cards = new List<KanbanCardModel> {{
            new() {{ Id = Guid.NewGuid(), Title = ""Sample task 1"", ColumnId = ""todo"", Order = 0 }},
            new() {{ Id = Guid.NewGuid(), Title = ""Sample task 2"", ColumnId = ""in-progress"", Order = 0 }}
        }};

        _loading = false;
    }}

    private List<KanbanCardModel> GetCardsForColumn(string columnId, string? swimlane) {{
        return _cards
            .Where(c => c.ColumnId == columnId && (swimlane == null || c.Swimlane == swimlane || (swimlane == ""Default"" && string.IsNullOrEmpty(c.Swimlane))))
            .OrderBy(c => c.Order)
            .ToList();
    }}

    private int GetSwimlaneCardCount(string swimlane) {{
        return _cards.Count(c => c.Swimlane == swimlane || (swimlane == ""Default"" && string.IsNullOrEmpty(c.Swimlane)));
    }}

    private void ToggleSwimlanes() {{
        _showSwimlanes = !_showSwimlanes;
    }}

    private void AddCard() {{
        _editingCard = new KanbanCardModel {{
            Id = Guid.NewGuid(),
            ColumnId = _columns.FirstOrDefault()?.Id ?? ""todo"",
            CreatedAt = DateTime.UtcNow
        }};
        _showEditor = true;
    }}

    private void AddCardToColumn(string columnId, string? swimlane) {{
        _editingCard = new KanbanCardModel {{
            Id = Guid.NewGuid(),
            ColumnId = columnId,
            Swimlane = swimlane,
            CreatedAt = DateTime.UtcNow
        }};
        _showEditor = true;
    }}

    private void EditCard(Guid cardId) {{
        var card = _cards.FirstOrDefault(c => c.Id == cardId);
        if (card != null) {{
            _editingCard = card;
            _showEditor = true;
        }}
    }}

    private void HandleCardDrop(Guid cardId, string targetColumnId, string? targetSwimlane) {{
        var card = _cards.FirstOrDefault(c => c.Id == cardId);
        var targetColumn = _columns.FirstOrDefault(c => c.Id == targetColumnId);

        if (card == null || targetColumn == null) return;

        // Check WIP limit
        if (targetColumn.WipLimit > 0) {{
            var currentCount = GetCardsForColumn(targetColumnId, targetSwimlane).Count;
            if (currentCount >= targetColumn.WipLimit) {{
                // Could show a toast/alert here
                return;
            }}
        }}

        card.ColumnId = targetColumnId;
        if (targetSwimlane != null) card.Swimlane = targetSwimlane;
        card.UpdatedAt = DateTime.UtcNow;

        // Reorder cards in target column
        var cardsInColumn = GetCardsForColumn(targetColumnId, targetSwimlane);
        for (int i = 0; i < cardsInColumn.Count; i++) {{
            cardsInColumn[i].Order = i;
        }}

        StateHasChanged();
    }}

    private void SaveCard(KanbanCardModel card) {{
        var existing = _cards.FirstOrDefault(c => c.Id == card.Id);
        if (existing != null) {{
            existing.Title = card.Title;
            existing.Description = card.Description;
            existing.ColumnId = card.ColumnId;
            existing.Swimlane = card.Swimlane;
            existing.Assignee = card.Assignee;
            existing.DueDate = card.DueDate;
            existing.Priority = card.Priority;
            existing.Labels = card.Labels;
            existing.UpdatedAt = DateTime.UtcNow;
        }} else {{
            card.CreatedAt = DateTime.UtcNow;
            card.Order = _cards.Count(c => c.ColumnId == card.ColumnId);
            _cards.Add(card);
        }}
        _showEditor = false;
        StateHasChanged();
    }}

    private void DeleteCard(Guid cardId) {{
        _cards.RemoveAll(c => c.Id == cardId);
        _showEditor = false;
        StateHasChanged();
    }}

    private void CloseEditor() {{
        _showEditor = false;
    }}

    // ============================================================
    // View Models
    // ============================================================

    public class KanbanColumnModel {{
        public string Id {{ get; set; }} = string.Empty;
        public string Title {{ get; set; }} = string.Empty;
        public string Color {{ get; set; }} = ""#6c757d"";
        public int WipLimit {{ get; set; }} = 0;
        public int Order {{ get; set; }}
    }}

    public class KanbanCardModel {{
        public Guid Id {{ get; set; }}
        public string Title {{ get; set; }} = string.Empty;
        public string Description {{ get; set; }} = string.Empty;
        public string ColumnId {{ get; set; }} = string.Empty;
        public string? Swimlane {{ get; set; }}
        public string? Assignee {{ get; set; }}
        public DateTime? DueDate {{ get; set; }}
        public string Priority {{ get; set; }} = ""Medium"";
        public List<string> Labels {{ get; set; }} = new();
        public int Order {{ get; set; }}
        public DateTime CreatedAt {{ get; set; }}
        public DateTime? UpdatedAt {{ get; set; }}
    }}
}}
";

    // ============================================================
    // KANBAN COLUMN - Column Component with WIP Limits
    // ============================================================

    private static string GetKanbanBoard_KanbanColumn(string name, DataObjects.EntityDefinition? entity) => $@"@* {name} - KanbanColumn.razor *@
@* Generated by Page Pattern: KanbanBoard *@

<div class=""kanban-column card shadow-sm""
     style=""min-width: 300px; max-width: 300px; background: var(--bs-gray-100);""
     @ondragover=""HandleDragOver""
     @ondragover:preventDefault=""true""
     @ondrop=""HandleDrop"">

    <div class=""card-header d-flex justify-content-between align-items-center""
         style=""border-left: 4px solid @Column.Color;"">
        <div class=""d-flex align-items-center"">
            <strong>@Column.Title</strong>
            <span class=""badge bg-secondary ms-2"">@Cards.Count</span>
            @if (Column.WipLimit > 0) {{
                <span class=""badge @(IsAtWipLimit ? ""bg-danger"" : ""bg-outline-secondary"") ms-1""
                      title=""WIP Limit"">
                    <i class=""fa-solid fa-gauge-high me-1""></i>@Cards.Count/@Column.WipLimit
                </span>
            }}
        </div>
        <button class=""btn btn-sm btn-outline-secondary"" @onclick=""@(() => OnAddCard.InvokeAsync())""
                disabled=""@IsAtWipLimit"">
            <i class=""fa-solid fa-plus""></i>
        </button>
    </div>

    <div class=""card-body p-2"" style=""min-height: 400px; max-height: calc(100vh - 280px); overflow-y: auto;"">
        @if (Cards.Count == 0) {{
            <div class=""text-center text-muted py-4"">
                <i class=""fa-regular fa-square-dashed fa-2x mb-2 opacity-50""></i>
                <p class=""small mb-0"">Drop cards here</p>
            </div>
        }} else {{
            @foreach (var card in Cards) {{
                <{name}_App_KanbanCard
                    Card=""card""
                    OnClick=""@(() => OnCardClick.InvokeAsync(card.Id))"" />
            }}
        }}
    </div>
</div>

<style>
    .kanban-column {{
        transition: box-shadow 0.2s ease;
    }}
    .kanban-column.drag-over {{
        box-shadow: 0 0 0 2px var(--bs-primary) !important;
    }}
</style>

@code {{
    [Parameter] public {name}_App_KanbanBoard.KanbanColumnModel Column {{ get; set; }} = new();
    [Parameter] public List<{name}_App_KanbanBoard.KanbanCardModel> Cards {{ get; set; }} = new();
    [Parameter] public EventCallback<(Guid cardId, string columnId)> OnCardDrop {{ get; set; }}
    [Parameter] public EventCallback<Guid> OnCardClick {{ get; set; }}
    [Parameter] public EventCallback OnAddCard {{ get; set; }}

    private bool _isDragOver = false;

    private bool IsAtWipLimit => Column.WipLimit > 0 && Cards.Count >= Column.WipLimit;

    private void HandleDragOver(DragEventArgs e) {{
        _isDragOver = true;
    }}

    private async Task HandleDrop(DragEventArgs e) {{
        _isDragOver = false;
        // The card ID is passed via the drag event data
        // In a real implementation, you'd use JS interop or a state service
        await OnCardDrop.InvokeAsync((Guid.Empty, Column.Id));
    }}
}}
";

    // ============================================================
    // KANBAN CARD - Draggable Card Component
    // ============================================================

    private static string GetKanbanBoard_KanbanCard(string name, DataObjects.EntityDefinition? entity) => $@"@* {name} - KanbanCard.razor *@
@* Generated by Page Pattern: KanbanBoard *@

<div class=""kanban-card card mb-2 @(_isDragging ? ""dragging"" : """")""
     draggable=""true""
     @ondragstart=""HandleDragStart""
     @ondragend=""HandleDragEnd""
     @onclick=""@(() => OnClick.InvokeAsync())"">

    <div class=""card-body p-2"">
        @* Labels *@
        @if (Card.Labels.Any()) {{
            <div class=""d-flex flex-wrap gap-1 mb-2"">
                @foreach (var label in Card.Labels) {{
                    <span class=""badge"" style=""@GetLabelStyle(label)"">@label</span>
                }}
            </div>
        }}

        @* Title *@
        <h6 class=""card-title mb-2"" style=""font-size: 0.9rem;"">@Card.Title</h6>

        @* Description preview *@
        @if (!string.IsNullOrEmpty(Card.Description)) {{
            <p class=""card-text text-muted small mb-2"" style=""display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden;"">
                @Card.Description
            </p>
        }}

        @* Footer with metadata *@
        <div class=""d-flex justify-content-between align-items-center"">
            <div class=""d-flex gap-2 align-items-center"">
                @* Priority indicator *@
                <span class=""badge @GetPriorityClass()"" title=""@Card.Priority priority"">
                    <i class=""fa-solid @GetPriorityIcon()""></i>
                </span>

                @* Due date *@
                @if (Card.DueDate.HasValue) {{
                    <span class=""small @(IsOverdue ? ""text-danger"" : ""text-muted"")"" title=""Due date"">
                        <i class=""fa-regular fa-calendar me-1""></i>
                        @Card.DueDate.Value.ToString(""MMM dd"")
                    </span>
                }}
            </div>

            @* Assignee avatar *@
            @if (!string.IsNullOrEmpty(Card.Assignee)) {{
                <span class=""avatar-sm rounded-circle bg-primary text-white d-flex align-items-center justify-content-center""
                      style=""width: 24px; height: 24px; font-size: 0.7rem;""
                      title=""@Card.Assignee"">
                    @Card.Assignee.Substring(0, 1).ToUpper()
                </span>
            }}
        </div>
    </div>
</div>

<style>
    .kanban-card {{
        cursor: grab;
        transition: transform 0.2s ease, box-shadow 0.2s ease;
        border: 1px solid var(--bs-gray-200);
    }}
    .kanban-card:hover {{
        box-shadow: 0 2px 8px rgba(0,0,0,0.12);
        transform: translateY(-1px);
    }}
    .kanban-card.dragging {{
        opacity: 0.5;
        cursor: grabbing;
        transform: rotate(2deg);
    }}
    .kanban-card:active {{
        cursor: grabbing;
    }}
</style>

@code {{
    [Parameter] public {name}_App_KanbanBoard.KanbanCardModel Card {{ get; set; }} = new();
    [Parameter] public EventCallback OnClick {{ get; set; }}

    private bool _isDragging = false;

    private bool IsOverdue => Card.DueDate.HasValue && Card.DueDate.Value < DateTime.Today;

    private void HandleDragStart(DragEventArgs e) {{
        _isDragging = true;
        // Store card ID for drop handling
        // In production, use JS interop or a state service to pass the ID
    }}

    private void HandleDragEnd(DragEventArgs e) {{
        _isDragging = false;
    }}

    private string GetPriorityClass() => Card.Priority switch {{
        ""High"" => ""bg-danger"",
        ""Medium"" => ""bg-warning text-dark"",
        ""Low"" => ""bg-success"",
        _ => ""bg-secondary""
    }};

    private string GetPriorityIcon() => Card.Priority switch {{
        ""High"" => ""fa-arrow-up"",
        ""Medium"" => ""fa-minus"",
        ""Low"" => ""fa-arrow-down"",
        _ => ""fa-minus""
    }};

    private string GetLabelStyle(string label) {{
        // Simple hash-based color generation for labels
        int hash = label.GetHashCode();
        string[] colors = new[] {{ ""#e91e63"", ""#9c27b0"", ""#673ab7"", ""#3f51b5"", ""#2196f3"", ""#00bcd4"", ""#009688"", ""#4caf50"", ""#ff9800"", ""#ff5722"" }};
        string color = colors[Math.Abs(hash) % colors.Length];
        return $""background-color: {{color}}; color: white;"";
    }}
}}
";

    // ============================================================
    // CARD EDITOR - Quick Edit Modal
    // ============================================================

    private static string GetKanbanBoard_CardEditor(string name, DataObjects.EntityDefinition? entity) => $@"@* {name} - CardEditor.razor *@
@* Generated by Page Pattern: KanbanBoard *@

<div class=""modal fade show d-block"" tabindex=""-1"" style=""background: rgba(0,0,0,0.5);"">
    <div class=""modal-dialog modal-lg"">
        <div class=""modal-content"">
            <div class=""modal-header"">
                <h5 class=""modal-title"">
                    <i class=""fa-solid @(IsNew ? ""fa-plus"" : ""fa-pen"") me-2""></i>
                    @(IsNew ? ""New Card"" : ""Edit Card"")
                </h5>
                <button type=""button"" class=""btn-close"" @onclick=""Cancel""></button>
            </div>

            <div class=""modal-body"">
                <div class=""row"">
                    <div class=""col-md-8"">
                        @* Title *@
                        <div class=""mb-3"">
                            <label class=""form-label"">Title <span class=""text-danger"">*</span></label>
                            <input type=""text"" class=""form-control"" @bind=""Card.Title"" placeholder=""Enter card title..."" />
                        </div>

                        @* Description *@
                        <div class=""mb-3"">
                            <label class=""form-label"">Description</label>
                            <textarea class=""form-control"" rows=""4"" @bind=""Card.Description"" placeholder=""Add a detailed description...""></textarea>
                        </div>

                        @* Labels *@
                        <div class=""mb-3"">
                            <label class=""form-label"">Labels</label>
                            <div class=""d-flex flex-wrap gap-1 mb-2"">
                                @foreach (var label in Card.Labels) {{
                                    <span class=""badge bg-primary"">
                                        @label
                                        <button type=""button"" class=""btn-close btn-close-white ms-1""
                                                style=""font-size: 0.6rem;""
                                                @onclick=""@(() => RemoveLabel(label))""></button>
                                    </span>
                                }}
                            </div>
                            <div class=""input-group input-group-sm"">
                                <input type=""text"" class=""form-control"" @bind=""_newLabel"" placeholder=""Add label...""
                                       @onkeypress=""HandleLabelKeyPress"" />
                                <button class=""btn btn-outline-secondary"" type=""button"" @onclick=""AddLabel"">
                                    <i class=""fa-solid fa-plus""></i>
                                </button>
                            </div>
                        </div>
                    </div>

                    <div class=""col-md-4"">
                        @* Column *@
                        <div class=""mb-3"">
                            <label class=""form-label"">Column</label>
                            <select class=""form-select"" @bind=""Card.ColumnId"">
                                @foreach (var col in Columns) {{
                                    <option value=""@col.Id"">@col.Title</option>
                                }}
                            </select>
                        </div>

                        @* Swimlane *@
                        @if (Swimlanes.Any()) {{
                            <div class=""mb-3"">
                                <label class=""form-label"">Swimlane</label>
                                <select class=""form-select"" @bind=""Card.Swimlane"">
                                    <option value="""">(None)</option>
                                    @foreach (var lane in Swimlanes) {{
                                        <option value=""@lane"">@lane</option>
                                    }}
                                </select>
                            </div>
                        }}

                        @* Assignee *@
                        <div class=""mb-3"">
                            <label class=""form-label"">Assignee</label>
                            <input type=""text"" class=""form-control"" @bind=""Card.Assignee"" placeholder=""Enter name..."" />
                        </div>

                        @* Due Date *@
                        <div class=""mb-3"">
                            <label class=""form-label"">Due Date</label>
                            <input type=""date"" class=""form-control"" @bind=""Card.DueDate"" />
                        </div>

                        @* Priority *@
                        <div class=""mb-3"">
                            <label class=""form-label"">Priority</label>
                            <select class=""form-select"" @bind=""Card.Priority"">
                                <option value=""Low"">Low</option>
                                <option value=""Medium"">Medium</option>
                                <option value=""High"">High</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>

            <div class=""modal-footer d-flex justify-content-between"">
                <div>
                    @if (!IsNew) {{
                        <button type=""button"" class=""btn btn-outline-danger"" @onclick=""Delete"">
                            <i class=""fa-solid fa-trash me-1""></i>Delete
                        </button>
                    }}
                </div>
                <div class=""d-flex gap-2"">
                    <button type=""button"" class=""btn btn-secondary"" @onclick=""Cancel"">Cancel</button>
                    <button type=""button"" class=""btn btn-primary"" @onclick=""Save"" disabled=""@(!IsValid)"">
                        <i class=""fa-solid fa-check me-1""></i>Save
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

@code {{
    [Parameter] public {name}_App_KanbanBoard.KanbanCardModel Card {{ get; set; }} = new();
    [Parameter] public List<{name}_App_KanbanBoard.KanbanColumnModel> Columns {{ get; set; }} = new();
    [Parameter] public List<string> Swimlanes {{ get; set; }} = new();
    [Parameter] public EventCallback<{name}_App_KanbanBoard.KanbanCardModel> OnSave {{ get; set; }}
    [Parameter] public EventCallback<Guid> OnDelete {{ get; set; }}
    [Parameter] public EventCallback OnCancel {{ get; set; }}

    private string _newLabel = string.Empty;

    private bool IsNew => Card.CreatedAt == default;
    private bool IsValid => !string.IsNullOrWhiteSpace(Card.Title);

    private async Task Save() {{
        if (IsValid) {{
            await OnSave.InvokeAsync(Card);
        }}
    }}

    private async Task Delete() {{
        await OnDelete.InvokeAsync(Card.Id);
    }}

    private async Task Cancel() {{
        await OnCancel.InvokeAsync();
    }}

    private void AddLabel() {{
        if (!string.IsNullOrWhiteSpace(_newLabel) && !Card.Labels.Contains(_newLabel)) {{
            Card.Labels.Add(_newLabel);
            _newLabel = string.Empty;
        }}
    }}

    private void RemoveLabel(string label) {{
        Card.Labels.Remove(label);
    }}

    private void HandleLabelKeyPress(KeyboardEventArgs e) {{
        if (e.Key == ""Enter"") {{
            AddLabel();
        }}
    }}
}}
";
}

#endregion
