using System.Text;

namespace FreeManager;

#region EntityTemplates - Dashboard Generation
// ============================================================================
// ENTITY WIZARD - DASHBOARD PAGE TEMPLATES
// Generates dashboard pages with stats cards, recent feed, and status grid.
// Part of: EntityTemplates.App (partial)
// ============================================================================

public static partial class EntityTemplates
{
    // ============================================================
    // DASHBOARD PAGE GENERATION
    // ============================================================

    /// <summary>
    /// Generates a dashboard page from DashboardConfig.
    /// Used by FreeAudit template for GLBA compliance dashboard.
    /// </summary>
    public static string GenerateDashboardPage(
        DataObjects.DashboardConfig config,
        DataObjects.ExternalApiConfig? apiConfig,
        List<DataObjects.EntityDefinition> entities,
        string projectName)
    {
        var sb = new StringBuilder();
        var pageName = config.PageName.ToLower();
        var controllerName = apiConfig?.ControllerName ?? "Dashboard";

        // File header
        sb.AppendLine($"@* {projectName}.App.{config.PageName}.razor - Dashboard page *@");
        sb.AppendLine($"@* Generated by Entity Builder Wizard *@");
        sb.AppendLine($"@page \"/{config.PageName}\"");
        sb.AppendLine($"@page \"/{{TenantCode}}/{config.PageName}\"");
        sb.AppendLine($"@implements IDisposable");
        sb.AppendLine($"@inject BlazorDataModel Model");
        sb.AppendLine($"@inject HttpClient Http");
        sb.AppendLine();

        // Main content wrapper
        sb.AppendLine($"@if (Model.Loaded && Model.LoggedIn && Model.View == _pageName) {{");
        sb.AppendLine($"    @if (_loading) {{");
        sb.AppendLine($"        <div class=\"container-fluid\">");
        sb.AppendLine($"            <h1 class=\"page-title\">");
        sb.AppendLine($"                <i class=\"fa-solid {config.Icon} me-2\"></i>{config.PageTitle}");
        sb.AppendLine($"            </h1>");
        sb.AppendLine($"            <div class=\"text-center py-5\"><i class=\"fa-solid fa-spinner fa-spin fa-2x\"></i></div>");
        sb.AppendLine($"        </div>");
        sb.AppendLine($"    }} else {{");
        sb.AppendLine($"        <div class=\"container-fluid\">");
        sb.AppendLine($"            <div class=\"@Model.StickyMenuClass\">");
        sb.AppendLine($"                <h1 class=\"page-title\">");
        sb.AppendLine($"                    <i class=\"fa-solid {config.Icon} me-2\"></i>{config.PageTitle}");
        sb.AppendLine($"                </h1>");
        sb.AppendLine($"            </div>");
        sb.AppendLine();

        // Stats Cards Row
        sb.AppendLine($"            @* Stats Cards *@");
        sb.AppendLine($"            <div class=\"row mb-4\">");

        foreach (var period in config.StatsPeriods)
        {
            var periodLower = period.Replace(" ", "");
            sb.AppendLine($"                <div class=\"col-md-4\">");
            sb.AppendLine($"                    <div class=\"card shadow-sm\">");
            sb.AppendLine($"                        <div class=\"card-body text-center\">");
            sb.AppendLine($"                            <h2 class=\"mb-0\">@_stats.{periodLower}.ToString(\"N0\")</h2>");
            sb.AppendLine($"                            <p class=\"text-muted mb-0\">{FormatPeriodLabel(period)}</p>");
            sb.AppendLine($"                        </div>");
            sb.AppendLine($"                    </div>");
            sb.AppendLine($"                </div>");
        }

        sb.AppendLine($"            </div>");
        sb.AppendLine();

        // Recent Events Section
        sb.AppendLine($"            @* Recent Events *@");
        sb.AppendLine($"            <div class=\"card shadow-sm mb-4\">");
        sb.AppendLine($"                <div class=\"card-header d-flex justify-content-between align-items-center\">");
        sb.AppendLine($"                    <h5 class=\"mb-0\">");
        sb.AppendLine($"                        <i class=\"fa-solid fa-clock-rotate-left me-2\"></i>Recent Events");
        sb.AppendLine($"                    </h5>");
        sb.AppendLine($"                    <a href=\"@Helpers.BuildUrl(\"{config.RecentFeedEntity}s\")\" class=\"btn btn-sm btn-outline-primary\">");
        sb.AppendLine($"                        View All <i class=\"fa-solid fa-arrow-right ms-1\"></i>");
        sb.AppendLine($"                    </a>");
        sb.AppendLine($"                </div>");
        sb.AppendLine($"                <div class=\"card-body p-0\">");
        sb.AppendLine($"                    <div class=\"table-responsive\">");
        sb.AppendLine($"                        <table class=\"table table-hover mb-0\">");
        sb.AppendLine($"                            <thead class=\"table-light\">");
        sb.AppendLine($"                                <tr>");

        foreach (var col in config.RecentFeedColumns)
        {
            sb.AppendLine($"                                    <th>{FormatColumnHeader(col)}</th>");
        }

        sb.AppendLine($"                                </tr>");
        sb.AppendLine($"                            </thead>");
        sb.AppendLine($"                            <tbody>");
        sb.AppendLine($"                                @foreach (var evt in _recentEvents) {{");
        sb.AppendLine($"                                    <tr>");

        foreach (var col in config.RecentFeedColumns)
        {
            var format = GetColumnFormat(col);
            sb.AppendLine($"                                        <td>@evt.{col}{format}</td>");
        }

        sb.AppendLine($"                                    </tr>");
        sb.AppendLine($"                                }}");
        sb.AppendLine($"                            </tbody>");
        sb.AppendLine($"                        </table>");
        sb.AppendLine($"                    </div>");
        sb.AppendLine($"                </div>");
        sb.AppendLine($"            </div>");
        sb.AppendLine();

        // Status Grid Section (if configured)
        if (!string.IsNullOrEmpty(config.StatusGridEntity))
        {
            sb.AppendLine($"            @* Source Systems Status *@");
            sb.AppendLine($"            <div class=\"card shadow-sm\">");
            sb.AppendLine($"                <div class=\"card-header d-flex justify-content-between align-items-center\">");
            sb.AppendLine($"                    <h5 class=\"mb-0\">");
            sb.AppendLine($"                        <i class=\"fa-solid fa-server me-2\"></i>Source Systems");
            sb.AppendLine($"                    </h5>");
            sb.AppendLine($"                    <a href=\"@Helpers.BuildUrl(\"{config.StatusGridEntity}s\")\" class=\"btn btn-sm btn-outline-primary\">");
            sb.AppendLine($"                        Manage <i class=\"fa-solid fa-gear ms-1\"></i>");
            sb.AppendLine($"                    </a>");
            sb.AppendLine($"                </div>");
            sb.AppendLine($"                <div class=\"card-body p-0\">");
            sb.AppendLine($"                    <div class=\"table-responsive\">");
            sb.AppendLine($"                        <table class=\"table table-hover mb-0\">");
            sb.AppendLine($"                            <thead class=\"table-light\">");
            sb.AppendLine($"                                <tr>");
            sb.AppendLine($"                                    <th>System</th>");
            sb.AppendLine($"                                    <th>Status</th>");

            if (!string.IsNullOrEmpty(config.StatusLastActivityProperty))
            {
                sb.AppendLine($"                                    <th>Last Event</th>");
            }

            if (!string.IsNullOrEmpty(config.StatusCountProperty))
            {
                sb.AppendLine($"                                    <th>Total Events</th>");
            }

            sb.AppendLine($"                                </tr>");
            sb.AppendLine($"                            </thead>");
            sb.AppendLine($"                            <tbody>");
            sb.AppendLine($"                                @foreach (var src in _sources) {{");
            sb.AppendLine($"                                    <tr>");
            sb.AppendLine($"                                        <td>@(src.DisplayName ?? src.Name)</td>");
            sb.AppendLine($"                                        <td>");
            sb.AppendLine($"                                            @if (src.{config.StatusActiveProperty}) {{");
            sb.AppendLine($"                                                <span class=\"badge bg-success\"><i class=\"fa-solid fa-circle me-1\"></i>Active</span>");
            sb.AppendLine($"                                            }} else {{");
            sb.AppendLine($"                                                <span class=\"badge bg-secondary\"><i class=\"fa-solid fa-circle me-1\"></i>Inactive</span>");
            sb.AppendLine($"                                            }}");
            sb.AppendLine($"                                        </td>");

            if (!string.IsNullOrEmpty(config.StatusLastActivityProperty))
            {
                sb.AppendLine($"                                        <td>@GetTimeAgo(src.{config.StatusLastActivityProperty})</td>");
            }

            if (!string.IsNullOrEmpty(config.StatusCountProperty))
            {
                sb.AppendLine($"                                        <td>@src.{config.StatusCountProperty}.ToString(\"N0\")</td>");
            }

            sb.AppendLine($"                                    </tr>");
            sb.AppendLine($"                                }}");
            sb.AppendLine($"                            </tbody>");
            sb.AppendLine($"                        </table>");
            sb.AppendLine($"                    </div>");
            sb.AppendLine($"                </div>");
            sb.AppendLine($"            </div>");
        }

        sb.AppendLine($"        </div>");
        sb.AppendLine($"    }}");
        sb.AppendLine($"}}");
        sb.AppendLine();

        // Code section
        sb.AppendLine($"@code {{");
        sb.AppendLine($"    [Parameter] public string? TenantCode {{ get; set; }}");
        sb.AppendLine();
        sb.AppendLine($"    private string _pageName = \"{pageName}\";");
        sb.AppendLine($"    private bool _loading = true;");
        sb.AppendLine($"    private bool _loadedData = false;");
        sb.AppendLine();
        sb.AppendLine($"    private DataObjects.{controllerName}Stats _stats = new();");
        sb.AppendLine($"    private List<DataObjects.{config.RecentFeedEntity}> _recentEvents = new();");

        if (!string.IsNullOrEmpty(config.StatusGridEntity))
        {
            sb.AppendLine($"    private List<DataObjects.{config.StatusGridEntity}> _sources = new();");
        }

        sb.AppendLine();
        sb.AppendLine($"    public void Dispose()");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        Model.OnChange -= OnDataModelUpdated;");
        sb.AppendLine($"    }}");
        sb.AppendLine();
        sb.AppendLine($"    protected override void OnInitialized()");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        Model.View = _pageName;");
        sb.AppendLine($"        Model.OnChange += OnDataModelUpdated;");
        sb.AppendLine($"    }}");
        sb.AppendLine();
        sb.AppendLine($"    protected override async Task OnAfterRenderAsync(bool firstRender)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        if (firstRender)");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            Model.TenantCodeFromUrl = TenantCode;");
        sb.AppendLine($"        }}");
        sb.AppendLine();
        sb.AppendLine($"        if (Model.Loaded && Model.LoggedIn && !_loadedData)");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            _loadedData = true;");
        sb.AppendLine($"            await LoadDataAsync();");
        sb.AppendLine($"        }}");
        sb.AppendLine($"    }}");
        sb.AppendLine();
        sb.AppendLine($"    private void OnDataModelUpdated()");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        if (Model.View == _pageName)");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            StateHasChanged();");
        sb.AppendLine($"        }}");
        sb.AppendLine($"    }}");
        sb.AppendLine();
        sb.AppendLine($"    private async Task LoadDataAsync()");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        _loading = true;");
        sb.AppendLine($"        StateHasChanged();");
        sb.AppendLine();
        sb.AppendLine($"        try");
        sb.AppendLine($"        {{");

        var routePrefix = apiConfig?.RoutePrefix ?? "api/dashboard";

        sb.AppendLine($"            // Load all data in parallel");
        sb.AppendLine($"            var statsTask = Helpers.GetOrPost<DataObjects.{controllerName}Stats>(\"{routePrefix}/stats/summary\");");
        sb.AppendLine($"            var eventsTask = Helpers.GetOrPost<List<DataObjects.{config.RecentFeedEntity}>>(\"{routePrefix}/events/recent?limit={config.RecentFeedLimit}\");");

        if (!string.IsNullOrEmpty(config.StatusGridEntity))
        {
            sb.AppendLine($"            var sourcesTask = Helpers.GetOrPost<List<DataObjects.{config.StatusGridEntity}>>(\"{routePrefix}/sources/status\");");
            sb.AppendLine();
            sb.AppendLine($"            await Task.WhenAll(statsTask, eventsTask, sourcesTask);");
        }
        else
        {
            sb.AppendLine();
            sb.AppendLine($"            await Task.WhenAll(statsTask, eventsTask);");
        }

        sb.AppendLine();
        sb.AppendLine($"            _stats = await statsTask ?? new();");
        sb.AppendLine($"            _recentEvents = await eventsTask ?? new();");

        if (!string.IsNullOrEmpty(config.StatusGridEntity))
        {
            sb.AppendLine($"            _sources = await sourcesTask ?? new();");
        }

        sb.AppendLine($"        }}");
        sb.AppendLine($"        catch (Exception ex)");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            Model.ErrorMessage($\"Error loading dashboard: {{ex.Message}}\");");
        sb.AppendLine($"        }}");
        sb.AppendLine();
        sb.AppendLine($"        _loading = false;");
        sb.AppendLine($"        StateHasChanged();");
        sb.AppendLine($"    }}");
        sb.AppendLine();

        // Time ago helper
        sb.AppendLine($"    private string GetTimeAgo(DateTime? dt)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        if (!dt.HasValue) return \"Never\";");
        sb.AppendLine($"        var diff = DateTime.UtcNow - dt.Value;");
        sb.AppendLine($"        if (diff.TotalMinutes < 1) return \"Just now\";");
        sb.AppendLine($"        if (diff.TotalMinutes < 60) return $\"{{(int)diff.TotalMinutes}} min ago\";");
        sb.AppendLine($"        if (diff.TotalHours < 24) return $\"{{(int)diff.TotalHours}} hours ago\";");
        sb.AppendLine($"        return $\"{{(int)diff.TotalDays}} days ago\";");
        sb.AppendLine($"    }}");
        sb.AppendLine($"}}");

        return sb.ToString();
    }

    // ============================================================
    // HELPER METHODS
    // ============================================================

    private static string FormatPeriodLabel(string period) => period switch
    {
        "Today" => "Today",
        "ThisWeek" => "This Week",
        "ThisMonth" => "This Month",
        "Yesterday" => "Yesterday",
        "LastWeek" => "Last Week",
        "LastMonth" => "Last Month",
        _ => period
    };

    private static string FormatColumnHeader(string column)
    {
        // Convert camelCase/PascalCase to Title Case with spaces
        var result = new StringBuilder();
        foreach (var c in column)
        {
            if (char.IsUpper(c) && result.Length > 0)
                result.Append(' ');
            result.Append(c);
        }
        return result.ToString();
    }

    private static string GetColumnFormat(string column)
    {
        // Add appropriate formatting based on column name
        if (column.Contains("At") || column.Contains("Date"))
            return ".ToString(\"g\")";
        return "";
    }
}

#endregion
