namespace FreeManager.Client;

#region PagePatterns - CustomizableDashboard
// ============================================================================
// PAGE PATTERN: CUSTOMIZABLE DASHBOARD
// User-configurable dashboard with drag-drop widgets.
//
// Generated Files:
// - Dashboard.razor - Main dashboard page with layout management
// - DashboardGrid.razor - Grid-based widget layout system
// - WidgetContainer.razor - Widget wrapper with drag/resize handles
// - WidgetPicker.razor - Modal for selecting widgets to add
// - StatsWidget.razor - Statistics/metrics display widget
// - ChartWidget.razor - Chart visualization widget
// ============================================================================

public static partial class PagePatterns
{
    /// <summary>
    /// Generate CustomizableDashboard files for the given project.
    /// </summary>
    public static List<(string FileName, string FileType, string Content)> GetCustomizableDashboardFiles(
        string projectName,
        DataObjects.EntityDefinition? entity = null)
    {
        List<(string, string, string)> files = new();

        files.Add(($"{projectName}.App.Dashboard.razor", "RazorComponent", GetCustomizableDashboard_Dashboard(projectName, entity)));
        files.Add(($"{projectName}.App.DashboardGrid.razor", "RazorComponent", GetCustomizableDashboard_DashboardGrid(projectName, entity)));
        files.Add(($"{projectName}.App.WidgetContainer.razor", "RazorComponent", GetCustomizableDashboard_WidgetContainer(projectName, entity)));
        files.Add(($"{projectName}.App.WidgetPicker.razor", "RazorComponent", GetCustomizableDashboard_WidgetPicker(projectName, entity)));
        files.Add(($"{projectName}.App.StatsWidget.razor", "RazorComponent", GetCustomizableDashboard_StatsWidget(projectName, entity)));
        files.Add(($"{projectName}.App.ChartWidget.razor", "RazorComponent", GetCustomizableDashboard_ChartWidget(projectName, entity)));

        return files;
    }

    // ============================================================
    // Dashboard.razor - Main dashboard page
    // ============================================================
    private static string GetCustomizableDashboard_Dashboard(string name, DataObjects.EntityDefinition? entity) => $@"@* {name} - Dashboard.razor - Customizable Dashboard *@
@* Generated by Page Pattern Template *@
@page ""/dashboard""
@page ""/{{TenantCode}}/dashboard""
@implements IDisposable
@inject BlazorDataModel Model
@inject IJSRuntime JS

@if (Model.Loaded && Model.LoggedIn) {{
    <div class=""dashboard-container"">
        <div class=""dashboard-header d-flex justify-content-between align-items-center mb-3"">
            <h1 class=""page-title mb-0"">
                <i class=""fa-solid fa-grip me-2""></i>Dashboard
            </h1>
            <div class=""dashboard-actions"">
                @if (_editMode) {{
                    <button class=""btn btn-success me-2"" @onclick=""SaveLayout"">
                        <i class=""fa-solid fa-save me-1""></i>Save Layout
                    </button>
                    <button class=""btn btn-secondary me-2"" @onclick=""CancelEdit"">
                        <i class=""fa-solid fa-times me-1""></i>Cancel
                    </button>
                }}
                <button class=""btn @(_editMode ? ""btn-warning"" : ""btn-outline-primary"")"" @onclick=""ToggleEditMode"">
                    <i class=""fa-solid @(_editMode ? ""fa-lock"" : ""fa-edit"") me-1""></i>
                    @(_editMode ? ""Lock Dashboard"" : ""Customize"")
                </button>
                @if (_editMode) {{
                    <button class=""btn btn-primary ms-2"" @onclick=""ShowWidgetPicker"">
                        <i class=""fa-solid fa-plus me-1""></i>Add Widget
                    </button>
                }}
            </div>
        </div>

        <{name}_App_DashboardGrid @ref=""_grid""
                         Widgets=""_widgets""
                         EditMode=""_editMode""
                         OnWidgetMoved=""HandleWidgetMoved""
                         OnWidgetResized=""HandleWidgetResized""
                         OnWidgetRemoved=""HandleWidgetRemoved"" />

        @if (_showWidgetPicker) {{
            <{name}_App_WidgetPicker OnSelect=""AddWidget"" OnClose=""HideWidgetPicker"" />
        }}
    </div>
}}

<style>
    .dashboard-container {{
        padding: 1rem;
    }}

    .dashboard-header {{
        position: sticky;
        top: 0;
        background: var(--bs-body-bg);
        z-index: 100;
        padding: 1rem 0;
        border-bottom: 1px solid var(--bs-border-color);
    }}
</style>

@code {{
    private DashboardGrid_{name}? _grid;
    private List<DashboardWidget> _widgets = new();
    private List<DashboardWidget> _originalWidgets = new();
    private bool _editMode = false;
    private bool _showWidgetPicker = false;

    public void Dispose() {{ Model.OnChange -= StateHasChanged; }}

    protected override void OnInitialized()
    {{
        Model.View = ""dashboard"";
        Model.OnChange += StateHasChanged;
        LoadLayout();
    }}

    private void LoadLayout()
    {{
        // Load saved layout from user preferences or use defaults
        _widgets = GetDefaultWidgets();
        _originalWidgets = _widgets.Select(w => w.Clone()).ToList();
    }}

    private List<DashboardWidget> GetDefaultWidgets() => new()
    {{
        new DashboardWidget {{ Id = Guid.NewGuid(), Type = ""stats"", Title = ""Total Users"", Column = 0, Row = 0, Width = 3, Height = 2, Config = new() {{ [""icon""] = ""fa-users"", [""value""] = ""1,234"", [""trend""] = ""+12%"", [""color""] = ""primary"" }} }},
        new DashboardWidget {{ Id = Guid.NewGuid(), Type = ""stats"", Title = ""Revenue"", Column = 3, Row = 0, Width = 3, Height = 2, Config = new() {{ [""icon""] = ""fa-dollar-sign"", [""value""] = ""$45,678"", [""trend""] = ""+8%"", [""color""] = ""success"" }} }},
        new DashboardWidget {{ Id = Guid.NewGuid(), Type = ""stats"", Title = ""Orders"", Column = 6, Row = 0, Width = 3, Height = 2, Config = new() {{ [""icon""] = ""fa-shopping-cart"", [""value""] = ""892"", [""trend""] = ""+23%"", [""color""] = ""info"" }} }},
        new DashboardWidget {{ Id = Guid.NewGuid(), Type = ""stats"", Title = ""Pending Tasks"", Column = 9, Row = 0, Width = 3, Height = 2, Config = new() {{ [""icon""] = ""fa-tasks"", [""value""] = ""47"", [""trend""] = ""-5%"", [""color""] = ""warning"" }} }},
        new DashboardWidget {{ Id = Guid.NewGuid(), Type = ""chart"", Title = ""Sales Overview"", Column = 0, Row = 2, Width = 6, Height = 4, Config = new() {{ [""chartType""] = ""line"" }} }},
        new DashboardWidget {{ Id = Guid.NewGuid(), Type = ""chart"", Title = ""Revenue by Category"", Column = 6, Row = 2, Width = 6, Height = 4, Config = new() {{ [""chartType""] = ""bar"" }} }}
    }};

    private void ToggleEditMode()
    {{
        _editMode = !_editMode;
        if (_editMode)
        {{
            _originalWidgets = _widgets.Select(w => w.Clone()).ToList();
        }}
    }}

    private async Task SaveLayout()
    {{
        // Persist layout to user preferences
        _editMode = false;
        _originalWidgets = _widgets.Select(w => w.Clone()).ToList();
        StateHasChanged();
    }}

    private void CancelEdit()
    {{
        _widgets = _originalWidgets.Select(w => w.Clone()).ToList();
        _editMode = false;
        StateHasChanged();
    }}

    private void ShowWidgetPicker() => _showWidgetPicker = true;
    private void HideWidgetPicker() => _showWidgetPicker = false;

    private void AddWidget(string widgetType)
    {{
        var newWidget = new DashboardWidget
        {{
            Id = Guid.NewGuid(),
            Type = widgetType,
            Title = GetWidgetTitle(widgetType),
            Column = 0,
            Row = GetNextAvailableRow(),
            Width = widgetType == ""chart"" ? 6 : 3,
            Height = widgetType == ""chart"" ? 4 : 2,
            Config = GetDefaultConfig(widgetType)
        }};
        _widgets.Add(newWidget);
        _showWidgetPicker = false;
        StateHasChanged();
    }}

    private string GetWidgetTitle(string type) => type switch
    {{
        ""stats"" => ""New Statistic"",
        ""chart"" => ""New Chart"",
        _ => ""New Widget""
    }};

    private int GetNextAvailableRow()
    {{
        if (!_widgets.Any()) return 0;
        return _widgets.Max(w => w.Row + w.Height);
    }}

    private Dictionary<string, string> GetDefaultConfig(string type) => type switch
    {{
        ""stats"" => new() {{ [""icon""] = ""fa-chart-simple"", [""value""] = ""0"", [""trend""] = ""0%"", [""color""] = ""secondary"" }},
        ""chart"" => new() {{ [""chartType""] = ""line"" }},
        _ => new()
    }};

    private void HandleWidgetMoved((Guid id, int col, int row) args)
    {{
        var widget = _widgets.FirstOrDefault(w => w.Id == args.id);
        if (widget != null)
        {{
            widget.Column = args.col;
            widget.Row = args.row;
        }}
    }}

    private void HandleWidgetResized((Guid id, int width, int height) args)
    {{
        var widget = _widgets.FirstOrDefault(w => w.Id == args.id);
        if (widget != null)
        {{
            widget.Width = Math.Max(2, Math.Min(12, args.width));
            widget.Height = Math.Max(2, Math.Min(8, args.height));
        }}
    }}

    private void HandleWidgetRemoved(Guid widgetId)
    {{
        _widgets.RemoveAll(w => w.Id == widgetId);
        StateHasChanged();
    }}

    public class DashboardWidget
    {{
        public Guid Id {{ get; set; }}
        public string Type {{ get; set; }} = ""stats"";
        public string Title {{ get; set; }} = """";
        public int Column {{ get; set; }}
        public int Row {{ get; set; }}
        public int Width {{ get; set; }} = 3;
        public int Height {{ get; set; }} = 2;
        public Dictionary<string, string> Config {{ get; set; }} = new();

        public DashboardWidget Clone() => new()
        {{
            Id = Id,
            Type = Type,
            Title = Title,
            Column = Column,
            Row = Row,
            Width = Width,
            Height = Height,
            Config = new Dictionary<string, string>(Config)
        }};
    }}
}}
";

    // ============================================================
    // DashboardGrid.razor - Grid layout for widgets
    // ============================================================
    private static string GetCustomizableDashboard_DashboardGrid(string name, DataObjects.EntityDefinition? entity) => $@"@* {name} - DashboardGrid.razor - Grid-based widget layout *@
@* Generated by Page Pattern Template *@

<div class=""dashboard-grid @(_editMode ? ""edit-mode"" : """")"">
    @foreach (var widget in Widgets)
    {{
        <{name}_App_WidgetContainer Widget=""widget""
                           EditMode=""_editMode""
                           OnMoved=""HandleMoved""
                           OnResized=""HandleResized""
                           OnRemoved=""HandleRemoved"" />
    }}
</div>

<style>
    .dashboard-grid {{
        display: grid;
        grid-template-columns: repeat(12, 1fr);
        grid-auto-rows: minmax(60px, auto);
        gap: 1rem;
        min-height: 400px;
    }}

    .dashboard-grid.edit-mode {{
        background-image:
            linear-gradient(to right, rgba(0,0,0,0.05) 1px, transparent 1px),
            linear-gradient(to bottom, rgba(0,0,0,0.05) 1px, transparent 1px);
        background-size: calc(100% / 12) 60px;
        border: 2px dashed var(--bs-primary);
        border-radius: 0.5rem;
        padding: 0.5rem;
    }}
</style>

@code {{
    [Parameter] public List<Dashboard_{name}.DashboardWidget> Widgets {{ get; set; }} = new();
    [Parameter] public bool EditMode {{ get; set; }}
    [Parameter] public EventCallback<(Guid id, int col, int row)> OnWidgetMoved {{ get; set; }}
    [Parameter] public EventCallback<(Guid id, int width, int height)> OnWidgetResized {{ get; set; }}
    [Parameter] public EventCallback<Guid> OnWidgetRemoved {{ get; set; }}

    private bool _editMode => EditMode;

    private async Task HandleMoved((Guid id, int col, int row) args)
    {{
        await OnWidgetMoved.InvokeAsync(args);
    }}

    private async Task HandleResized((Guid id, int width, int height) args)
    {{
        await OnWidgetResized.InvokeAsync(args);
    }}

    private async Task HandleRemoved(Guid widgetId)
    {{
        await OnWidgetRemoved.InvokeAsync(widgetId);
    }}
}}
";

    // ============================================================
    // WidgetContainer.razor - Widget wrapper with controls
    // ============================================================
    private static string GetCustomizableDashboard_WidgetContainer(string name, DataObjects.EntityDefinition? entity) => $@"@* {name} - WidgetContainer.razor - Widget container with drag/resize *@
@* Generated by Page Pattern Template *@

<div class=""widget-container @(_editMode ? ""editable"" : """")""
     style=""grid-column: span @Widget.Width; grid-row: span @Widget.Height; grid-column-start: @(Widget.Column + 1); grid-row-start: @(Widget.Row + 1);""
     draggable=""@_editMode""
     @ondragstart=""HandleDragStart""
     @ondragend=""HandleDragEnd"">

    @if (_editMode)
    {{
        <div class=""widget-controls"">
            <button class=""btn btn-sm btn-link text-muted"" @onclick=""() => MoveWidget(-1, 0)"" title=""Move Left"">
                <i class=""fa-solid fa-arrow-left""></i>
            </button>
            <button class=""btn btn-sm btn-link text-muted"" @onclick=""() => MoveWidget(1, 0)"" title=""Move Right"">
                <i class=""fa-solid fa-arrow-right""></i>
            </button>
            <button class=""btn btn-sm btn-link text-muted"" @onclick=""() => MoveWidget(0, -1)"" title=""Move Up"">
                <i class=""fa-solid fa-arrow-up""></i>
            </button>
            <button class=""btn btn-sm btn-link text-muted"" @onclick=""() => MoveWidget(0, 1)"" title=""Move Down"">
                <i class=""fa-solid fa-arrow-down""></i>
            </button>
            <span class=""mx-1"">|</span>
            <button class=""btn btn-sm btn-link text-muted"" @onclick=""() => ResizeWidget(1, 0)"" title=""Wider"">
                <i class=""fa-solid fa-arrows-left-right""></i>+
            </button>
            <button class=""btn btn-sm btn-link text-muted"" @onclick=""() => ResizeWidget(-1, 0)"" title=""Narrower"">
                <i class=""fa-solid fa-arrows-left-right""></i>-
            </button>
            <button class=""btn btn-sm btn-link text-muted"" @onclick=""() => ResizeWidget(0, 1)"" title=""Taller"">
                <i class=""fa-solid fa-arrows-up-down""></i>+
            </button>
            <button class=""btn btn-sm btn-link text-muted"" @onclick=""() => ResizeWidget(0, -1)"" title=""Shorter"">
                <i class=""fa-solid fa-arrows-up-down""></i>-
            </button>
            <span class=""mx-1"">|</span>
            <button class=""btn btn-sm btn-link text-danger"" @onclick=""RemoveWidget"" title=""Remove"">
                <i class=""fa-solid fa-trash""></i>
            </button>
        </div>
    }}

    <div class=""widget-content"">
        @switch (Widget.Type)
        {{
            case ""stats"":
                <{name}_App_StatsWidget Title=""@Widget.Title"" Config=""@Widget.Config"" />
                break;
            case ""chart"":
                <{name}_App_ChartWidget Title=""@Widget.Title"" Config=""@Widget.Config"" />
                break;
            default:
                <div class=""p-3 text-muted"">Unknown widget type: @Widget.Type</div>
                break;
        }}
    </div>

    @if (_editMode)
    {{
        <div class=""widget-resize-handle"" @onmousedown=""StartResize"">
            <i class=""fa-solid fa-grip""></i>
        </div>
    }}
</div>

<style>
    .widget-container {{
        background: var(--bs-body-bg);
        border: 1px solid var(--bs-border-color);
        border-radius: 0.5rem;
        box-shadow: 0 2px 4px rgba(0,0,0,0.05);
        overflow: hidden;
        display: flex;
        flex-direction: column;
        transition: box-shadow 0.2s, transform 0.2s;
    }}

    .widget-container.editable {{
        cursor: move;
        border: 2px dashed var(--bs-primary);
    }}

    .widget-container.editable:hover {{
        box-shadow: 0 4px 12px rgba(0,0,0,0.15);
        transform: translateY(-2px);
    }}

    .widget-controls {{
        display: flex;
        align-items: center;
        justify-content: center;
        background: var(--bs-light);
        padding: 0.25rem;
        border-bottom: 1px solid var(--bs-border-color);
        flex-wrap: wrap;
        gap: 0.25rem;
    }}

    .widget-controls .btn {{
        padding: 0.125rem 0.375rem;
        font-size: 0.75rem;
    }}

    .widget-content {{
        flex: 1;
        overflow: auto;
    }}

    .widget-resize-handle {{
        position: absolute;
        bottom: 0;
        right: 0;
        width: 24px;
        height: 24px;
        background: var(--bs-light);
        border-top-left-radius: 0.5rem;
        display: flex;
        align-items: center;
        justify-content: center;
        cursor: nwse-resize;
        color: var(--bs-secondary);
    }}

    .widget-resize-handle:hover {{
        background: var(--bs-primary);
        color: white;
    }}
</style>

@code {{
    [Parameter] public Dashboard_{name}.DashboardWidget Widget {{ get; set; }} = new();
    [Parameter] public bool EditMode {{ get; set; }}
    [Parameter] public EventCallback<(Guid id, int col, int row)> OnMoved {{ get; set; }}
    [Parameter] public EventCallback<(Guid id, int width, int height)> OnResized {{ get; set; }}
    [Parameter] public EventCallback<Guid> OnRemoved {{ get; set; }}

    private bool _editMode => EditMode;
    private bool _isDragging = false;

    private void HandleDragStart()
    {{
        _isDragging = true;
    }}

    private void HandleDragEnd()
    {{
        _isDragging = false;
    }}

    private async Task MoveWidget(int colDelta, int rowDelta)
    {{
        var newCol = Math.Max(0, Math.Min(12 - Widget.Width, Widget.Column + colDelta));
        var newRow = Math.Max(0, Widget.Row + rowDelta);
        await OnMoved.InvokeAsync((Widget.Id, newCol, newRow));
    }}

    private async Task ResizeWidget(int widthDelta, int heightDelta)
    {{
        var newWidth = Math.Max(2, Math.Min(12, Widget.Width + widthDelta));
        var newHeight = Math.Max(2, Math.Min(8, Widget.Height + heightDelta));
        await OnResized.InvokeAsync((Widget.Id, newWidth, newHeight));
    }}

    private async Task RemoveWidget()
    {{
        await OnRemoved.InvokeAsync(Widget.Id);
    }}

    private void StartResize()
    {{
        // Resize functionality handled by CSS and button controls
    }}
}}
";

    // ============================================================
    // WidgetPicker.razor - Modal for adding widgets
    // ============================================================
    private static string GetCustomizableDashboard_WidgetPicker(string name, DataObjects.EntityDefinition? entity) => $@"@* {name} - WidgetPicker.razor - Widget selection modal *@
@* Generated by Page Pattern Template *@

<div class=""modal fade show d-block"" tabindex=""-1"" style=""background: rgba(0,0,0,0.5);"">
    <div class=""modal-dialog modal-lg"">
        <div class=""modal-content"">
            <div class=""modal-header"">
                <h5 class=""modal-title"">
                    <i class=""fa-solid fa-plus me-2""></i>Add Widget
                </h5>
                <button type=""button"" class=""btn-close"" @onclick=""Close""></button>
            </div>
            <div class=""modal-body"">
                <p class=""text-muted mb-4"">Select a widget type to add to your dashboard:</p>

                <div class=""row g-3"">
                    @foreach (var widget in _availableWidgets)
                    {{
                        <div class=""col-md-4"">
                            <div class=""card widget-option h-100"" @onclick=""() => SelectWidget(widget.Type)"">
                                <div class=""card-body text-center"">
                                    <div class=""widget-icon mb-3"">
                                        <i class=""fa-solid @widget.Icon fa-3x text-@widget.Color""></i>
                                    </div>
                                    <h5 class=""card-title"">@widget.Name</h5>
                                    <p class=""card-text text-muted small"">@widget.Description</p>
                                </div>
                            </div>
                        </div>
                    }}
                </div>
            </div>
            <div class=""modal-footer"">
                <button type=""button"" class=""btn btn-secondary"" @onclick=""Close"">Cancel</button>
            </div>
        </div>
    </div>
</div>

<style>
    .widget-option {{
        cursor: pointer;
        transition: transform 0.2s, box-shadow 0.2s;
        border: 2px solid transparent;
    }}

    .widget-option:hover {{
        transform: translateY(-4px);
        box-shadow: 0 8px 16px rgba(0,0,0,0.1);
        border-color: var(--bs-primary);
    }}

    .widget-icon {{
        width: 80px;
        height: 80px;
        margin: 0 auto;
        display: flex;
        align-items: center;
        justify-content: center;
        background: var(--bs-light);
        border-radius: 50%;
    }}
</style>

@code {{
    [Parameter] public EventCallback<string> OnSelect {{ get; set; }}
    [Parameter] public EventCallback OnClose {{ get; set; }}

    private List<WidgetOption> _availableWidgets = new()
    {{
        new WidgetOption {{ Type = ""stats"", Name = ""Statistics Card"", Description = ""Display a key metric with trend indicator"", Icon = ""fa-chart-simple"", Color = ""primary"" }},
        new WidgetOption {{ Type = ""chart"", Name = ""Chart Widget"", Description = ""Visualize data with line, bar, or pie charts"", Icon = ""fa-chart-line"", Color = ""success"" }}
    }};

    private async Task SelectWidget(string widgetType)
    {{
        await OnSelect.InvokeAsync(widgetType);
    }}

    private async Task Close()
    {{
        await OnClose.InvokeAsync();
    }}

    private class WidgetOption
    {{
        public string Type {{ get; set; }} = """";
        public string Name {{ get; set; }} = """";
        public string Description {{ get; set; }} = """";
        public string Icon {{ get; set; }} = """";
        public string Color {{ get; set; }} = ""primary"";
    }}
}}
";

    // ============================================================
    // StatsWidget.razor - Statistics/metrics widget
    // ============================================================
    private static string GetCustomizableDashboard_StatsWidget(string name, DataObjects.EntityDefinition? entity) => $@"@* {name} - StatsWidget.razor - Statistics display widget *@
@* Generated by Page Pattern Template *@

<div class=""stats-widget h-100"">
    <div class=""stats-card h-100 d-flex flex-column"">
        <div class=""stats-header d-flex justify-content-between align-items-start"">
            <div class=""stats-icon bg-@_color bg-opacity-10 text-@_color"">
                <i class=""fa-solid @_icon""></i>
            </div>
            <span class=""badge @(_trendPositive ? ""bg-success"" : ""bg-danger"")"">
                <i class=""fa-solid @(_trendPositive ? ""fa-arrow-up"" : ""fa-arrow-down"") me-1""></i>
                @_trend
            </span>
        </div>
        <div class=""stats-body flex-grow-1 d-flex flex-column justify-content-center"">
            <h2 class=""stats-value mb-1"">@_value</h2>
            <p class=""stats-title text-muted mb-0"">@Title</p>
        </div>
        <div class=""stats-footer text-muted small"">
            <i class=""fa-solid fa-clock me-1""></i>Updated just now
        </div>
    </div>
</div>

<style>
    .stats-widget {{
        padding: 1rem;
    }}

    .stats-card {{
        padding: 1rem;
    }}

    .stats-icon {{
        width: 48px;
        height: 48px;
        border-radius: 0.5rem;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 1.25rem;
    }}

    .stats-value {{
        font-size: 2rem;
        font-weight: 700;
        color: var(--bs-dark);
    }}

    .stats-title {{
        font-size: 0.875rem;
        font-weight: 500;
    }}

    .stats-footer {{
        padding-top: 0.75rem;
        border-top: 1px solid var(--bs-border-color);
    }}
</style>

@code {{
    [Parameter] public string Title {{ get; set; }} = ""Statistic"";
    [Parameter] public Dictionary<string, string> Config {{ get; set; }} = new();

    private string _icon => Config.GetValueOrDefault(""icon"", ""fa-chart-simple"");
    private string _value => Config.GetValueOrDefault(""value"", ""0"");
    private string _trend => Config.GetValueOrDefault(""trend"", ""0%"");
    private string _color => Config.GetValueOrDefault(""color"", ""primary"");
    private bool _trendPositive => !_trend.StartsWith(""-"");
}}
";

    // ============================================================
    // ChartWidget.razor - Chart visualization widget
    // ============================================================
    private static string GetCustomizableDashboard_ChartWidget(string name, DataObjects.EntityDefinition? entity) => $@"@* {name} - ChartWidget.razor - Chart visualization widget *@
@* Generated by Page Pattern Template *@

<div class=""chart-widget h-100 d-flex flex-column"">
    <div class=""chart-header d-flex justify-content-between align-items-center p-3 border-bottom"">
        <h6 class=""mb-0"">
            <i class=""fa-solid @_chartIcon me-2 text-primary""></i>@Title
        </h6>
        <div class=""btn-group btn-group-sm"">
            <button class=""btn @(_chartType == ""line"" ? ""btn-primary"" : ""btn-outline-primary"")"" @onclick=""@(() => SetChartType(""line""))"">
                <i class=""fa-solid fa-chart-line""></i>
            </button>
            <button class=""btn @(_chartType == ""bar"" ? ""btn-primary"" : ""btn-outline-primary"")"" @onclick=""@(() => SetChartType(""bar""))"">
                <i class=""fa-solid fa-chart-bar""></i>
            </button>
            <button class=""btn @(_chartType == ""pie"" ? ""btn-primary"" : ""btn-outline-primary"")"" @onclick=""@(() => SetChartType(""pie""))"">
                <i class=""fa-solid fa-chart-pie""></i>
            </button>
        </div>
    </div>
    <div class=""chart-body flex-grow-1 p-3"">
        <div class=""chart-placeholder d-flex flex-column align-items-center justify-content-center h-100 text-muted"">
            @if (_chartType == ""line"")
            {{
                <svg viewBox=""0 0 200 100"" class=""chart-svg"">
                    <polyline points=""10,80 40,60 70,70 100,40 130,50 160,20 190,30""
                              fill=""none"" stroke=""currentColor"" stroke-width=""2"" class=""text-primary"" />
                    <circle cx=""10"" cy=""80"" r=""4"" fill=""currentColor"" class=""text-primary"" />
                    <circle cx=""40"" cy=""60"" r=""4"" fill=""currentColor"" class=""text-primary"" />
                    <circle cx=""70"" cy=""70"" r=""4"" fill=""currentColor"" class=""text-primary"" />
                    <circle cx=""100"" cy=""40"" r=""4"" fill=""currentColor"" class=""text-primary"" />
                    <circle cx=""130"" cy=""50"" r=""4"" fill=""currentColor"" class=""text-primary"" />
                    <circle cx=""160"" cy=""20"" r=""4"" fill=""currentColor"" class=""text-primary"" />
                    <circle cx=""190"" cy=""30"" r=""4"" fill=""currentColor"" class=""text-primary"" />
                </svg>
            }}
            else if (_chartType == ""bar"")
            {{
                <svg viewBox=""0 0 200 100"" class=""chart-svg"">
                    <rect x=""10"" y=""40"" width=""25"" height=""55"" fill=""currentColor"" class=""text-primary"" opacity=""0.8"" />
                    <rect x=""45"" y=""20"" width=""25"" height=""75"" fill=""currentColor"" class=""text-success"" opacity=""0.8"" />
                    <rect x=""80"" y=""50"" width=""25"" height=""45"" fill=""currentColor"" class=""text-info"" opacity=""0.8"" />
                    <rect x=""115"" y=""10"" width=""25"" height=""85"" fill=""currentColor"" class=""text-warning"" opacity=""0.8"" />
                    <rect x=""150"" y=""30"" width=""25"" height=""65"" fill=""currentColor"" class=""text-danger"" opacity=""0.8"" />
                </svg>
            }}
            else
            {{
                <svg viewBox=""0 0 100 100"" class=""chart-svg pie"">
                    <circle cx=""50"" cy=""50"" r=""40"" fill=""transparent"" stroke=""currentColor"" stroke-width=""20""
                            stroke-dasharray=""62.8 188.4"" transform=""rotate(-90 50 50)"" class=""text-primary"" />
                    <circle cx=""50"" cy=""50"" r=""40"" fill=""transparent"" stroke=""currentColor"" stroke-width=""20""
                            stroke-dasharray=""50.24 188.4"" stroke-dashoffset=""-62.8"" transform=""rotate(-90 50 50)"" class=""text-success"" />
                    <circle cx=""50"" cy=""50"" r=""40"" fill=""transparent"" stroke=""currentColor"" stroke-width=""20""
                            stroke-dasharray=""37.68 188.4"" stroke-dashoffset=""-113.04"" transform=""rotate(-90 50 50)"" class=""text-warning"" />
                    <circle cx=""50"" cy=""50"" r=""40"" fill=""transparent"" stroke=""currentColor"" stroke-width=""20""
                            stroke-dasharray=""37.68 188.4"" stroke-dashoffset=""-150.72"" transform=""rotate(-90 50 50)"" class=""text-info"" />
                </svg>
            }}
            <p class=""mt-3 small"">Sample @_chartType chart - Connect to data source</p>
        </div>
    </div>
    <div class=""chart-footer p-2 border-top d-flex justify-content-between align-items-center text-muted small"">
        <span><i class=""fa-solid fa-database me-1""></i>Sample Data</span>
        <button class=""btn btn-sm btn-link p-0"">
            <i class=""fa-solid fa-expand""></i> Expand
        </button>
    </div>
</div>

<style>
    .chart-widget {{
        background: var(--bs-body-bg);
    }}

    .chart-svg {{
        width: 100%;
        max-width: 300px;
        height: auto;
    }}

    .chart-svg.pie {{
        max-width: 150px;
    }}

    .chart-placeholder {{
        min-height: 150px;
    }}
</style>

@code {{
    [Parameter] public string Title {{ get; set; }} = ""Chart"";
    [Parameter] public Dictionary<string, string> Config {{ get; set; }} = new();

    private string _chartType => Config.GetValueOrDefault(""chartType"", ""line"");

    private string _chartIcon => _chartType switch
    {{
        ""line"" => ""fa-chart-line"",
        ""bar"" => ""fa-chart-bar"",
        ""pie"" => ""fa-chart-pie"",
        _ => ""fa-chart-simple""
    }};

    private void SetChartType(string type)
    {{
        Config[""chartType""] = type;
        StateHasChanged();
    }}
}}
";
}

#endregion
