using Microsoft.EntityFrameworkCore;

namespace FreeGLBA.EFModels.EFModels;

// ============================================================================
// FREEGLBA PROJECT - EFDataModel Extension
// DbSet properties for generated entities
// Generated by Entity Builder Wizard
// ============================================================================

public partial class EFDataModel : DbContext
{
    public virtual DbSet<SourceSystemItem> SourceSystems { get; set; } = null!;
    public virtual DbSet<AccessEventItem> AccessEvents { get; set; } = null!;
    public virtual DbSet<DataSubjectItem> DataSubjects { get; set; } = null!;
    public virtual DbSet<ComplianceReportItem> ComplianceReports { get; set; } = null!;
}
